### ISSUE TITLE
"HTTP Login" could be "Web login" or just "Login"

### ISSUE THREAD

**Issue by mikehearn** [trezor/connect#1]
Screenshot looks hot! I will try it out soon!

I noticed that the text on screen says "HTTP Login", even for an https web page? That seems confusing and HTTP is perhaps unnecessarily jargony. Indeed does it even need to say HTTP or web? What if someone wanted to use the protocol for IMAP or some custom app specific protocol?

**Comment by slush0** [comment]
Agree, we may display "web" instead of HTTP in the future. But other protocols are supported as well (SSH, for example). That's why it prints "HTTP" now.

**Comment by prusnak** [comment]
It should show HTTPS for https page. It just takes the given protocol and makes it an uppercase version of it.

**Comment by prusnak** [comment]
HTTPS is now shown as "Web login": https://github.com/trezor/trezor-mcu/blob/master/firmware/layout2.c#L305

HTTP might be disabled in the future completely.
