### ISSUE TITLE
Trezor-Connect traditional sign feature

### ISSUE THREAD

**Issue by ondra-novak** [trezor/connect#10]
I am missing traditional "sign a message" feature as it is available in mytrezor.com.

**Comment by prusnak** [comment]
See "Sign" examples here: http://trezor.github.io/connect/examples/

**Comment by slush0** [comment]
Reopening, because signing *messages* is really missing.

**Comment by prusnak** [comment]
Ah, sorry I missed that this is about signing messages, not transactions.

**Comment by ondra-novak** [comment]
BUMP

Any news about subj? I am starting to develop a service where every user action must be signed. Using Trezor could be the best solution.

**Comment by prusnak** [comment]
Closed by #21

**Comment by runn1ng** [comment]
Can't wait to see the service :) thanks for the code
