### ISSUE TITLE
Webusb does not work when in Google chrome incognito mode

### ISSUE THREAD

**Issue by karliatto** [trezor/connect#1001]
**Describe the bug**
When using latest commit develop branch connect in suite app webusb does not work in Google chrome incognito mode.

**Info:**
Commit: 745e9a50a0c60a6535f97a398d0ed26eb8390fc0 latest develop
Browser: Google chrome Version 95.0.4638.69 (Official Build) (64-bit)
OS: Pop!_OS 21.04

**How to reproduce**
Steps to reproduce:
1. Run connect in dev mode like `yarn dev`
2. Use the localhost version of connect in suite app like:
    ```javascript
            await TrezorConnect.init({
            connectSrc: 'https://localhost:8088/',
            transportReconnect: true,
            debug: true,
            popup: false,
            webusb: isWeb(),
            pendingTransportEvent: getState().devices.length < 1,
            manifest: {
                email: 'info@trezor.io',
                appUrl: '@trezor/suite',
            },
        });
     ```
3. Run localhost version of suite app and try to use webusb in Google chrome incognito mode
4. Suite app does not allow user to select the device as usually when using webusb

Notes:
* With the same setup in Google chrome without incognito mode it works as expected.
* Webusb with suite app is working as expected also in Google chorme incognito mode when:
    * Using connect as npm dependecy `8.2.5-beta.1`
    * In production

**Comment by Zwilla** [comment]
read this!  It is not a BUG!!!
https://github.com/WICG/webusb/issues/73

**Comment by karliatto** [comment]
This issue is not reproducible when using suite with https in incognito mode, therefore I am closing it.
