### ISSUE TITLE
how to sign the tx with trezor?(ethereum smart contract deployment)

### ISSUE THREAD

**Issue by leochan007** [trezor/connect#101]
i wanna deploy a smart contract to mainnet of ethereum. how to sign the tx? 
using trezor api or using the deploy function on https://www.myetherwallet.com/#contracts ?

**Comment by prusnak** [comment]
Check this example: https://github.com/trezor/connect/blob/master/examples/signtx-ethereum.html

**Comment by leochan007** [comment]
@prusnak thx for example.  i do wanna know is there a example for deploy *.sol contract to ethereum mainnet via trezor account.

in your example,
var data = 'a9059cbb000000000000000000000000dc7359317ef4cc723a3980213a013c0433a338910000000000000000000000000000000000000000000000000000000001312d00'; // some contract data 

is the field "data" is the compiled src from solc or truffle compile?

**Comment by prusnak** [comment]
This is really out of scope for Connect. Connect does attach exactly the data you give it to.

To learn what to put into the data I suggest you study how contract deployment is being done on Ethereum network and this is not really specific to TREZOR or Connect.
