### ISSUE TITLE
Unknown addresses returned from getAccountInfo advanced

### ISSUE THREAD

**Issue by tommq** [trezor/connect#1026]
When the getAccountInfo endpoint is used as:

`TrezorConnect.getAccountInfo({
  coin: "test",
  details: "tokens"
});`

The returned addresses have derivation path: **"unknown/0/0/0"**

No error is returned.

Steps to reproduce:

1. Go to https://trezor.github.io/connect-explorer/#/method/getAccountInfo-advanced
2. Empty the "OR BIP44 PATH" field
3. Select DETAILS: Tokens (Account addresses)
4. See addresses in response

**Comment by mroz22** [comment]
Should be fixed now.

**Comment by tsusanka** [comment]
Fixed in https://github.com/trezor/connect/commit/eaa0fc3f4b97434d1e0e55878b70e481545491b2 (for reference).

**Comment by tsusanka** [comment]
And probably introduced in https://github.com/trezor/connect/commit/4e6abd328e079e8d2790e440eeb0df4ddb1f6be2.
