### ISSUE TITLE
coins: Correct decred block time.

### ISSUE THREAD

**Issue by JoeGruffins** [trezor/connect#1038]
Decred's current `blocktime_seconds` values in coins.json:
https://github.com/trezor/connect/blob/1daabdd0230c04d77596e63ec7387e3aaa5515cd/src/data/coins.json#L749-L838

Mainnet should be 300 and testnet 120:
https://github.com/decred/dcrd/blob/bcc5023fa94d2e0895682012081fbe3cef3d6b51/chaincfg/mainnetparams.go#L96
https://github.com/decred/dcrd/blob/bcc5023fa94d2e0895682012081fbe3cef3d6b51/chaincfg/testnetparams.go#L91

**Comment by mroz22** [comment]
Hi, we take these data from trezor-firmware repo. I would say that from this file most probably https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/decred.json
So please open PR there if you wish to change this.

**Comment by JoeGruffins** [comment]
Thank you! https://github.com/trezor/trezor-firmware/issues/2099
