### ISSUE TITLE
requestLogin on localhost server does not redirect to connect.trezor.io

### ISSUE THREAD

**Issue by Azael05x** [trezor/connect#104]
I am trying to run simple TrezorConnect flow using `https://connect.trezor.io/4/connect.js` based on this repo example: https://github.com/trezor/connect/blob/v4/examples/login-js.html

When I click on button to start flow, popup opens with link `http://localhost:4200/popup/popup.html?v=12341234` with message inside: `Cannot GET /popup/popup.html`

But when I try to run example as static html without server - it works and it redirects to connect.trezor.io.

I understand that it is trying to serve popup from my server. Maybe I am missing some extra configuration, to allow Trezor to execute it's logic?

I'm running Angular on `webpack-dev-server`

**Comment by Azael05x** [comment]
It works with version 3

**Comment by szymonlesisz** [comment]
Hi @Azael05x ,

To override this behaviour just set global variable before you include connect.js
<script>
window.TREZOR_POPUP_ORIGIN = 'https://connect.trezor.io';
</script>
.
.
.
<script src="https://connect.trezor.io/4/connect.js"></script>

This should help for now, we will fix this in next build.
Thanks for reporting

**Comment by Azael05x** [comment]
It worked, thanks.
