### ISSUE TITLE
NEM is not a valid coin name?

### ISSUE THREAD

**Issue by dgobaud** [trezor/connect#106]
NEM doesn't seem to be included :( https://github.com/trezor/connect/blob/7919d47ca9d483cf303d77907505ccc7d389c68c/popup/coins.json

**Comment by prusnak** [comment]
coins.json is just a list of bitcoin-like coins.

NEM uses different communication mechanism and does not have to be in
this list.

**Comment by dgobaud** [comment]
thanks I found nemGetAddress
