### ISSUE TITLE
Trezor "recover-coins" doesn't detect addresses behind the gap limit.

### ISSUE THREAD

**Issue by jhoenicke** [trezor/connect#108]
If I send LTC to my BTC address, the recover-coins tool should scan the BTC chain to determine the last used address+gap limit and only then scan the LTC chain to find the lost coins.  Otherwise it wouldn't find the coins if more than 20 BTC addresses were used.

As an example I sent some LTC to 3-address BTC in slip-14.

**Comment by szymonlesisz** [comment]
Hi @jhoenicke , it should be fixed by now
