### ISSUE TITLE
`ethereumSignMessage()` not working on Trezor model T

### ISSUE THREAD

**Issue by williamchong** [trezor/connect#109]
in https://connect.trezor.io/4/examples/signmsg-ethereum.html I cannot sign any ethereum message.
The connect window pops up, loads for a while and i get
```
{
  "success": false,
  "error": "Unexpected message"
}
```

![image](https://user-images.githubusercontent.com/6198816/37833006-31d40c2c-2ee5-11e8-9b59-c1c0872af5ee.png)

my device is Trezor Model T, firmware `2.0.5`
My mac env is OSX `10.13.3`, Chrome Version `65.0.3325.181 (64-bit)`

I am also encountering this error when trying to call `ethereumSignMessage()` when developing my dapp
Anything I am doing wrong?

**Comment by prusnak** [comment]
We disabled Ethereum signing because there are multiple competing standards. One there is a consensus which one to use (most probably EIP712), we will implement it.

**Comment by brunobar79** [comment]
@prusnak  https://github.com/ethereum/EIPs/pull/712 was merged yesterday. Can you guys reopen this issue ?

**Comment by prusnak** [comment]
The original sign/verify method will be re-enabled in the next firmware update.

**Comment by sterlu** [comment]
@prusnak I see the the signing is already updated per EIP 712 (trezor/trezor-mcu@1f470cf). Any ETA/plans for the fw update?

**Comment by brunobar79** [comment]
@prusnak  Can you confirm if this was re-enabled on https://github.com/trezor/trezor-core/releases/tag/v2.0.7 ? 

EDIT: nvm - I just saw it's working on the simulator. Thanks!

**Comment by prusnak** [comment]
Yes, confirmed. The firmware will be released on Monday.
