### ISSUE TITLE
Can I get or change any info about Trezor device?

### ISSUE THREAD

**Issue by iamkd** [trezor/connect#111]
Trezor.js allowed us to get device status (is it connected, is the bridge running etc), label and version or make different changes like setting new PIN. For now whitelisting is deprecated, so we cannot use trezor.js for our service. How can we get all those functions as in trezor.js, or at least the device label? And when can we get these features?

**Comment by iamkd** [comment]
I see the TPM version of trezor-connect that seems to allow many great features. Could you please tell us when do you plan to release it?

**Comment by szymonlesisz** [comment]
Hi @iamkd,
Yes, we are currently working on new version, which for now is used only in Trezor Password Manager project (TMP) but soon will be available in public as version 5.
Unfortunately i cannot give a specific date, but it shouldn't be long.
