### ISSUE TITLE
https://connect.trezor.io/4/examples/xpubkey.html returns incorrect xpubkey

### ISSUE THREAD

**Issue by liangfenxiaodao** [trezor/connect#112]
When I go to `https://wallet.trezor.io` -> `Basic` -> `Account public keys`, it shows me a key starting with `ypub...` which I can use on blockonomics website and get the addresses.

While if I go to https://connect.trezor.io/4/examples/xpubkey.html, it show me a key starting with `xpub...` and if I copy/paste it to blockonomics, it does show me some addresses, but the addresses are incorrect and have no balance.

I also tried Trezor Low-level HID API to get public key, but I still get a `xpub...` key which is the same as what I got from connect.trezor.io, but cannot return me correct addresses.

Could someone please help?

Cheers,
Jacky

**Comment by szymonlesisz** [comment]
Hi @jackylimel,

TrezorConnect version 5 will return public key in both formats in "xpub" and "xpubSegwit"(ypub) fields.
Give it a try:
https://trezor.github.io/connect-explorer/#/
