### ISSUE TITLE
multisig input alternatives

### ISSUE THREAD

**Issue by dhoffmann** [trezor/connect#116]
It would be ideal if multisig inputs could be sent with just public keys or the redeemScript. For example...

```
multisig: {
  pubkeys: ['publicKey1', 'publicKey2', 'publicKey3'],
  signatures: ['', '', ''],
  m: 2
}
```

```
multisig: 'redeemScriptHex'
```

**Comment by szymonlesisz** [comment]
Sorry, we can't do it for security reasons.
We need to generate redeemSciript on our side for proper change output verification
