### ISSUE TITLE
Ethereum Account Discovery

### ISSUE THREAD

**Issue by randomnetcat** [trezor/connect#118]
Hi, sorry if this is a stupid question, but I was wondering how to allow the user to an Ethereum account from a list. Can I just use `getAccountInfo(null, callback)`, or is that only for Bitcoin/altcoin accounts?

The documentation doesn't specify.

**Comment by szymonlesisz** [comment]
hi @meowingtwurtle,
Unfortunately TrezorConnect does not have support for Ethereum network yet, so communication need to be provided from a third party
