### ISSUE TITLE
Broadcast signed Ethereum transaction to the blockchain

### ISSUE THREAD

**Issue by amirsimhi** [trezor/connect#119]
Hello,
I signed an Ethereum transaction by your API ( by TrezorConnect.ethereumSignTx).
How can push and broadcast the resulting transaction to the Ethereum blockchain?
As I see in your api you have pushTransaction method for the Bitcoin blockchain.
Thanks.

**Comment by szymonlesisz** [comment]
connect does not have support for Ethereum network yet, communication need to be provided from a third party.
