### ISSUE TITLE
Getting 'Chain Id out of bounds' when signing ethereum transaction with private chain id: 33349

### ISSUE THREAD

**Issue by amirsimhi** [trezor/connect#120]
I'm trying to sign eth transaction by TrezorConnect.ethereumSignTx. I'm sending chain id: 33349 (that's my private chain id) and I'm getting 'Chain Id out of bounds'.

Why is this happening?

**Comment by prusnak** [comment]
Firmware version?

**Comment by or2008** [comment]
this was fixed after updating to latest firmware
