### ISSUE TITLE
Questionable behavior from ethereumSignTx

### ISSUE THREAD

**Issue by randomnetcat** [trezor/connect#121]
Hello! I'm trying to use Trezor connect to implement an ethereum integration. Obviously, this sometimes requires the Trezor to sign transactions. However, according to a JS library and the components from the sign message response, the trezor is signing with a different address's private key every time, which is different from the one returned from `ethereumGetAddress` on the same address path. This results in the transaction failing with insufficient funds, since the address the transaction is sent from ends up having 0 balance.

A) Is this intended behavior, or am I doing something wrong?
B) If so, is there any way I can force Trezor to sign using the same address that `ethereumGetAddress` returns?

**Comment by prusnak** [comment]
Show the code you are using to call EthereumSignTx

**Comment by randomnetcat** [comment]
Sorry for the long delay, here's the (reduced) code:

```js
return (new Promise((resolve, reject) => {
  connect.ethereumSignTx(
    addressPath,
    hex(tx.nonce),
    hex(tx.gasPrice),
    hex(tx.gasLimit),
    tx.to.slice(2),
    hex(tx.value),
    hex(tx.data),
    networkID,
    (response) => {
      if (response.success) 
        tx.v = prefixHex(response.v)
        tx.r = prefixHex(response.r)
        tx.s = prefixHex(response.s)

        const signedTx = new TX(tx)

        const serialized = '0x' + signedTx.serialize().toString('hex');

        console.log('trezor-signer: tx sender is ' + (signedTx.from.toString('hex')))

        resolve(serialized)
      } else {
        reject(response.error)
      }
    },
  )
}))
```

The TX object is from [this link](https://github.com/ethereumjs/ethereumjs-tx). This is trusted to correctly produce the serialized transaction and the sender address.
The tx paramater (passed out of this text) contains the arguments to the transaction.
`hex` is a function that converts a number to a hex string without prefix.
`addressPath` is constant for a specific login.

**Comment by prusnak** [comment]
What's in the `addressPath` variable? Inspect the values before call if it contains the value you think it contains.

**Comment by randomnetcat** [comment]
I can confirm that this behavior still happens even when a constant is used in place of `addressPath`.

**Comment by prusnak** [comment]
Which value do you pass as addressPath?

**Comment by randomnetcat** [comment]
`m/44'/60'/0'/0` as a string.

**Comment by randomnetcat** [comment]
Update: Just tried again with `m/44'/60'/0'/0/0` as the account path, still got a different signing address than from ethereumGetAddress.

**Comment by szymonlesisz** [comment]
Hi @meowingtwurtle,
Im pretty sure that signEthereumTx works correctly, otherwise we would get a lot of complains from MyEtherWallet users.
Could you provide an full object that you are trying to send as a parameter?

**Comment by randomnetcat** [comment]
Right, that makes sense.

I just realized, is the fact that I'm using this on a private network an issue? The `networkID` variable is "22346" (just an arbitrary ID). Could that cause it to use a different signing key? (I'm sorry that I didn't think of this before)

**Comment by szymonlesisz** [comment]
I don't think so, but its worth to try it on different network, like mainnet or ropsten

**Comment by randomnetcat** [comment]
Okay, I found that with BIP44 network 60 and `chain_id` = 1, it DOES sign with the same address as from ethereumGetAddress.

**Comment by uri-chandler** [comment]
I'm seeing a similar issue, where the address is ok until the `new TX(tx)` part:

```javascript
ethereumSignTx(..., result => {
  ...
  const txObj = new EthereumTx(tx);
  // txObj.from.toString('hex')   <-- this gives me the wrong address
  ...
});
```

**Note 1** `EthereumTx` is from the [ethereumjs-tx](https://github.com/ethereumjs/ethereumjs-tx) lib
**Note 2** Testing on a private net, chain-id `33349`, path `m/44'/60'/0'/0/0`

Not sure if this is a bug in `EthereumTx` or `TrezorConnect` (or maybe I'm just passing wrong values)

**Comment by or2008** [comment]
Having the exact same issue with private chain. glad you opened this bug, I could have burn hours on this

**Comment by randomnetcat** [comment]
Okay, apparently it still signs with a different key every time, even with BIP44 ID of 60 and chainID of 1, while still returning the same address from ethereumGetAddress

**Comment by prusnak** [comment]
Does the example from https://github.com/trezor/connect/blob/v4/examples/signtx-ethereum.html work for you? (i.e. signs always with the same key?)

**Comment by uri-chandler** [comment]
@prusnak For me this works (I think).
The issue is in the next step when passing the singed transaction into `ethereumjs-tx` to get a transaction object. That's when we get the wrong address.

If I'm not mistaken, the address derivation also uses the `signedTx.v` parameter, which is why I'm not sure if this is a **TrezorConnect** issue or something else with `ethereumjs-tx`

What else can we test?

**Comment by prusnak** [comment]
@ujc Ask the developers of ethereum-js library. Everything works as expected from our side as far as I can tell.

**Comment by prusnak** [comment]
@meowingtwurtle What firmware version do you use? Make sure you use the latest one ...

**Comment by randomnetcat** [comment]
@prusnak Using latest firmware (as of like 2 weeks ago, just got this trezor). As for whether the example works, I'm not sure how to check that (yes I'm a bit of a newbie). I know you have to use ecrecover, but that requires the hash of the transaction, which is not outputted.

**Comment by randomnetcat** [comment]
Closing as I just ran a test where I had Trezor sign the exact same transaction several times. It returned the exact same v, r, and s components every time, leading to the same public key.

Thanks for everyone's help!

**Comment by prusnak** [comment]
Where was the problem?

**Comment by randomnetcat** [comment]
Still not sure, but I now know that it is not with this library.

**Comment by randomnetcat** [comment]
Figured it out, I was interpreting the v value as hex rather than as a number.

**Comment by randomnetcat** [comment]
As a side note, is there a way to signify a private network with BIP44 indexing?

**Comment by rbanate** [comment]
@meowingtwurtle thanks for sharing. I'm encountering the same issue you mentioned. But can't seem to make it work based on the solution you provided.

From your original code:
```
return (new Promise((resolve, reject) => {
  connect.ethereumSignTx(
    addressPath,
    hex(tx.nonce),
    hex(tx.gasPrice),
    hex(tx.gasLimit),
    tx.to.slice(2),
    hex(tx.value),
    hex(tx.data),
    networkID,
    (response) => {
      if (response.success) 
        tx.v = prefixHex(response.v)
        tx.r = prefixHex(response.r)
        tx.s = prefixHex(response.s)

        const signedTx = new TX(tx)

        const serialized = '0x' + signedTx.serialize().toString('hex');

        console.log('trezor-signer: tx sender is ' + (signedTx.from.toString('hex')))

        resolve(serialized)
      } else {
        reject(response.error)
      }
    },
  )
}))
```
So for your solution did you just remove `prefixHex` for ` tx.v = prefixHex(response.v)`? I'm still getting different address. Does `prefixHex` just add `0x` prefix or it does more than that?

**Comment by rbanate** [comment]
@meowingtwurtle - nm, I was able to make it work on my end, again thanks for sharing

**Comment by brunobar79** [comment]
@rbanate I'm running into the same exact problem.  (I've already checked that tx.v is being intepreted as a number). Any idea?

**Comment by randomnetcat** [comment]
The issue for me was with the private net since there is no bip44 for
private net. It works on main and testnet.

**Comment by rbanate** [comment]
@meowingtwurtle - I was able to get around that by specifying a chainId for testnet/testrpc to i.e. 67.
@brunobar79 - aside from the chainId, you may also double check if the path used returns the same address when you do `TrezorConnect.ethereumGetAddress`.
