### ISSUE TITLE
support of multiple ethereum sign transactions

### ISSUE THREAD

**Issue by or2008** [trezor/connect#122]
Hello, I am building a web3 daap to buy sell ERC20 tokens. in one process in the dapp the user required to sign multiple transactions in a specific order, to do that I am using web3 Batch request (https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests)

I wonder how can I achieve same behaviour with Trezor, do you support signing multiple ethereum transactions? or should I call `ethereumSignTx` for each transaction at a time

**Comment by prusnak** [comment]
Yes, you should call `ethereumSignTx` for each transaction.

User needs to support each TX individually on display, so this is not a big deal anyway.

**Comment by vlddm** [comment]
> Yes, you should call `ethereumSignTx` for each transaction.
> 
> User needs to support each TX individually on display, so this is not a big deal anyway.

Sure, but user also have to look at trezor connect popup window before every transaction signing. Quite annoying and slow.
