### ISSUE TITLE
Detect connection

### ISSUE THREAD

**Issue by passabilities** [trezor/connect#124]
I am trying to figure out if it is possible to detect when/if a Trezor device is plugged in to a users computer using this library?

I've noticed that wallet.trezor.io has this feature and would like to mimic. Is this possible?

**Comment by szymonlesisz** [comment]
hi @passabilities,
Not with current version. We are currently working on new version which allow to listen for certain events, like connect/disconnect.
Unfortunately i cannot give you a specific time of release but we work hard to make it soon

**Comment by passabilities** [comment]
@szymonlesisz Awesome! Please keep us updated on any progress. Thanks!
