### ISSUE TITLE
Sign Ethereum message not working on TREZOR model T

### ISSUE THREAD

**Issue by janezkranjc** [trezor/connect#125]
https://connect.trezor.io/4/examples/signmsg-ethereum.html

In the following example, no matter the message I get the error:
```
{
  "success": false,
  "error": "Unexpected message"
}
```

The popup opens for a second or so and then closes by itself.

**Comment by janezkranjc** [comment]
I am using a TREZOR model T.

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/connect/issues/109
