### ISSUE TITLE
Callback in ethereumGetAddress is not invoked after 'Window closed' error

### ISSUE THREAD

**Issue by amirsimhi** [trezor/connect#126]
Hi,
I'm trying to get Trezor address by ethereumGetAddress method. The Trezor browser popup is coming up.
After I'm closing the popup, I'm getting error 'Window closed'. And then after I'm calling again to ethereumGetAddress(path, callback) but this callback isn't invoked.

If I try to call again to this method I'm getting Error: Already waiting for a response.

Any help please?

**Comment by amirsimhi** [comment]
I tried to run TrezorConnect.close() after the 'Window closed' error, but the callback is still not invoked anymore

**Comment by szymonlesisz** [comment]
Hi @amirsimhi,

Try it with new version 5:
https://trezor.github.io/connect-explorer/#/eth-getaddress
