### ISSUE TITLE
About Testnet

### ISSUE THREAD

**Issue by garysen** [trezor/connect#128]
TrezorConnect.setCurrency('Testnet');
error: Invalid coin name
Because current coin_name = 'Decred Testnet'

**Comment by szymonlesisz** [comment]
According to [coins.json](https://connect.trezor.io/4/popup/coins.json) in version 4 the coin_name is still "Testnet", you can try with TrezorConnect.setCurrency('TEST') instead.
However we've released new version recently where coin parameter is used differently.
See our [documentation](https://github.com/trezor/connect/blob/develop/docs/methods.md) and give it a try.
