### ISSUE TITLE
Invalid coin name

### ISSUE THREAD

**Issue by garysen** [trezor/connect#129]
let TrezorConnect = trezor.TrezorConnect;
TrezorConnect.setCurrency('Testnet');
TrezorConnect.getXPubKey('m/44'/1'/0'', function(result) {
      console.log(result);
});
error:
result = {
      error: "Invalid coin name",
      success: false
}

**Comment by szymonlesisz** [comment]
We've released version 5 where this should be fixed.
However if you willing to stay on version 4 try to set "test" instead of "testnet"
