### ISSUE TITLE
Signing paytoaddress transactions example wrong?

### ISSUE THREAD

**Issue by rmn-boiko** [trezor/connect#132]
Iam trying to sign paytoaddress btc transaction via trezor-connect.js api. Due to this example https://github.com/trezor/connect/blob/v4/examples/signtx-paytoaddress.html.
`inputs.push({address_n: [49 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000, 0, 1], prev_hash: 'f3bc1022a05b6687b55d92361457ae7ee2299238a09aa99572e615cf9682ed9c', prev_index: 0})`
`outputs.push({address: 'someAddress', amount: 0.00001, script_type: 'PAYTOADDRESS'})`
`outputs.push({address_n: [49 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000, 0, 0], amount: payBack})`
`trezor.TrezorConnect.setCurrency('btc')`
`trezor.TrezorConnect.signTx(inputs, outputs, this.SendTxTrezorCallback)`
But iam getting an error `Connecting failed: Input amount not set`. When i set amount of input it said to change script type.

**Comment by szymonlesisz** [comment]
hi @SoYouDie,
If you are trying to sign input from segwit account (from 49'/0'/0'...) it needs to have a proper format.
Like  you see in the example:

// segwit input
var inp2 = {
            address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 1, 0],
            amount: 123456789,
            prev_index: 0,
            prev_hash: "20912f98ea3ed849042efed0fdac8cb4fc301961c5988cba56902d8ffb61c337",
            script_type: "SPENDP2SHWITNESS"
   };

So you are missing 2 fields in your input:
- amount: 123456789, (this amount is a input value - not amount you want to spend)
- script_type: "SPENDP2SHWITNESS" (segwit input type)

**Comment by rmn-boiko** [comment]
@szymonlesisz It solve problem of signing but transaction is invalid. Here is signed tx hex `010000000001019ced8296cf15e67295a99aa0389229e27eae571436925db587665ba02210bcf30000000017160014354966a45844090d7152d104326c681ca1075e5effffffff02e8030000000000001976a914e42a54ba2042e889461c7966ac6ba13eeb144a3f88ac306f01000000000017a9148ff360136ee24aa4d5f3ed298947dbc5cfd8ebd58702483045022100881abedbce423c8665911ff7e276216aef1c98713c660e5c7e3a3283d85ca3b202203aae82330c9b229082265249d15853f39859e722446c76083f3f360bc5dbee240121027a8d1c43339ffddeb722b92189412602720f722ed640a08dcbe7e473e71ca11600000000`. But when i try to push i got an error `16: bad-txns-vin-empty. Code:-26`

**Comment by szymonlesisz** [comment]
This is not a trezor error, this one comes from network. You probably mess some values in input/output.
Trezor does not validate if those values are proper.

**Comment by rmn-boiko** [comment]
@szymonlesisz, youre right. I tried to push this tx via other API and it works. Tnx for answer
