### ISSUE TITLE
How to get multiple ETH accounts?

### ISSUE THREAD

**Issue by davidfarina** [trezor/connect#133]
Im struggling to find out how I can get a list of ethereum accounts from the Trezor. I tried finding out how myetherwallet did it but I simply cant get behind it. I tried making multiple calls to ethereumGetAddress but it fails somehow.

Any ideas?

**Comment by szymonlesisz** [comment]
You need to change derivation path for ethereumGetAddress method.

m/44'/60'/0'/0/0 - first account
m/44'/60'/0'/0/1 - second account
m/44'/60'/0'/0/2 - third account

and so on
