### ISSUE TITLE
signEthereumTx value with odd length causes error

### ISSUE THREAD

**Issue by jdetle** [trezor/connect#139]
This error arises when I calculate the value as 
```js
let value = (amount - gas_price * gas_limit).toString(16)
```
If I simply add
```js
if (value.length % 2 !== 0) {
      value = "0".concat([value])
}
```

I get no such error. Seems like this case can easily be handled serverside. Thoughts?

**Comment by prusnak** [comment]
There is no serverside. All code runs on the client, so you are
responsible for providing the correct values.

**Comment by jdetle** [comment]
Okay, I meant serverside in the sense that there is a call over a channel to code I can't find, probably the wrong nomenclature. In no way should a user have to be responsible for knowing that all strings have to have length divisible by two. I propose that it is either documented, or that the code prepends a "0" to strings of odd length.

**Comment by prusnak** [comment]
I agree this should be documented, but I would not do any automagic to user provided values.

**Comment by jdetle** [comment]
After talking with some of my more senior coworkers I think I understand your hesitation. At coincart.co we enforce people using ICOs to use to trezor for their address management, but have been running into some pretty unique issues. Do you think we could talk in a more formal setting about your product? We are all really big fans of the work you are doing.

**Comment by prusnak** [comment]
Github issues are perfect for discussing technical stuff. If you have non-technical inquiry, I can point you to our sales team.

**Comment by jdetle** [comment]
You're absolutely right. Your time is valuable and these conversations should be open to all. I'll try to open some more issues.

**Comment by jdetle** [comment]
My apologies if I came off as rude in this issue, sometimes its hard to take the time to write a well composed issue during the middle of the workday.

**Comment by prusnak** [comment]
No worries.
