### ISSUE TITLE
xpub does not look right

### ISSUE THREAD

**Issue by jimmythrowaway** [trezor/connect#145]
My Trezor now has BIP49-style xpubs, supposedly. From what I understand, that should start with 'ypub', not 'SKRw'. I'm not aware of any standard that uses those starting letters and could not find anything in the BIP49 standard to corroborate this. I use the xpubs generated for some other stuff, can someone please fix this or tell me where I can find documentation for xpubs that start with 'SKRw'?

**Comment by prusnak** [comment]
This seems like a bug. Can you explain how you generate the xpub?

**Comment by karelbilek** [comment]
hello, this is indeed a bug on webwallet, we mistakenly parse the xpub magic as hexadecimal twice. We are now fixing this. Sorry!

**Comment by prusnak** [comment]
Fixed
