### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by jdetle** [trezor/connect#148]
Hi,
I'm getting an error with trezor connect when attempting to transfer ethereum. 
```javascript
var to = stripHexPrefix(this.state.home)
    gas_price_response = await gas_price_response.json()
    var gas_price_hex = gas_price_response.result
    var gas_price = new BigNumber(gas_price_hex, 16).multipliedBy(20)
    gas_price_hex = this.evenify(stripHexPrefix(gas_price.toString(16)))
    var gas_limit = new BigNumber(21000)
    var gas_limit_hex = this.evenify(gas_limit.toString(16))
    var totalGasAmount = gas_price.multipliedBy(gas_limit)
    var value = amount.minus(totalGasAmount)
    value = this.evenify(value.toString(16))
    var data = null // for no data
    var chain_id = 1 // 1 for ETH, 61 for ETC
    var rawTx
    window.TrezorConnect.signEthereumTx(
      address_n,
      nonce,
      gas_price_hex,
      gas_limit_hex,
      to,
      value,
      data,
      chain_id,
      async response => {
		if (response.error) {
			console.log(response.error)
		}
	  }
}
```

considering that I'm deriving value from the gas_price and the amount, and I'm using BigNumber for precision, I'm baffled as to how this error is getting thrown. Any help would be appreciated.

**Comment by jdetle** [comment]
This is a situation in which the funds available to the account exceed the gas price * gas limit

**Comment by jdetle** [comment]
This isn't a trezor issue, my bad.

**Comment by lutsifer** [comment]
Hello,
Can you point me out how to look for solution on this problem? I am using MyEtherWallet with Atheios coin. When I use a non-trezor account funds got send right away, however when I use my trezor account I get same error.  Not sure what to do anymore...

**Comment by lutsifer** [comment]
I am having hard times to believe this is not a trezor problem..

**Comment by prusnak** [comment]
Try firmware from master.

**Comment by lutsifer** [comment]
@prusnak I am new - one week Trezor Model T user.  Do you have steps somewhere described how this can be done?

**Comment by prusnak** [comment]
@lutsifer instructions are here: https://github.com/trezor/trezor-core/blob/master/docs/build.md#build-instructions-for-embedded-arm-port

Be careful, this will erase the coins stored on your device.

**Comment by lutsifer** [comment]
I am confused. If I use same recovery seed after the firmware update I will pop into brand new blank wallets?

**Comment by prusnak** [comment]
No, it will just remove the seed and you would need to do the recovery, which will lead to the same wallets.

**Comment by lutsifer** [comment]
GREAT! I am confirming I was able to send funds successfully using the new firmware!
BTW trezor is not showing the full address when asking to confirm transaction from MEW, but this is not so scary :) THANK YOU SO MUCH @prusnak

**Comment by lutsifer** [comment]
Ah yes - and this red DO NOT USE on startup is so annoying :)

**Comment by prusnak** [comment]
> BTW trezor is not showing the full address when asking to confirm transaction from MEW

Please file a new report ideally with screenshot and describe how would you like it to look like.

> Ah yes - and this red DO NOT USE on startup is so annoying :)

This is intentional, it's a developers firmware, anyway.

Thanks for the report.

**Comment by jdetle** [comment]
Hey @lutsifer, its almost always an issue with an incorrect data conversion when generating a signed transaction. You have to have a very solid understanding of the types you are working with. I recommend thoroughly typing your code and making sure every key in an object has the type that you assume it should have.

**Comment by lutsifer** [comment]
@jdetle Thank you for your response. It's all good now!
Cheers!
