### ISSUE TITLE
Sign Transaction Implementation 

### ISSUE THREAD

**Issue by itsMikeLowrey** [trezor/connect#151]
I was wondering how the Trezor knows what key to use to sign parsed transactions, since it takes in only transaction info and the coin. Dose it just go through every private key until it finds the correct public key, found in the parsed transaction?

**Comment by tylkomat** [comment]
In my understanding, there is only one private key. The one that is generated according your recovery seed. Only if you use [Passphrase](https://wiki.trezor.io/Passphrase) you will virtually (as the passphrases are not stored) use multiple private keys, but before signing you'll have to enter the respective passphrase.

**Comment by szymonlesisz** [comment]
Thats right, there is one private key which is generated from your seed. Additional words from passphrase can be used to create another private key.

**Comment by itsMikeLowrey** [comment]
Could you tell me what private key is used to sign the transaction? My understanding of bip39 is that each address has its own private key. Are you saying that it uses the bip39 root key to sign the transaction? I am using this generator for key terminology https://iancoleman.io/bip39/ . I thought bip39 also uses many different adresses as discussed here https://www.reddit.com/r/TREZOR/comments/6z8tz3/trezor_private_keys_for_all_coins/.

**Comment by tylkomat** [comment]
If you play with that generator you'll see what happens.
The root key is generated from the seed. Based on different parameters (coin type, account, internal/external) a different (extended) private key and a corresponding public key is generated.

I'm not 100% sure about this part: The wallet address is created in a way that indicates which parameters were used to generate the extended private key such that when signing a transaction the same extended private key for that wallet address can be generated from the root key.

**Comment by szymonlesisz** [comment]
This isn't really the right repository to answer that since TrezorConnect doesn't sign anything or doesn't works with private keys in any way. You are welcome to move this discussion to:

https://github.com/trezor/trezor-core
