### ISSUE TITLE
Return currently installed firmware version

### ISSUE THREAD

**Issue by destrys** [trezor/connect#153]
Looking for getVersion from trezor.js

With the changes to the Ethereum signing algorithm introduced in 1.6.2 by trezor/trezor-mcu@1f470cf
I need to test what firmware version is installed and respond to that. 
Using the requiredFirmware argument is very clunky for this.

**Comment by szymonlesisz** [comment]
Hi @destrys ,
since ethereumSignMessage and ethereumVerifyMessage wasn't compatible with other standards this method should not be used with firmware lower than 1.6.2 and 2.0.7 (for model T). 
Otherwise you will get incompatible results which will not be verified by other wallets.
So for now you need to rely on requiredFirmware argument, but soon, with connect version 5 this will be handled automatically by connect itself

**Comment by destrys** [comment]
Hi @szymonlesisz 
we had already taken that into account and used the old incompatible algorithm in our application. That commit actually makes Trezor Ones running 1.6.2+ incompatible with our existing on-chain contracts.

Besides that, having the ability to query the firmware version would be more useful, looking forward to the new and improved connect 5, I hope it has all the functionality of the current trezor.js

**Comment by szymonlesisz** [comment]
I'm sorry to tell you that but i'm afraid you will need to rewrite your code to be compatible with firmware 1.6.2+/2.0.7+ only. After version 5 will be released we're going to make this firmware required for all ethereum methods. We don't wan't to keep old algorithm accessible because it will lead to inconsistent results

**Comment by destrys** [comment]
I'm aware of that and am actively re-writing our contracts to react to this change.
But that doesn't change that there is ETH locked in contracts that used your old code. 

By putting in this change (and not even putting it in the changelog) you've made it impossible to upgrade to the latest firmware until we've developed new contracts, tested them, and transitioned. A deprecation warning would have been nice.

My request here was asking for the ability to return the currently installed firmware version. Completely separately from the message signing issue, I still think that's a valid request since it exists in trezor.js and I don't see a security reason to not be able to request that through connect.

**Comment by prusnak** [comment]
Currently, we don't plan to add such functionality into Connect.

**Comment by destrys** [comment]
Why wouldn't you allow an application to find what version of firmware the Trezor is running?

**Comment by prusnak** [comment]
I think the app should not care about which version of firmware is running. It should care about whether the version is compatible and this is exactly why there is `requiredFirmware` argument now.

If you present any good use case why you need this, I might reconsider it, but so far I have not seen any.

**Comment by destrys** [comment]
My example above is that there are contracts on-chain that are only compatible with Trezor firmwares 1.6.1 and below. If I could detect the firmware version I could inform the user that their transaction will be unsuccessful.

I know that those contracts should be migrated to contracts that are 1.6.2 compatible, but that doesn't happen instantly and I'm trying to support an open-source contract that was designed specifically for use with Trezors.

Being able to pin an application to a specific firmware would also guard against future breaking changes in the firmware. I could imagine writing an app that restricts users to a specific Trezor firmware so that we could vet the new firmware before users are able to use the app with it.

Luckily, this change won't result in any permanently locked contracts, but I don't know what will happen in the future, and it'd be nice to be able to restrict users from using an application until we've tested it against the new firmware.

**Comment by destrys** [comment]
Checking back in on this.

An alternative to returning the firmware version would be to include a 'maximumFirmware' field for function calls since functionality has changed and I want to be able to stop a user from using part of my app if their firmware is above a given version.

**Comment by prusnak** [comment]
We never change things in non-backwards compatible manner.

Can you post a real example where this would make sense?

**Comment by destrys** [comment]
There was a non-backwards compatible change to the Ethereum signing algorithm introduced in Trezor firmware v1.6.2 by trezor/trezor-mcu@1f470cf

We have an open-source multi-sig Ethereum contract and corresponding dapp that were designed using the old signing algorithm. (https://github.com/unchained-capital/ethereum-multisig).

The dapp has been deploying a version of our contract "signable" by Trezor versions <=1.6.1.  
Trezor versions >=1.6.2 cannot sign such contracts because of non-backwards compatible change above.  We are modifying our code so that Trezor versions >=1.6.2 will work with new instances of our contract, but we are still left in the position of having real users with real funds in existing instances of our contract - these are *only* signable by Trezor versions <=1.6.1.  
To support our users in transferring their ETH from existing to new instances of our contract, we need to detect when a Trezor is version <=1.6.1 vs >=1.6.2.  The current `requireFirmware` API does not let us gracefully do this.
