### ISSUE TITLE
[undocumented] challenge_hidden must be in HEX format

### ISSUE THREAD

**Issue by araspitzu** [trezor/connect#158]
The `challenge_hidden` field of in `TrezorConnect.requestLogin` API needs a string that is multiple of 2 and in HEX encoding, otherwise fails with "Error: Illegal str: Length not a multiple of 2" or "Error: Illegal str: Contains non-hex characters".

**Comment by prusnak** [comment]
Send a pull request to documentation if you want this documented somewhere, thanks

**Comment by araspitzu** [comment]
Sorry i was too quick opening the PR, i later found the docs at https://github.com/trezor/connect/blob/develop/docs/methods/requestLogin.md (and yes it's specified the hex format).
