### ISSUE TITLE
Name clash with "open" function.

### ISSUE THREAD

**Issue by araspitzu** [trezor/connect#159]
I had a weird issue of the connect.js calling another function in my javascript because it was named "open" and from [here](https://github.com/trezor/connect/blob/v4/connect.js#L962) it was being called instead of window.open(). Would it be possible to rename it to something more unique to avoid potential name clashes?

**Comment by szymonlesisz** [comment]
Hi @araspitzu,
We've released a new version of connect which was completely rewritten and you shouldn't have this issue with it.
Give it a try:

https://github.com/trezor/connect/blob/develop/docs/index.md
