### ISSUE TITLE
Getting "Wrong acquire input" Error on Chrome

### ISSUE THREAD

**Issue by tmsrjs** [trezor/connect#16]
Hey guys,
I'm getting "Wrong acquire input" Error with the latest Chrome extension (1.0.11).
Let me know if I can help in any way to diagnose this.

Thanks!

**Comment by runn1ng** [comment]
Sorry, that was a bug. Try to update the extension to 1.0.12, it should be in web store

**Comment by tmsrjs** [comment]
Thanks, @runn1ng !
