### ISSUE TITLE
Exporting master root xpub in Connect v5

### ISSUE THREAD

**Issue by nneuman** [trezor/connect#175]
In Trezor Connect v5, the ability to export the master xpub with `getHDPath` has been removed.

Link to relevant code -> https://github.com/trezor/connect/blob/develop/src/js/utils/pathUtils.js#L15

This is currently keeping our team from upgrading from Connect v4 -> v5 to support the Model T. Is there a different method we should use to export the m/ root in v5, or is it possible to add this functionality back in?

Thanks very much for any advice/help!

**Comment by szymonlesisz** [comment]
Fixed and released as 5.0.29
