### ISSUE TITLE
yarn link behavior confusing

### ISSUE THREAD

**Issue by jdetle** [trezor/connect#182]
The main entrypoint for the package is "main": "dist/trezor-connect.js" but in order to use the npm package from a linked local directory, the main entrypoint must be changed to "main": "npm/lib/index.js", documenting this would be nice for people who are trying to develop locally.

**Comment by szymonlesisz** [comment]
If you build npm module locally using yarn build:npm and link ./npm directory into your project you don't have to change anything. package.json inside ./npm directory has "main" filed set to "lib/index.js".

We are working on detailed documentation for developers where those things will be described

**Comment by jdetle** [comment]
Thanks, I dont know what you're working on and what you aren't, just trying to give useful feedback.
