### ISSUE TITLE
Tor Browser

### ISSUE THREAD

**Issue by seigneur** [trezor/connect#19]
I am using Trezor connect for the site here at: https://www.coincircles.com/

We also host it on tor, and with the tor browser(mozilla) the bridge does not work. It works via mozilla otherwise. 

When going through tor, cloudflare gives me a Google Recaptcha, after which it asks me to install the bridge, which is already installed.

**Comment by prusnak** [comment]
This won't work unless communication with bridge is routed via Tor network and this is slow (we tried it already).
