### ISSUE TITLE
Testing new coin, which is fork of a Bitcoin

### ISSUE THREAD

**Issue by Adman** [trezor/connect#190]
Hello,

I would like to test basic operations of Capricoin, which is a fork of Bitcoin.
We setup blockbook servers on following urls https://blockbook.capricoin.org/ , https://blockbook2.capricoin.org/, https://blockbook3.capricoin.org/, https://blockbook4.capricoin.org/
As a `slip44` constant, I chose random number, which has not been used yet (number 289).

**getAddress**
  * connectV4 - exports address properly
  * connectV5 - throws `"Invalid parameters: Cannot read property 'split' of null"`

**getAccountInfo**
  * connectV4 - throws `"Cannot set property 'blocks' of undefined"`
  * connectV5 - works fine (except the bug that blockbook returns balance 0, https://github.com/trezor/blockbook/issues/37)

**composeTransaction**
  * connectV4 - throws `"Cannot set property 'blocks' of undefined"`
  * connectV5 - popup asks me to select capricoin account, but the button is disabled

**signTransaction**
  * connectV4 - throws `"Cannot set property 'blocks' of undefined"`
  * connectV5 - throws `"Trying to access beyond buffer length"`

I'd be very grateful if someone could explain me what I'm doing wrong, or which parameters in coin definition to look at and adjust. Also, I would like to know if connectV4 is compatible with blockbooks.

Thanks

**Comment by szymonlesisz** [comment]
Hi @Adman,
It will be helpful if you paste your modified coins.json file
Since connect v5 was released we're not going to add new functionality to v4 so you can skip this version and work only with v5

**Comment by Adman** [comment]
@szymonlesisz Here's the capricoin.json file, (I ran `build_coins.py` to generate coins.json)
```json
{
  "coin_name": "Capricoin",
  "coin_shortcut": "CPC",
  "coin_label": "Capricoin",
  "website": "https://capricoin.org",
  "github": "https://github.com/Capricoinofficial/Capricoin",
  "maintainer": "Filip Husak <filip.husak@infinit.sk>",
  "curve_name": "secp256k1",
  "address_type": 28,
  "address_type_p2sh": 35,
  "maxfee_kb": 2000000,
  "minfee_kb": 1000,
  "signed_message_header": "Capricoin Signed Message:\n",
  "hash_genesis_block": "000007abc632537def4bce0806ca008150b19363f887ad0cb5cf582804f8bc3d",
  "xprv_magic": 76066276,
  "xpub_magic": 76067358,
  "xpub_magic_segwit_p2sh": 77429938,
  "xpub_magic_segwit_native": 78792518,
  "bech32_prefix": null,
  "cashaddr_prefix": null,
  "slip44": 289,
  "segwit": false,
  "decred": false,
  "fork_id": null,
  "force_bip143": false,
  "bip115": false,
  "version_group_id": null,
  "default_fee_b": {
    "Low": 1,
    "Economy": 7,
    "Normal": 14,
    "High": 20
  },
  "dust_limit": 546,
  "blocktime_seconds": 60,
  "uri_prefix": "capricoin",
  "address_prefix": "capricoin:",
  "min_address_length": 27,
  "max_address_length": 34,
  "bitcore": [],
  "blockbook": [
    "https://blockbook.capricoin.org",
    "https://blockbook2.capricoin.org",
    "https://blockbook3.capricoin.org",
    "https://blockbook4.capricoin.org"
  ]
}
```

**Comment by szymonlesisz** [comment]
looks like you are missing "support" field in there
i'm quite surprised that it worked at all without it. 
Which build/branch of Connect v5 are you using?

**Comment by szymonlesisz** [comment]
I'm not able to test it without a firmware anyway,

However you can do a debug for yourself with console using breakpoints.
I'm guessing that you are running connect locally so it shouldn't be to hard.

1. getAddress: what line of code throws this error? what field is expected to be a string (split) but is undefined?
3. composeTransaction: probably you have 0 balance on this account, that's why it's disabled
4. signTransaction: again, what line of code is that, how does Buffer object looks like (and what size he expect to be)

Compare debugging results with working coins, such as bitcoin and you will find your solution

**Comment by Adman** [comment]
I pasted coin definition from defs/coins folder, which does not contain support. But I know I needed to add it to support.json.

```json
"support": {
            "connect": true,
            "electrum": null,
            "trezor1": null,
            "trezor2": "2.0.7",
            "webwallet": true
        },
```

I tested both `v5` and `develop` branches of connect V5.

1. getAddress returns object with that response error
```json
{
payload: {error: "Invalid parameters: Cannot read property 'split' of null"}
success: false
}
```

2. I have sent some coins to that account. The balance returned by blockbook is 0, so I'd expect connect to compute it according to transaction history received from blockbook.

3. Again, I don't know which line exactly is that error coming  from, because I get the unsuccessful response
```json
{
payload: {error: "Trying to access beyond buffer length", code: undefined}
success: false
}
```

I'll be very grateful if I could send you some CPC tokens and you test it, because I'm struggling with that for a couple of days.

**Comment by szymonlesisz** [comment]
What parameters you are sending to getAddress and signTransaction method?
paste you code

**Comment by Adman** [comment]
GetAddress
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    </head>

<body>
    <h1>Hello from get address</h1>

    <script src="./trezor-connect.js"></script>
    <script>
        window.__TREZOR_CONNECT_SRC = 'http://localhost:8080/';
        window.TrezorConnect.getAddress({
            path: "m/44'/289'/0'/0/0",
            coin: "cpc",
            showOnTrezor: true,
        }).then(function(res) {
            console.log(res);
        });

    </script>
</body>
</html>
```

SignTransaction
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    </head>

<body>
    <h1>Hello from signing transaction</h1>

    <script src="./trezor-connect.js"></script>
    <script>
        window.__TREZOR_CONNECT_SRC = 'http://localhost:8080/';

        window.TrezorConnect.signTransaction({
            coin: "cpc",
            inputs: [
                {
                    address_n: [2147483692, 2147483937, 2147483648, 0, 0],
                    prev_index: 1,
                    prev_hash: 'db01766994941f6278b5ba884547bcd6a704a99f861f86ebec07ce99eb8274d9'
                }
            ],
            outputs: [
                {
                    address_n: [2147483692, 2147483937, 2147483648, 0, 1],
                    amount: '88050',
                    script_type: 'PAYTOADDRESS'
                },
                {
                    address: 'CcGPp49GCxGVHVPJrUurQFv5QPaxNXDUXs',
                    amount: '10000',
                    script_type: 'PAYTOADDRESS'
                }
            ]         
        }).then(function(res) {
            console.log(res);
        });
    </script>
</body>
</html>
```

**Comment by szymonlesisz** [comment]
after quick debugging. Yours parameters looks legit.
If i add "cpc" coin to coins.json with support field with "trezor1" field set to "1.6.2", this is a bug where i'm expecting to have support on both devices (trezor1 and trezor2). I will fix that in next release.

TrezorConnect.getAddress works as it should, except for that i don't have firmware with CPC support, so i needed to export this address with Bitcoin format. But it works.

TrezorConnect.signTransaction fails inside [bitcoinjs-lib](https://github.com/karel-3d/bitcoinjs-lib/blob/zcash/src/transaction.js#L162); inside loop on line 162, so there is something wrong with transaction hash. i'm not sure what exactly, you need to debug it for yourself

**Comment by Adman** [comment]
@szymonlesisz I'm not missing "support" field, I just copied here the capricoin.json file, which does not contain that field, but after generating coins.json, it's there.

getAddress works now, I just rebuilt connect and recompiled core.

Will try to debug signTransaction. Thanks.

**Comment by Adman** [comment]
@szymonlesisz The problem is that cpc raw transaction in hex probably contains more data and the library cannot parse it. I hardcoded it there, but there is another small problem in connect.
When reaching method `requestTxInfo` it fails that I'm requesting unknown tx.

Prev transaction: https://insight.capricoin.org/tx/e85fa0d41d19fc4e2f077501f9a7401d2dc72c13312443b363fbd9c6098129b7
Prev index: 0

The `index` parameter of this method contains only one item:
`{ 899ca23ed2b8c4f2816c8c94622fcd23672b6aff41d6914b5fdb5f8c590566c0: {....} }`
But the hash that connect accesses the table with looks like this: `e85fa0d41d19fc4e2f077501f9a7401d2dc72c13312443b363fbd9c6098129b7`

**Comment by szymonlesisz** [comment]
This method works fine for multiple coins which are forks or works like a bitcoin.
That brings me the conclusion that it's not small problem of connect but small problem of your coin.
If your transaction hash in not compatible with bitcoinjs library and you need to make some hard-coding inside of it, then you need to figure it out how to fix it and make pull requests in proper repositories.
I can point you to direction to follow what's going on with this transaction hash, it needs to be reversed multiple times back an forth (bitcoinsjs compatibility vs. hd-wallet/bitcore/blockbook compatibility)

Take a closer look at:
https://github.com/trezor/connect/blob/develop/src/js/core/methods/tx/inputs.js
and 
https://github.com/trezor/connect/blob/develop/src/js/core/methods/tx/refTx.js

and search for "reverseBuffer"
