### ISSUE TITLE
How to connect bch tesnet node

### ISSUE THREAD

**Issue by jonathansmirnoff** [trezor/connect#193]
Hi,
I wanted to connect to bch tesnet node but I didn't find the server url (I only have mainet url https://bch-bitcore2.trezor.io/api/). I'll appreciate if someone could give me the information. Thanks!

**Comment by prusnak** [comment]
We don't run BCH Tesnet instance. If you find someone who does, you can
use their server.

**Comment by jonathansmirnoff** [comment]
@prusnak Thanks for your response. I want to know if the BCH node that I have to run it should have particular specification.

**Comment by prusnak** [comment]
You need to run BCH node and this on top of it:

https://github.com/trezor/blockbook
