### ISSUE TITLE
Error: "TrezorConnect not yet initialized." TrezorConnect.getPublicKey/ TrezorConnect.ethereumGetAddress

### ISSUE THREAD

**Issue by mszczech01** [trezor/connect#200]
Hello Everyone,

I am attempting to implement the Trezor Connect API into my web application.

I need to be able list all of the ether addresses on my Trezor device (about 5000) without typing every single hd derivation path. I created a simple "for loop" which changes the hd path in the getPublicKey and the ethereumGetAddress methods.

When I call the method (the first time), I receive a pop-up window to export my publicKey from my trezor. When I click the export button, **the first iteration is completed successfully** while the rest of them fail and throw the error "TrezorConnect not yet initialized". I've been stuck on this for a few hours and would like a push in the right direction. 

### **Here is my code for my implementation:**

```
function sweeping(i)
{
TrezorConnect.getPublicKey({
  bundle:[
    {path: "m/44'/60'/0/"+i+"0'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"1'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"2'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"3'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"4'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"5'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"6'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"7'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"8'", showOnTrezor: false, keepSession: true},
    {path: "m/44'/60'/0/"+i+"9'", showOnTrezor: false, keepSession: true}
  ]
}).then(function(r){
console.log(r);

TrezorConnect.ethereumGetAddress({
  bundle:[
    {path: "m/44'/60'/0/"+i+"0'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"1'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"2'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"3'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"4'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"5'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"6'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"7'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"8'", showOnTrezor: false},
    {path: "m/44'/60'/0/"+i+"9'", showOnTrezor: false}
]
}).then(function(r){
  console.log(r);
});
});
}

function sweep()
{
for(i=0;i<3;i++)
sweeping(i);
}
```
### ** Here are the errors which I am receiving:**

![screen shot 2018-08-23 at 6 45 57 pm](https://user-images.githubusercontent.com/30051604/44555778-d2043900-a704-11e8-9bdc-628d2a13b635.png)

**### Thank you in advance for your recommendations/solutions!**

**Comment by szymonlesisz** [comment]
Hi @mszczech01 ,

Wow, i didn't expect that someone will use it to generate 5000 keys :)
The first solution that comes to my mind it to bundle all keys/addresses and get them in single call.

So you can use your [for] loop to prepare bundles:

```
var xpubBundle = [];
var addressBundle = [];
function prepareBundles(account) {
    // i've fixed path there, it should be m/44'/60'/[account]'/address_type/address_index
    // read more about BIP32 HD derivation path: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
    // (m / purpose' / coin_type' / account' / change / address_index )
    // also you don't have to generate xpubs for every address index, account index is enough

    xpubBundle.push( {path: "m/44'/60'/" + account + "'/0", showOnTrezor: false } );
    for (var index = 0; index < 10; index++) {
      addressBundle.push( {path: "m/44'/60'/"+ account +"'/0/" + index, showOnTrezor: false} );
    }
}
for (var i = 0; i < 3; i++) {
    prepareBundles(i);
}

console.log("PREPARED BUNDLES", xpubBundle, addressBundle);
```

and then call everything at once:
[ EDIT: with progress listener ]
```

function handleXpubProgress(progress) {
    console.log("- XPUB PROGRESS", progress);
}
function handleAddressProgress(progress) {
    console.log("- ADDRESS PROGRESS", progress);
}
TrezorConnect.on('ui-bundle_progress', handleXpubProgress);

TrezorConnect.getPublicKey({
    bundle: xpubBundle,
    keepSession: true, // "keepSession" doesn't belong to bundle, it's a common param
}).then(function(xpubs) {
    // remove first listener
    TrezorConnect.off('ui-bundle_progress', handleXpubProgress);
    // add second listener
    TrezorConnect.on('ui-bundle_progress', handleAddressProgress);

    console.log("XPUBS", xpubs);

    TrezorConnect.ethereumGetAddress({
        bundle: addressBundle,
    }).then(function(addresses) {
        // remove second listener
       TrezorConnect.off('ui-bundle_progress', handleAddressProgress);

        console.log("ADDRESSES", addresses);

    });
});
```

Anyway i'll have a look on this "not initialized" issue, it looks like some bug. Thanks

**Comment by szymonlesisz** [comment]
You may also want to handle progress for each bundle item, i've updated code for you.

**Comment by szymonlesisz** [comment]
I've figured this out, this issue occurs because you are calling TrezorConnect method 3 times without waiting for result of first call:

```
for(i=0;i<3;i++)
    sweeping(i);
}
```
This code is calling TrezorConnect method in few miliseconds interval, but after first call TrezorConnect needs some time to initialize itself (loads resources, connect to TrezorBridge... etc) First call will start initialization and second call right after will fail because TrezorConnect didn't finish initialization process yet.

**Comment by mszczech01** [comment]
@szymonlesisz  Thank you very much for your help! I can't believe I didn't think to generate the bundles first! 

I see that you wrote:
>  // also you don't have to generate xpubs for every address index, account index is enough

Would you recommend that I use the xPub of a singular account and the generate the 5000 addresses under that account? 

### **I also slightly modified your AddressBundle (since I received an error) from:**

>       addressBundle.push( {path: "m/44'/60'/"+ account +"'/0/" + index, showOnTrezor: false} );

### **To:**

>         addressBundle.push( {path: "m/44'/60'/"+ account + "'/" + index + "''", showOnTrezor: false});

Please let me know if this is correct or if I am misunderstanding something.

Thanks again for your help!

**Comment by szymonlesisz** [comment]
No, it's not ok.
I've pasted a proper formula in previous comment
(m / purpose' / coin_type' / account' / change / address_index )

change index and account index **should not** be hardended (with apostrophe)

**Comment by szymonlesisz** [comment]
`Would you recommend that I use the xPub of a singular account and the generate the 5000 addresses under that account?`

I'm sure it will be much faster to generate those addresses from xpub usign HDKey and EthereumUtils
