### ISSUE TITLE
Is the Cardano api supported for the latest firmware?

### ISSUE THREAD

**Issue by bazooka70** [trezor/connect#202]
Calling:
```
TrezorConnect.cardanoGetAddress({
    path: "m/44'/1815'/0'"
})
```

I get an error popup "Firmware is no supported"
(using version 5 with `"https://connect.trezor.io/5/trezor-connect.js"`

**Comment by prusnak** [comment]
No, you need to wait for the next firmware update. Or run the T2 emulator: https://github.com/trezor/trezor-core/blob/master/docs/emulator.md

**Comment by shinsuny** [comment]
@prusnak 
When can we expect the next firmware update for Trezor One?
