### ISSUE TITLE
MultiSig Error: Invalid parameters: Invalid checksum

### ISSUE THREAD

**Issue by jonathansmirnoff** [trezor/connect#203]
Guys,

I want to sign a multisig tx but I kept getting this error "**Invalid parameters:Invalid checksum error**". 
I created the multisig wallet using the publicKey of 2 trezor. We get these keys using the testnet derivation path.
I'm using connect version 5.

Here is the code:

var meriXpub = 'tpubDCSJ3GrB3gss1K2ySF1pFezeSmdWZgjAXJC9i7mSVgh1taeg8XM6U522Tq1Yapd4yTn7BBzUzneZVDCLtyZxt42Js7YpVPqQXkTjKBTiytv';
var joniXpub = 'tpubVobq2bCJxzu1WE48YtmxZN3CFCjEfhZjFsFKWbqvRLaWDgUTdwe9U7QJ1RfBc73a6p34SXVAhZjhj1jwSNxNWKu8KWegN36HNkHWdy9E19p';

// meri path "49'/1'/0'"
// joni path "49'/1'/0'"
//spend a multisig input
var inputs;
if (testId == 1) {
    inputs = [
        {
            address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000],
            prev_index: 0,
            prev_hash: '2a65a02db311164822ce0b3fd5af557fe7da2bb8433c8470ec32634b2a85a412',
            script_type: 'SPENDMULTISIG',
            multisig: {
                pubkeys: [
                    {node: meriXpub, address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]},
                    {node: joniXpub, address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]}
                ],                        
                m: 1
            }
        }
    ];
}         

// send to PAYTOADDRESS output
var outputs = [{
    script_type: 'PAYTOADDRESS',
    amount: '20000000', //0.2 BTC
    address: 'mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG'
}];

var coin = 'test';
TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
     if (response.success) {
         console.log('Serialized TX:', response.serialized_tx); // tx in hex
         console.log('Signatures:', response.signatures); // array of signatures, in hex
     } else {
         console.error('Error:', response.error); // error message
     }
     document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
});     

I'll appreciate your help!

**Comment by prusnak** [comment]
joniXpub is not a valid xpub, because the checksum doesn't match

**Comment by jonathansmirnoff** [comment]
@prusnak thanks you for your quick response. I use https://connect.trezor.io/4/examples/xpubkey.html to get my xpub.
I get this:

Coin:  Testnet  m/49'/1'/0'
{
  "success": true,
  "xpubkey": "tpubVobq2bCJxzu1WE48YtmxZN3CFCjEfhZjFsFKWbqvRLaWDgUTdwe9U7QJ1RfBc73a6p34SXVAhZjhj1jwSNxNWKu8KWegN36HNkHWdy9E19p",
  "chainCode": "e086f0e7df57b2fa1b51638765007fba19d27077ae3af45edc8d320c0b08bc98",
  "publicKey": "0281e8cff2f64f031eb60e148132e316fe881cf3f8e905af3d0f4ae62222db73cc",
  "path": [
    2147483697,
    2147483649,
    2147483648
  ],
  "serializedPath": "49'/1'/0'"
}

To create the multisig a used the method `createmultisig` (https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)

`createmultisig 1 '["0281e8cff2f64f031eb60e148132e316fe881cf3f8e905af3d0f4ae62222db73cc","03cbd0c230086e41842b28c802f29574613e2e4880ce5169f8597b33292f58329d"]'`

**Comment by szymonlesisz** [comment]
Hi @jonathansmirnoff ,
Looks like there is some bug in v4 with testnet xpubs.  "joniXpub" is not valid, when i replaced this by mine it works.
However, since you are trying to sign mulitisig transaction you should use path beginning with 48 instead of 49.
Try to generate those xpubs from v5 and use path m/48'/1'/0': 
https://trezor.github.io/connect-explorer/#/

And also you should change input "address_n" parameter to "48" since you are trying to spend a multisig input

**Comment by jonathansmirnoff** [comment]
@szymonlesisz thanks for your response. I've been trying to test this but currently BTC testnet is not working correctly. A soon as it comes back I'll let you know.

**Comment by jonathansmirnoff** [comment]
After the weekend one of my UTXOs was confirmed. Here is it:
- https://testnet-bitcore1.trezor.io/address/2N1qJLVE2HyVAh4tYDYdWyzfHkeWBGMHhrk
- https://testnet-bitcore2.trezor.io/tx/13f2346895a0dd2592d6927a83f78d298fc58d3664c5291529a972c9bb2ada74

I double check that de network is assigned correctly because I set the coin to `test` and when the trezor signs the tx I see the message "Sign Testnet Transaction". The problem that I have is that trezor returns `Requested unknown tx`:

```
{
  "payload": {
    "error": "Requested unknown tx: 13f2346895a0dd2592d6927a83f78d298fc58d3664c5291529a972c9bb2ada74"
  },
  "id": 2,
  "success": false
}
```

The code that I'm using is:
```
     function trezorSignTx(signIndex) {                
        var meriXpub = 'tpubDCSJ3GrB3gss1K2ySF1pFezeSmdWZgjAXJC9i7mSVgh1taeg8XM6U522Tq1Yapd4yTn7BBzUzneZVDCLtyZxt42Js7YpVPqQXkTjKBTiytv';
        var joniXpub = 'tpubDDfUwLZKVuHm2R4YwVnRvPKL4JeRi1cheEd95j3bZxeJLLs8rynmuoLsD5LN8BGVPauR8hKVni8tJBoanTkGx1wNFGeWcyHW7ocgKU7GS1S';        

        // meri path "49'/1'/0'"
        // joni path "49'/1'/0'"
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {
                    address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000],
                    prev_index: 1,
                    prev_hash: '13f2346895a0dd2592d6927a83f78d298fc58d3664c5291529a972c9bb2ada74',
                    script_type: 'SPENDMULTISIG',
                    amount: '10000000',                    
                    multisig: {
                        pubkeys: [
                            {node: meriXpub, address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]},
                            {node: joniXpub, address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]}
                        ],                        
                        m: 1
                    }
                }
            ];
        } 
        
        // send to PAYTOADDRESS output
        var outputs = [{
            script_type: 'PAYTOADDRESS',
            amount: '9000000', 
            address: 'mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG'
        },
        {
            script_type: 'PAYTOADDRESS',
            amount: '900000',
            address: '2N1qJLVE2HyVAh4tYDYdWyzfHkeWBGMHhrk'
        }
        ];
        
        var coin = 'test';        
        TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
             if (response.success) {
                 console.log('Serialized TX:', response.serialized_tx); // tx in hex
                 console.log('Signatures:', response.signatures); // array of signatures, in hex
             } else {
                 console.error('Error:', response.error); // error message
             }
             document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
        });
     }

```

I used derivation path `49'/1'/0'` instead of `m/48'/1'/0'` because when I tried to generate a testnet address with `m/48'/1'/0'` it returned this error: `"Invalid parameters: Parameters "path" and "coin" do not match."` If I only set the derivation path, it returns mainnet xpub.

**Comment by szymonlesisz** [comment]
```
TrezorConnect.getPublicKey({
  "path": "m/48'/1'/0'",
  "coin": "test"
})
```
is retuning "Invalid parameters: Parameters "path" and "coin" do not match.", are you sure?
I've just tried here:
https://trezor.github.io/connect-explorer/#/
and it worked

"Requested unknown tx" is a bug, i didn't expect that someone will try to spend segwit (49) inputs as 'SPENDMULTISIG', i will fix it in next release.
Meanwhile make sure that you are using above code to generate multisig public keys

**Comment by jonathansmirnoff** [comment]
@szymonlesisz thanks for you response. You're a right, I could generate the address. 
Now I'm waiting because of the issues that are happening in btc testnet. 
I hope I confirm soon that I could do all the stuff that I need.

**Comment by jonathansmirnoff** [comment]
@szymonlesisz finally today one of my UTXOs was confirmed. So I could sign the tx but I have another issue, trezor connect returned this:
```
{
  "payload": {
    "error": "Failed to compile input",
    "code": "Failure_ProcessError"
  },
  "id": 2,
  "success": false
}
```

Something interesting is that when I interact with trezor it shows me the corresponding messages:
- Confirm sending 0.1 TEST to mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG ?
- Confirm sending 0.00101589 TEST to 2N3zgYVaU8vA8vHFg71cG1Ji9iduL6MS5WW?
- Really send 0.00101589 TEST from your wallet? Fee included: 0.009 TEST

The script that I used was the following:
```
<!DOCTYPE html>
<html>
  <head>
    <title>TREZOR Sign Transaction</title>
    <script>       

     function trezorSignTx(signIndex) {                
        var meriXpub = 'tpubDCNFpmM8kZSmfSWtjZ3wTsuAJYvA9K4Zmgov3DvM4ULBE8tjxCJGc2jVzTFCXxkUxtuo7MQaG21bDJ8mL82VnxPayNXTz9zspmJwVBS1Lre';
        var joniXpub = 'tpubDDphoFRUFwhR5KH8ru4TqRSA6Bd21qUsR1XkzE21EgiqhtfrYEqAbeT68sek7o2Manig4WuyHjmC26ivxzvi2wvovVk6WYrQYBbdzHi7uFW';        
        
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {
                    address_n: [48 | 0x80000000, 1 | 0x80000000, 6],
                    prev_index: 172,
                    prev_hash: '6ed71c8234e2c2b822a6f4c1adc4453274d230f8896bf93127f197a420dc6cc3',
                    script_type: 'SPENDMULTISIG',                    
                    amount: '11001589',
                    multisig: {
                        pubkeys: [
                            {node: meriXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6]},
                            {node: joniXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6]}
                        ],                        
                        m: 1
                    }
                }
            ];
        } 
        
        // send to PAYTOADDRESS output
        var outputs = [{
            script_type: 'PAYTOADDRESS',
            amount: '10000000', //0.1 BTC
            address: 'mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG'
        },
        {
            script_type: 'PAYTOADDRESS',
            amount: '101589', 
            address: '2N3zgYVaU8vA8vHFg71cG1Ji9iduL6MS5WW'
        }
        ];
        
        var coin = 'test';        
        TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
             if (response.success) {
                 console.log('Serialized TX:', response.serialized_tx); // tx in hex
                 console.log('Signatures:', response.signatures); // array of signatures, in hex
             } else {
                 console.error('Error:', response.error); // error message
             }
             document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
        });
     }

    </script>
  </head>
  <body>

    <p>Sign the tx:</p>

    <button onclick="trezorSignTx(1)">Sign with key 1</button>    

    <pre id="response"></pre>

    <script src="connectv5.js"></script>

  </body>
</html>

```

**Comment by szymonlesisz** [comment]
your inputs account index are not hardended.
```
inputs = [
                {
                    address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000],
                    multisig: {
                        pubkeys: [
                            {node: meriXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000]},
                            {node: joniXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000]}
                        ],                        
                        m: 1
                    }
                }
];
```

**Comment by jonathansmirnoff** [comment]
Thanks, when I created the address I used this path `m/48'/1'/6`. So I think the account index are ok. Maybe I should use hardended (I didn't know the reason).

**Comment by jonathansmirnoff** [comment]
We recently tested it again with a hardened path I got the same error. We didn't understand what is happening:

```
<!DOCTYPE html>
<html>
  <head>
    <title>TREZOR Sign Transaction</title>
    <script>       

     function trezorSignTx(signIndex) {                
        var meriXpub = 'tpubDCNFpmMH6DyjqcHZfx4wYbySMyiKkRWuebKBiNtkAcz2Tsxp9i6HMzgbfC1P7mLPDAVCLMsW3NEqHTGc2dSPKaYbHjydbdiMgPBYwGdk6Y2';
        var joniXpub = 'tpubDDphoFRcbcEPDM1U91kR4HzHT62ePd9iAvkYaXdXJTzXgG4oPm2E7bKSVFc2ejeXFrPBYzcAuSWsviu4x8YkDAVoxrXcNdHgnihZSpsajFA';        
        
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {                    
                    prev_index: 0,
                    prev_hash: 'b22ae3c916a7cc8813b354efefb405f558482ff54723512daf698860924d106e',
                    address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000],
                    script_type: 'SPENDMULTISIG',                    
                    multisig: {
                        pubkeys: [
                            
                            {node: meriXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000]},
                            {node: joniXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 6 | 0x80000000]}
                        ],                        
                        m: 1
                    }
                }
            ];
        } 
        
        // send to PAYTOADDRESS output
        var outputs = [{
            script_type: 'PAYTOADDRESS',
            amount: '740', //0.1 BTC
            address: 'mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG'
        }
        ];
        
        var coin = 'test';        
        TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
             if (response.success) {
                 console.log('Serialized TX:', response.serialized_tx); // tx in hex
                 console.log('Signatures:', response.signatures); // array of signatures, in hex
             } else {
                 console.error('Error:', response.error); // error message
             }
             document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
        });
     }

    </script>
  </head>
  <body>

    <p>Sign the tx:</p>

    <button onclick="trezorSignTx(1)">Sign with key 1</button>    

    <pre id="response"></pre>

    <script src="connectv5.js"></script>

  </body>
</html>

```

the result:

```
{
  "payload": {
    "error": "Failed to compile input",
    "code": "Failure_ProcessError"
  },
  "id": 1,
  "success": false
}
```

**Comment by prusnak** [comment]
You can't do hardened derivation from xpub. Read BIP32 again.

**Comment by jonathansmirnoff** [comment]
Thanks @prusnak and @szymonlesisz for your help. I read BIP32 and review all the process, but I still have an issue. I'll try to explain with more detail everything.

1. First @herrerameri and I used the this utility https://trezor.github.io/connect-explorer/#/ to get the xpub. I have the Trezor One and @herrerameri has the emulator.
We tried to generate a multisig with this path `48'/1'/0'`

The result is:

```
Joni (Trezor One):
serializedPath:"48'/1'/0'"
childNum:2147483648
xpub:"tpubDDphoFRcbcENx2zN4e8yMwbg4S6uWLc23hcPavehGHUpz7oiXdfm5NP1ECtXK1ybeB6Nr3TobQjnG1dJndspc4eCUVPhsvzKFAecDRYaq75"
chainCode:"0a3067efcb1ab4555d0fa3902d30fb850c9bd5c5493c01f8ebf37141d1a05e97"
publicKey:"031ac71a928d13f6e68153dbfd591d2ff71005bd25643878ce4fa4a3de392fea2b"
fingerprint:4104892669

Meri(Emulator):
serializedPath:"48'/1'/0'"
childNum:2147483648
xpub:"tpubDCNFpmMH6Dyjak8FohiM1qksNi3ZHBK8DbQ5dwTrHoPJr82dHPZdVAaCsyAziCwRo2E6GqdVwoeAoogZobegPHqjSmdY8q4xQH6CwErvjCo"
chainCode:"e2a886d788a895a0d215ff8e5faf804a33d532185493c835c142d017097598e5"
publicKey:"03ddd4e38f68758253621f7be1660f71560072ef3ac9440362b39e72c914e05262

```

2. Then we used bitcoind to generated the multisig wallet by doing this `bitcoin-cli -testnet --rpcuser=user --rpcpassword=password -rpcport=18332 createmultisig 1 '["031ac71a928d13f6e68153dbfd591d2ff71005bd25643878ce4fa4a3de392fea2b", "03ddd4e38f68758253621f7be1660f71560072ef3ac9440362b39e72c914e05262"]' `

The result was:

```
{
  "address": "2MwKDYk8YcjVFNhkinAYZmifeigBT22bm3T",
  "redeemScript": "5121031ac71a928d13f6e68153dbfd591d2ff71005bd25643878ce4fa4a3de392fea2b2103ddd4e38f68758253621f7be1660f71560072ef3ac9440362b39e72c914e0526252ae"
}
```

3. We used some faucet of btc testnet to send some found to this address.
4. After waiting the confirmation for the tx (https://testnet-bitcore1.trezor.io/address/2MwKDYk8YcjVFNhkinAYZmifeigBT22bm3T) we used the following code to try to sign the tx and we have this error: **"Failed to compile input"**

```

function trezorSignTx(signIndex) {                
        var meriXpub = 'tpubDDphoFRcbcENx2zN4e8yMwbg4S6uWLc23hcPavehGHUpz7oiXdfm5NP1ECtXK1ybeB6Nr3TobQjnG1dJndspc4eCUVPhsvzKFAecDRYaq75';
        var joniXpub = 'tpubDCNFpmMH6Dyjak8FohiM1qksNi3ZHBK8DbQ5dwTrHoPJr82dHPZdVAaCsyAziCwRo2E6GqdVwoeAoogZobegPHqjSmdY8q4xQH6CwErvjCo';        
        
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {                    
                    prev_index: 0,
                    prev_hash: '20a0a8147cafd8dab3be833f1d1fd57961b0a7746c99ce47b0ede4fe03a983f9',
                    address_n: [48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000],                    
                    script_type: 'SPENDMULTISIG',                    
                    amount: '7000000',      
                    multisig: {
                        pubkeys: [
                            {node: meriXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]},
                            {node: joniXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000]}
                        ],                        
                        m: 1
                    }
                }
            ];
        } 
        
        // send to PAYTOADDRESS output
        var outputs = [{
            script_type: 'PAYTOADDRESS',
            amount: '70000',
            address: 'mow8mDqiUCf17DxE9uV97SvDvzfYjrBzEG'
        }
        ];
        
        var coin = 'test';        
        TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
             if (response.success) {
                 console.log('Serialized TX:', response.serialized_tx); // tx in hex
                 console.log('Signatures:', response.signatures); // array of signatures, in hex
             } else {
                 console.error('Error:', response.error); // error message
             }
             document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
        });
     }

```

(we are using trezor connect version 5)

the result is 

```
{
  "payload": {
    "error": "Failed to compile input",
    "code": "Failure_ProcessError"
  },
  "id": 1,
  "success": false
}

```

We are thinking that this is maybe something related to this issue https://github.com/trezor/connect/issues/81

Thanks again for your time and help!

**Comment by prusnak** [comment]
multisig.pubkeys should look like this, because path `m/48'/0'/1'` is already "baked in" the xpub itself.

```
pubkeys: [
    {node: meriXpub, address_n: []},
    {node: joniXpub, address_n: []}
],    
```

The best way is to generate xpub like you did, then deriving the pubkey from xpub which you'll use further via public derivation - e.g. `m/0/0`. Then using  `address_n: [0, 0]` in the multisig.pubkeys.

Now you use the xpub node directly, which is OK, but then you cannot have more addresses e.g. for change, etc.

**Comment by szymonlesisz** [comment]
Issue #81 was already fixed in [version4](https://github.com/trezor/connect/pull/100) and it's also implemented on [version5](https://github.com/trezor/connect/blob/develop/src/js/utils/hdnode.js#L104)

**Comment by prusnak** [comment]
Closing this as there is no issue with Connect, but @jonathansmirnoff feel free to ask more info about multisig signing.

**Comment by jonathansmirnoff** [comment]
@prusnak it worked! We are so happy with this! Thanks a lot for your time.
If you go to Buenos Aires, you will be invited to barbecue ;)

**Comment by prusnak** [comment]
Haha, thanks! :D

**Comment by mustafakemal16** [comment]
Hi,
i have one trezor model T and working with trezor-bitcoind 2/3 multisign procees. i m implemented jonathan code but i got 
`
{
"payload": {
      "error": "Firmware error",
      "code": "Failure_FirmwareError"
 },
"id": 1,
"success": false
}`

i use trezor connect v5, here is the code

`
  function trezorSignTx(signIndex) {
             
        var trezorXpub = "tpubDF55ZRpou17aeCTJFUygHdJpLQAxmrEwcN3goqDhT3dvvBEzqQcjA3S9srGiHqxGimvQfNxPn8Wyuyf93gdouHDMfbFAcAnZTAnuB7GNW8d"; // serializedPath:"48/1/0/0"
        var aXpub = "tpubDDnVLNVirx1VVr6s1E5SfMMC8cQdGH1nJ6SBG9xroLZq2fWGU8VYLbcjefEf7iEjX3pgdAx5AjWbqrESciFEqshERGpE4JuMTkJ1HjeKoJQ";    // already derived xpub from m/48/1/0    
        var bXpub = "tpubDDnVLNVirx1VVr6s1E5SfMMC8cQdGH1nJ6SBG9xroLZq2fWGU8VYLbcjefEf7iEjX3pgdAx5AjWbqrESciFEqshERGpE4JuMTkJ1HjeKoJQ";    // already derived xpub from m/48/1/0
       
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {                    
                    prev_index: 1,
                    prev_hash: "50562705e3a7ab79e7a0cbdb82d271f8630c28abbbde8ad21d872f76e4865193",
                    address_n: [],                    
                    script_type: "SPENDMULTISIG",                    
                    amount: "18791282",      
                    multisig: {
                        pubkeys: [
                            {node: trezorXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000]},
                            {node: aXpub, address_n: [ 0 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000]}, // /0/0/0
                            {node: bXpub, address_n: [ 0 | 0x80000000, 0 | 0x80000000, 1 | 0x80000000]}  // /0/0/1
                            /*{node: trezorXpub, address_n: [48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000]},
                            {node: aXpub, address_n: [ 48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000,0 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000]}, // /0/0/0
                            {node: bXpub, address_n: [ 48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000,0 | 0x80000000, 0 | 0x80000000, 1 | 0x80000000]}  // /0/0/1
                            */
                        ],                        
                        m: 2
                    }
                }
            ];
        } 
        
        // send to PAYTOADDRESS output
        var outputs = [{
            script_type: "PAYTOADDRESS",
            amount: "18781282",
            address: "mwvyAB2L6ZUiFPcaS2DqbqinGeNf7Lpcm5"
        }
        ];
        
        var coin = "test";        
        TrezorConnect.signTransaction({inputs, outputs, coin}).then(function (response) {
             if (response.success) {
                 console.log("Serialized TX:", response.serialized_tx); // tx in hex
                 console.log("Signatures:", response.signatures); // array of signatures, in hex
             } else {
                 console.error("Error:", response.error); // error message
             }
             document.getElementById("response").innerHTML = JSON.stringify(response, undefined, 2);
        });
     }`

**Comment by prusnak** [comment]
@mustafakemal16 I wrote above that you should not use hardened derivation in paths inside of xpubs structure, yet you keep adding `| 0x80000000`. Just remove that and use paths without this. Don't put the part of the path, that is already "baked" into the xpub, there.

**Comment by jonathansmirnoff** [comment]
@mustafakemal16 I had the same issue that you had, so you need to review the derivation path, as @prusnak said. Another thing is that you also need to check the order of the public keys that you used to create the multisig, you have to put them in the correct order.

I want to ask another question related to this topic. Suppose that you create a multisig wallet 2-3 and you chose this base path `48'/0'/6'`, so you get the 3 xpub from that path. Then you want to create different address from that path (Receive and Change type for example). So want to have:
- `48'/0'/6'/0/1`
- `48'/0'/6'/0/2`
- `48'/0'/6'/1/0`

Is it correct to use 3 xpub from `48'/0'/6'` (in the correct order) and then derivate these address? Here is an example to try to clarify what I'm asking:
```
aXPub = 'xpub6F...29' //xpub from trezor one using the derivation path 48'/0'/6'/
bXPub = 'xpub6r...48' //xpub from trezor one using the derivation path 48'/0'/6'/
cXPub = 'xpub6s...09' //xpub from trezor one using the derivation path 48'/0'/6'/

.....

multisig: {
                    pubkeys: [
                        {node: aXPub, address_n: [0, 1]}, /0/1
                        {node: bXPub, address_n: [0, 1]}, /0/1
                        {node: cXPub, address_n: [0, 1]}, /0/1
                    ],                        
                    m: 2
                }
```
Thanks!

**Comment by mustafakemal16** [comment]
@jonathansmirnoff i think if you have different seeds its ok.

i change multisig params to as your suggestions 
```
....
address_n: [],
  multisig: {
    pubkeys: [
      {node: trezorXpub, address_n: []},    // "48'/1'/0'"
      {node: aXpub, address_n: [ 0 , 0 , 0]}, //"48'/1'/0'" /0/0/0
      {node: bXpub, address_n: [ 0 , 0, 1]}  //"48'/1'/0'" /0/0/1
    ],
    m: 2
} 
```
firmware error is gone, but we have another one :)

```
{
  "payload": {
    "error": "Pubkey not found in multisig script",
    "code": "Failure_DataError"
  },
  "id": 1,
  "success": false
}
```
same result all derived pubkeys
```
  var trezorXpub = "tpubDF55ZRpou17aeCTJFUygHdJpLQAxmrEwcN3goqDhT3dvvBEzqQcjA3S9srGiHqxGimvQfNxPn8Wyuyf93gdouHDMfbFAcAnZTAnuB7GNW8d"; // serializedPath:"48/1/0/0"
        var aXpub = "tpubDKE7dg3dhMznqyyb5aBZk8QLAesDHSNCtCK6ZpKdV16ASp4XrVYpjNu9fBvBP1vTQTmyFry2ueSwaiLwAuoBmGYh9gW1oL5HwrW6TAw46r1";    // already derived xpub from m/48/1/0/0/0/0    
        var bXpub = "tpubDKE7dg3dhMzntm3WyAEoJBwhewdiZPvd1LxeWXyL4BPw4hJBiK5wDjryPPP5ofD4oxpJySSYcpkH4xpA8VuhPtKY33AAdpEH2f8j5snmKov";    // already derived xpub from m/48/1/0/0/0/1
        
        //spend a multisig input
        var inputs;
        if (signIndex == 1) {
            inputs = [
                {                    
                    prev_index: 1,
                    prev_hash: "50562705e3a7ab79e7a0cbdb82d271f8630c28abbbde8ad21d872f76e4865193",
                    script_type: "SPENDMULTISIG",                    
                    amount: "18791282",      
                    address_n: [],                    
                    multisig: {
                        pubkeys: [
                            {node: trezorXpub, address_n: []},    
                            {node: aXpub, address_n: []}, 
                            {node: bXpub, address_n: []}  
                        ],
                        signatures: ['', '', ''],
                        m: 2
                    }
                }
            ];
        }
```
final input json
```

[{
    "prev_index": 1,
    "prev_hash": "50562705e3a7ab79e7a0cbdb82d271f8630c28abbbde8ad21d872f76e4865193",
    "script_type": "SPENDMULTISIG",
    "amount": "18791282",
    "address_n": [],
    "multisig": {
        "pubkeys": [{
            "node": "tpubDF55ZRpou17aeCTJFUygHdJpLQAxmrEwcN3goqDhT3dvvBEzqQcjA3S9srGiHqxGimvQfNxPn8Wyuyf93gdouHDMfbFAcAnZTAnuB7GNW8d",
            "address_n": []
        }, {
            "node": "tpubDKE7dg3dhMznqyyb5aBZk8QLAesDHSNCtCK6ZpKdV16ASp4XrVYpjNu9fBvBP1vTQTmyFry2ueSwaiLwAuoBmGYh9gW1oL5HwrW6TAw46r1",
            "address_n": []
        }, {
            "node": "tpubDKE7dg3dhMzntm3WyAEoJBwhewdiZPvd1LxeWXyL4BPw4hJBiK5wDjryPPP5ofD4oxpJySSYcpkH4xpA8VuhPtKY33AAdpEH2f8j5snmKov",
            "address_n": []
        }],
        "signatures": ["", "", ""],
        "m": 2
    }
}]
```
output json

```
[{
    "script_type": "PAYTOADDRESS",
    "amount": "18781282",
    "address": "mwvyAB2L6ZUiFPcaS2DqbqinGeNf7Lpcm5"
}]
```

thank you for your help, regards

**Comment by jonathansmirnoff** [comment]
@mustafakemal16 You need to add the corresponding derivation path in `"address_n"`. You have to get the chain values from trezor connect (https://trezor.github.io/connect-explorer/#/) and then put these values in `"address_n": [..,..,.., ]`. This parameter shouldn't be empty.

**Comment by mustafakemal16** [comment]
Thank you @jonathansmirnoff , i put serialized values (48,1,0,0) or (48 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 0 | 0x80000000), its not working, it should be path[] values in  trezor connect (https://trezor.github.io/connect-explorer/#/) get public key result (2147483696, 2147483649, 2147483648,0), 
final input json is

```
[{
    "address_n": [2147483696, 2147483649, 2147483648, 0],
    "prev_index": 1,
    "prev_hash": "50562705e3a7ab79e7a0cbdb82d271f8630c28abbbde8ad21d872f76e4865193",
    "script_type": "SPENDMULTISIG",
    "multisig": {
        "pubkeys": [{
            "node": "tpubDF55ZRpou17aeCTJFUygHdJpLQAxmrEwcN3goqDhT3dvvBEzqQcjA3S9srGiHqxGimvQfNxPn8Wyuyf93gdouHDMfbFAcAnZTAnuB7GNW8d",
            "address_n": []
        }, {
            "node": "tpubDKE7dg3dhMznqyyb5aBZk8QLAesDHSNCtCK6ZpKdV16ASp4XrVYpjNu9fBvBP1vTQTmyFry2ueSwaiLwAuoBmGYh9gW1oL5HwrW6TAw46r1",
            "address_n": []
        }, {
            "node": "tpubDKE7dg3dhMzntm3WyAEoJBwhewdiZPvd1LxeWXyL4BPw4hJBiK5wDjryPPP5ofD4oxpJySSYcpkH4xpA8VuhPtKY33AAdpEH2f8j5snmKov",
            "address_n": []
        }],
        "signatures": ["", "", ""],
        "m": 2
    }
}]
```
and signTransaction result :)
```
{
  "payload": {
    "signatures": [
      "304502210083abd44102972c00675e6b919464ec7042136910d7714db9c8c02ada7aa303a102206dd60bf5365bc82c672728cb583a6fb0760ba7837dd380aaab15a6df37942f79"
    ],
    "serializedTx": "0100000001935186e4762f871dd28adebbab280c63f871d282dbcba0e779aba7e30527565001000000b50048304502210083abd44102972c00675e6b919464ec7042136910d7714db9c8c02ada7aa303a102206dd60bf5365bc82c672728cb583a6fb0760ba7837dd380aaab15a6df37942f79014c69522102191dfe63c0d29c2be3269669242a3e006b054d6119cbc5bfef6f2f40418565a8210265ad8d365819fbdb9f89b5e608df6af58d97018b803acab80f29c572ec5db29921024562aaec7d6a16dbd446e88a9395c8fa3dd030e671320471f798aba9c7d5cf0c53aeffffffff0162941e01000000001976a914b40cb78aef0bd33c8afe8ab97a8011205e69f61388ac00000000"
  },
  "id": 1,
  "success": true
}
```

Regards
