### ISSUE TITLE
secret passphrase can be key logged

### ISSUE THREAD

**Issue by bernardpeh** [trezor/connect#204]
I suggest the secret passphrase to follow the random password numeric popup implemented currently. If using alphabets is hard, it could even be forced numeric again or have certain alphabets representing certain numbers (just like a phone pad) where users need to click randomly rather than typing. This will be much more secure than typing into a text box.

For the secret passphrase feature, there should also be an option to not keep prompting people to type in their phrase (just like the numeric password) which could be annoying

**Comment by prusnak** [comment]
Not gonna happen. Get a Model T where you can enter passphrase on
the device.
