### ISSUE TITLE
Simplified Bitcoin transaction processing

### ISSUE THREAD

**Issue by IcyEagle** [trezor/connect#205]
Hi.

I'm developing an application to receive and send payments on Bitcoin blockchain. In order to secure the private key, I'm going to use Trezor for signing and I want to store a derived public key with its chain code on the server to generate addresses automatically (using derivation).

I inspected Trezor API and found a way to sign Bitcoin transactions. It's necessary to provide txid with the corresponding _vout_ as well as _derivation path_ in order to form an input. I understand how it works but, maybe there is another way how can I manage coins. Actually, I'm talking about the way how Ethereum transactions are being handled (where only _derivation path_ is required to describe "the input").

Technically, it's possible to track the BTC blockchain and associate one or more **utxo/vout** pairs with a single address. I suppose online wallets work exactly like this to hide implementation details from the user under the hood and let him see his overall balance.

My question is: does Trezor has a kind of "wallet" interface where I can just set a _derivation path_ without details about what txids I'd like to use and allow Trezor to solve the question.

Many thanks!

**Comment by szymonlesisz** [comment]
Hi @IcyEagle ,

You can use "[composeTransaction](https://github.com/trezor/connect/blob/develop/docs/methods/composeTransaction.md)" method which will guide user thru the steps:
1. authorization
2. account selection
3. fee selection
4. tx confirmation

And all you have to do is to define outputs
