### ISSUE TITLE
Error: "Invalid identity"

### ISSUE THREAD

**Issue by ghost** [trezor/connect#206]
Hello,

I'm receiving the following response when using the [examples](https://github.com/trezor/connect/blob/gh-pages/examples) locally:

```
{
  "success": false,
  "error": "Invalid identity"
}
```

I've replaced lines   `<script src="../connect.js"></script>` with `<script src="https://connect.trezor.io/4/connect.js"></script>` 

The popup window will appear and any set challenge visual will appear on the Trezor, but confirming the prompt always results in the error.

<img width="603" alt="screen shot 2018-09-02 at 6 28 35 pm" src="https://user-images.githubusercontent.com/2432982/44963307-303bd380-aede-11e8-9c1b-1e60beaa7453.png">

If I return the .html to use `<script src="../connect.js"></script>` the popup will remain indefinitely waiting and no prompt/visual appears on the Trezor

<img width="608" alt="screen shot 2018-09-02 at 6 31 06 pm" src="https://user-images.githubusercontent.com/2432982/44963336-785af600-aede-11e8-8c01-86f781063dfc.png">

If I use http://trezor.github.io/connect/examples/login.html (or any of the hosted examples), the request succeeds.

Not sure what I'm doing wrong.

**Comment by szymonlesisz** [comment]
Hi @tmconnors,
Look like there is some mess with versions, you are trying to use v4 inline script with code(popup) from v1 (look at the popup url)
I will recommend you to use v5 with [requestLogin](https://github.com/trezor/connect/blob/develop/docs/methods/requestLogin.md) method
But if you willing to continue on v4, you can find examples here:
https://connect.trezor.io/4/examples/

**Comment by prusnak** [comment]
Stick to v5, don't use legacy stuff.

**Comment by ghost** [comment]
@szymonlesisz @prusnak Thanks, I was trying v5 earlier with no success. But I realized you switched it to `trezor-connect.js` instead of `connect.js` for v5. I was probably getting a 404 and didn't realize it. I was able to get it working with help from the `connect-explorer`. Thanks.
