### ISSUE TITLE
allow user to configure idle timeout duration for Trezor

### ISSUE THREAD

**Issue by bernardpeh** [trezor/connect#211]
At the moment, I assume the device timed out at 10 mins of inactivity. Perhaps set 10 mins at the default but user should be able to configure it to 5 mins, 2 hr...etc. A paranoid person might want to set it to 5 mins while a heavy user might want to set it to 5 hrs for example.

**Comment by szymonlesisz** [comment]
Hi @bernardpeh ,
TrezorConnect doesn't not set any timeout on device. It's a firmware feature and i'm sure it's there for a good reason :) Pointing to a proper repository:

https://github.com/trezor/trezor-core

**Comment by prusnak** [comment]
There is already a feature for this on Trezor One - install `python-trezor` and see `trezorctl set_auto_lock_delay --help`

**Comment by bernardpeh** [comment]
@prusnak would you consider adding a UI for it in wallet.trezor.io and does it work in Trezor T as well?

**Comment by prusnak** [comment]
It's planned to be added to the UI, but it's low priority. For T it does not work yet.
