### ISSUE TITLE
Deriving Bitcoin addresses from xPub

### ISSUE THREAD

**Issue by mszczech01** [trezor/connect#213]
Hey everyone,

I've been struggling with this all day. I am trying to generate addresses with respect to the first bitcoin account on my trezor wallet. I have tried using several tools to achieve this and none of them are working out for me.

Does anyone have any suggestions on how I can get the addresses associated with my BTC account #1. I need to derive several addresses to receive BTC from several different users and wanted to have their btc go to different addresses.

**Comment by szymonlesisz** [comment]
Hi @mszczech01 ,

There are a couple ways to do that.
Most obvious one will be to do it in [our wallet](https://wallet.trezor.io/). Select your account and go to "receive" tab. Then generate addresses by clicking on "[+ Show next address]" button.

If you wish to generate it from trezor-connect you can use [connect-explorer](https://trezor.github.io/connect-explorer/#/getaddress) and "Get address" method. Just change a "path" parameter to m/49'/0'/0'/0/X where "X" is a address ordinal number
