### ISSUE TITLE
Сase in wallet address.

### ISSUE THREAD

**Issue by GTOsss** [trezor/connect#217]
For ethereumSignTransaction i use:

![image](https://user-images.githubusercontent.com/19191516/45585792-493b8000-b8f3-11e8-9e30-c15ed154909b.png)

But on display of my trezor i can see. 

![image](https://user-images.githubusercontent.com/19191516/45585797-653f2180-b8f3-11e8-9317-36151993b5ab.png)

Does it matter?

**Comment by prusnak** [comment]
It's ok, it's checksum.
