### ISSUE TITLE
Recent Ethereum message signing change breaks existing applications and introduces buggy edge cases

### ISSUE THREAD

**Issue by destrys** [trezor/connect#222]
Trezor Connect `v5.0.32` included changes to `ethereumSignMessage` and `ethereumVerifyMessage` that breaks existing applications and could cause unexpected behavior.

The changes are in `src/js/utils/ethereumUtils.js`:

```
const isHexString = (value: string, length?: number) => {
    if (typeof value !== 'string' || !value.match(/^(0x|0X)?[0-9A-Fa-f]*$/)) {
        return false;
    }
    if (length && value.length !== 2 + 2 * length) { return false; }
    return true;
};

// from (toBuffer) https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js
export const messageToHex = (message: string): string => {
    let buffer: Buffer;
    if (isHexString(message)) {
        let clean = stripHexPrefix(message);
        // pad left even
        if (clean.length % 2 !== 0) { clean = '0' + clean; }
        buffer = Buffer.from(clean, 'hex');
    } else {
        buffer = Buffer.from(message);
    }
    return buffer.toString('hex');
};
```

If a message passed to `ethereumSignMessage` or `ethereumVerifyMessage` satisfies the regex, it is treated as a hex-encoded string instead of an utf-8 encoded string. Previously, all messages were treated as utf-8 encoded strings.

This new behavior breaks existing applications that were using Trezor Connect to sign hex formatted strings.
It additionally introduces edge cases where someone could submit a string to sign that satisfies the regex, e.g. "deed", "dead", etc. which would be unexpectedly converted.

Instead of auto-detecting hex formatting, I suggest introducing an optional 'hex' flag that can be set to true/false that instructs Trezor Connect to convert the given message, and defaults to not converting.

## Examples of current behavior
When signing a standard string, `ethereumSignMessage` behaves as is did previously:
```
     	    TrezorConnect.ethereumSignMessage({
                path: form.find('input.signer-bip32-path').val(),
                message: "hello there!"
            })
```
<img src="https://user-images.githubusercontent.com/1590973/45909507-02e49600-bdb7-11e8-8e15-d044924eebeb.jpg"  width="300px">

But when signing a string that resembles hex, `ethereumSignMessage` automatically converts:
```
     	    TrezorConnect.ethereumSignMessage({
                path: form.find('input.signer-bip32-path').val(),
                message: "deadbeef"
            })
```
<img src="https://user-images.githubusercontent.com/1590973/45909624-b8174e00-bdb7-11e8-99a8-b5271d66cd4a.jpg"  width="300px">

By converting to hex before submitting the message, you can hack around this change:
```
	var message = "deadbeef".split('')
            .map(function(v) {
                return v.charCodeAt(0).toString(16)
            })
            .join('');
     	    TrezorConnect.ethereumSignMessage({
                path: form.find('input.signer-bip32-path').val(),
                message: message // "6465616462656566"
            })
```
<img src="https://user-images.githubusercontent.com/1590973/45909609-9a49e900-bdb7-11e8-9975-57fd11a7cc6d.jpg"  width="300px">

**Comment by szymonlesisz** [comment]
thanks for report and sorry for breaking up,
i've added a new parameter "hex" which determines if conversion should be made.
if not set it will behave like before

**Comment by destrys** [comment]
Fantastic, thank you. When should we expect to see 5.0.33 deployed? Critical priority for us.

**Comment by prusnak** [comment]
5.0.33 deployed

**Comment by szymonlesisz** [comment]
just a notice, you don't have to update anything if you are not using mentioned "hex" parameter
