### ISSUE TITLE
Trezor connect popup 

### ISSUE THREAD

**Issue by s-mohammad-dabir** [trezor/connect#224]
Hey,
When I use a method like "TrezorConnect.getAddress" for the first time, Trezor popup opens in a new tab instead of new windows.

My code is:
```
TrezorConnect.getAddress({
    path: "m/49'/0'/4'/0/0",
    coin: "btc",
    showOnTrezor: false
}).then(function(result) {
console.log(result);
});
```
Where I could find configurations for opening popup?

P.S: I'm using Trezor-connect v5 (Stable branch).

**Comment by prusnak** [comment]
The default is to open a new tab. There is no option to open a new window.

**Comment by i-am-logger** [comment]
> The default is to open a new tab. There is no option to open a new window.

can you point me to the code ?
