### ISSUE TITLE
I can't get my ether wallet address.

### ISSUE THREAD

**Issue by GTOsss** [trezor/connect#225]
I use kovan network for testing transaction with sign trezor. But I can't get my current wallet. In myCrypto I can see my wallet on 'm/44'/1'/0'/0' 
![image](https://user-images.githubusercontent.com/19191516/46348101-807d9100-c656-11e8-89c5-3b7901caa9ec.png)
I use TrezorConnet.ethereumGetAddress with "m/44'/1'/0'/0 " for get my address, than i use web3.eth.getBalance. 

```
let ethAddresses = await TrezorConnect.ethereumGetAddress({
    bundle: Array.from({ length: 5 }).map((el, i) => (
      { path: `m/44'/1'/0'/${i}`, showOnTrezor: false }
    )),
  });
  console.log(ethAddresses);
  ethAddresses = ethAddresses.payload;
  const promiseBalances = ethAddresses
    .map((el) => asyncRequest(web3.eth.getBalance, el.address));
  let balances = await Promise.all(promiseBalances);
  balances = balances.map((el, i) => ({
    address: ethAddresses[i].address,
    balance: web3.fromWei(el.toString(10), 'ether'),
  }));
  console.log(balances);
```

As a result, I get:

![image](https://user-images.githubusercontent.com/19191516/46348412-9dff2a80-c657-11e8-8d37-867f158a5b7a.png)

How can i get my wallet with ether? And which wallet rezor using by default?

**Comment by prusnak** [comment]
You should use `m/44'/1'/0'/0/{i}`. Please reopen if that's not correct.

**Comment by GTOsss** [comment]
@prusnak  I use correct code as here https://stackoverflow.com/questions/1408289/how-can-i-do-string-interpolation-in-javascript

**Comment by prusnak** [comment]
You need to add extra `/0` in the path like I instructed you above. I was not talking about string interpolation, but rather of the fact you are missing an extra element in the path.

**Comment by GTOsss** [comment]
Sorry, I misunderstood you in the last message. I tried on your instructions and was able to get the right wallet. Thank you. But for me the question of how to specify the address I need as a "from" is still relevant.
