### ISSUE TITLE
Connect popup goes away after a few seconds (Iframe timeout) 

### ISSUE THREAD

**Issue by sterlu** [trezor/connect#227]
**This might be limited to minified builds.** I'm using Trezor Connect v5.0.33 with default react-create-app build scripts. Specifically I am calling `trezor.ethereumGetAddress`. Not completely sure what is going on here but:
 - When accessing a served dev build everything works fine
 - When accessing a served production build the window opens, displays "Loading" for a few seconds and then closes with a `Iframe timeout` error. I also get an error as soon as the window opens saying `Failed to execute 'postMessage' on 'Window': Invalid target origin 'undefined' in a call to 'postMessage'.`

I worked around this by including the trezor-connect.js version from CDN instead of importing the NPM module. Not sure what is going on but I figured this might be helpful to someone.

**Comment by mohammadrafigh** [comment]
it seems someone has put some weird characters in .../iframe/builder.js and .../lib/utils/networkUtils.js in npm package. in the package fetched from npm search for `/^.+\:\/\/[^\/]+/` in builder.js you will find two hidden characters at the middle of regex like this: `/^.+\:\/\/[^\\u200c\u200b/]+/` removed those 2 and the problem gone.

**Comment by prusnak** [comment]
We'll publish the fixed version 5.0.34 on Monday.
