### ISSUE TITLE
How to change derivation path for connected Trezor?

### ISSUE THREAD

**Issue by qmn1711** [trezor/connect#228]
I have a radio group of derivation path. Each time I change radio selection, I will get new Ethereum address base on the new selected derivation path. The first time of selection is ok, but the second time will occurs errors.
 - Trezor shows this message: `Another U2F device was used to register in this application trezor`.
 - Console log shows this: 
```
id: "U2F_4"
message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE"
name: "TransportError"
originalError: Error: Sign failed at makeError (... at EventImpl.dispatchToListener (extensions::event_bindings:403:22) at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26) at EventImpl.dispatch_ (extensions::event_bindings:387:35) at EventImpl.dispatch (extensions::event_bindings:409:17) at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26) at dispatchOnMessage (extensions::messaging:392:22)
stack: ...
```

My code:
```
  const result = await TrezorConnect.ethereumGetAddress({
    bundle: Array.from({ length: 5 }).map((el, i) => (
      { path: `${selectedPath}/${i}`, showOnTrezor: false }
    )),
  });
```

I use trezor-connect 5.0.33

**Comment by prusnak** [comment]
There is something broken with Ledger code. It is trying to communicate with Trezor device via the U2F although it's not a Ledger device. Uninstally/remove any Ledger code and it will work.
