### ISSUE TITLE
Uncaught TypeError: TrezorConnect.cardanoGetAddress is not a function

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#233]
Using:
`TrezorConnect.cardanoGetAddress({ path: "m/44'/1815'/0'/0/0" })`
and
`https://connect.trezor.io/5/popup.html`

with both emulator:
`https://github.com/trezor/trezor-mcu`
`https://github.com/trezor/trezor-core`

Getting:
Uncaught TypeError: TrezorConnect.cardanoGetAddress is not a function

![image](https://user-images.githubusercontent.com/19986226/47145903-d3697080-d305-11e8-8340-8fcf4ddc09f0.png)

**Comment by prusnak** [comment]
Have you followed the instructions here? https://github.com/trezor/connect/blob/develop/docs/index.md

**Comment by shinsuny** [comment]
I am using this with some modifications, but original clone is working fine. 
https://github.com/trezor/connect-explorer/tree/webextensions

will try to figure out where did i miss, Thanks !

**Comment by prusnak** [comment]
The branch `webextensions` is an experiment. It contains older version of connect in `vendor/connect.js`. Just replace this file with this one: https://connect.trezor.io/5/trezor-connect.js (which contains the newest changes, including Cardano changes) and it should work. You can also use this to have minified version: https://connect.trezor.io/5/trezor-connect.min.js

**Comment by shinsuny** [comment]
Thanks @prusnak , Its working now.


![image](https://user-images.githubusercontent.com/19986226/47196111-02312680-d39a-11e8-8454-2603d12ff740.png)

this list should also show Cardano ADA?

**Comment by shinsuny** [comment]
getting this for `TrezorConnect.cardanoGetAddress({ path: "m/44'/1815'/0'/0/0" })` :

![image](https://user-images.githubusercontent.com/19986226/47196405-4a047d80-d39b-11e8-837d-ef7fb5dae3e7.png)

**Comment by shinsuny** [comment]
https://github.com/trezor/connect/issues/202
