### ISSUE TITLE
Is there any way to localize UI in other languages? 

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#235]
![image](https://user-images.githubusercontent.com/19986226/47203699-2d2c7200-d3bc-11e8-8efc-1b10f7b552f6.png)

![image](https://user-images.githubusercontent.com/19986226/47204150-93fe5b00-d3bd-11e8-9a61-3f809ee722a6.png)

![image](https://user-images.githubusercontent.com/19986226/47203829-7da3cf80-d3bc-11e8-9b83-3124141b3597.png)

![image](https://user-images.githubusercontent.com/19986226/47203988-0cb0e780-d3bd-11e8-88e3-576719d0a4b8.png)

I will be very happy if there is any option to select / invoke language through API.

**Comment by keraf** [comment]
Adding i18n to connect is definitely considered. Added enhancement tag.

**Comment by tsusanka** [comment]
Thank you for the issue! We will continue tracking this in https://github.com/trezor/trezor-suite/issues/4856.
