### ISSUE TITLE
Bridge asset missing from __tests__/config.json

### ISSUE THREAD

**Issue by iammatis** [trezor/connect#238]
A bridge asset was added in this [commit](https://github.com/trezor/connect/commit/6472e31cd96b9f4649634c35a753284467827aca#diff-d8b99c1ced60551b1e479d6f86bf2d0bR30) to data/config.json, but is missing from [__tests__/config.json](https://github.com/trezor/connect/blob/develop/src/__tests__/config.json#L52). Therefore throwing and exception when running tests. Same goes for karma config, it's missing also [there](https://github.com/trezor/connect/blob/develop/karma.conf.js#L40).

**Comment by szymonlesisz** [comment]
fixed, thanks
