### ISSUE TITLE
Exporting ui/device event messages 

### ISSUE THREAD

**Issue by good-lly** [trezor/connect#242]
Still receiving UI msgs that are not exported.  Specifically "ui-cancel-popup-request" from popup.js and "device-connect" from device.js

![Uploading Screen Shot 2018-10-24 at 1.55.21 PM.png…]()

**Comment by szymonlesisz** [comment]
POPUP.CANCEL_POPUP_REQUEST in not propagated at all for trusted origins:

https://github.com/trezor/connect/blob/develop/src/js/iframe/iframe.js#L128-L130

DEVICE.CONNECT is already exported here:
https://github.com/trezor/connect/blob/develop/src/js/index.js#L437

import { DEVICE } from 'trezor-connect';

if (DECIVE.CONNECT) {
 ...
}
