### ISSUE TITLE
Is there a way to get low level device info like trezorctl get-features

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#243]
trezorctl get-features
Features (101 bytes) {
    device_id: '',
    flags: 1,
    initialized: True,
    label: 'WALLET-NAME',
    language: 'english',
    major_version: 2,
    minor_version: 0,
    model: 'T',
    needs_backup: False,
    passphrase_cached: False,
    passphrase_protection: False,
    patch_version: 8,
    pin_cached: True,
    pin_protection: True,
    revision: 8 bytes b'cdd3b45d',
    unfinished_backup: False,
    vendor: 'trezor.io',
}

**Comment by szymonlesisz** [comment]
Hi @sarveshwar-singh ,

You can use TrezorConnect.getFeatures() method, unfortunately it's not documented yet

**Comment by shinsuny** [comment]
Thanks @szymonlesisz 

It's what i was looking for.
