### ISSUE TITLE
v6 branch webextension is pointing to v5

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#246]
![image](https://user-images.githubusercontent.com/19986226/47648589-cbd78080-dbbd-11e8-95e2-00c6be63fca6.png)

![image](https://user-images.githubusercontent.com/19986226/47648613-e0b41400-dbbd-11e8-987a-699025037873.png)

have plan to update this?

**Comment by szymonlesisz** [comment]
thanks, i'll fix that
