### ISSUE TITLE
Can't sign a transaction with an external input

### ISSUE THREAD

**Issue by RHavar** [trezor/connect#247]
I'm trying to sign a subset of the inputs of a transaction. So in this example:

```
await TrezorConnect.signTransaction({
                    inputs: [
                        { // this is my input, that I want to sign
                           address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 1, 0],
                           prev_hash: "74449493a221a3485acb2272d4f7a85c1c99b742d8fae28177164cb7eb5a30ab",
                           prev_index: 1,
                           script_sig: '1600141b802545177dc62d7ccbc2f29888be4be7a7f133',
                           script_type: 'SPENDP2SHWITNESS',
                           amount: '297699833',
                           sequence: 0
                        },
                        { // do not modify this
                           prev_hash: "862b2fb66579c6bf5f5d47e0642eba67dc7dac0d01788d3aa835d6f9f7825e27",
                           prev_index: 0,
                           script_sig: '160014b03238b14c22310667ce200eacee0124d547900e',
                           script_type: 'EXTERNAL',
                           sequence: 0,
                           amount: '300000'
                        }
                    ],
                    outputs: [
                        { // dest
                            amount: '1534000',
                            script_type: 'PAYTOADDRESS',
                            address: '2NBaDAK4xUAoBmmvWan41MHkHo7Uf11ySQj'
                        },
                        {   // this is my change output
                            address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 1, 1],
                            amount: '296465332',
                            script_type: 'PAYTOP2SHWITNESS'
                        }
                    ],
                    coin: 'TEST',
                    push: false,
                });    
```

I'm trying to only sign the 1st input. So I have set the 2nd input  script type to `EXTERNAL` as I would like trezor to leave it alone. However I get: `{error: "Wrong input script type", code: "Failure_DataError"}`

If I set it to something like `SPENDP2SHWITNESS` it works, but modifies the `script_sig` and thus invalidates the transaction.

**Comment by prusnak** [comment]
Which Trezor firmware are you using?

**Comment by RHavar** [comment]
A Trezor Model T with firmware 2.0.7,  also tried with a Trezor One and got the same result (although that firmware is a year old or so).

You should be able to run the example I gave, even if you have different seeds. And if you change EXTERNAL the signing process will work

**Comment by prusnak** [comment]
I just confirmed that both Trezor One (firmware 1.x.x) and Trezor Model T (firmware 2.x.x) do not support `EXTERNAL` output.

This is not a Connect issue, so I am closing this.

Can you describe what you are trying to achieve?

**Comment by RHavar** [comment]
@prusnak  In the docs it says it does:
https://github.com/trezor/connect/blob/749490dd9bc0edf2d24d958fc1fd56472025e8ba/src/js/types/params.js#L99

I am trying to sign a transaction in which only one of the inputs is mine, and the other input is controlled by an external party (i.e. a coinjoin).   Or more specifically, I'm trying to implement bip79 support for trezor :D

**Comment by prusnak** [comment]
You can send the value to Trezor, but it is not implemented in the firmware at the moment.

If you want to try implementing it, you should add another case when `txi.script_type == InputScriptType.EXTERNAL` here:

https://github.com/trezor/trezor-core/blob/b9926a9fffe8a593beb3adb79e5fc429233e41a3/src/apps/wallet/sign_tx/signing.py#L148

and send a pull request to trezor-core. Running an emulator should be [straightforward](https://github.com/trezor/trezor-core/blob/master/docs/emulator.md).
