### ISSUE TITLE
silent call to TrezorConnect.getFeatures()

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#249]
Is there a way to `TrezorConnect.getFeatures()` without any Popup UI.

May be similar to:
https://github.com/trezor/connect/issues/8
https://github.com/trezor/connect/issues/124

**Comment by szymonlesisz** [comment]
no, for security reasons we don't want you to get any device information without notifying the user about it.
Once the user allow your app to communicate with Trezor you should get this info without popup in the future calls
