### ISSUE TITLE
info request about TrezorConnet.getDeviceState()

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#250]
```
TrezorConnet.getDeviceState()
result : {
 "payload": {
  "state": "64 char hexdecimal string"
 },
 "id": 2,
 "success": true
}
```
what ` "state": "64 char hexdecimal string"` stands for?

**Comment by szymonlesisz** [comment]
It's a advanced feature used by our wallet. Device state is a unique hash generated on device and it's used to keep passphrase session. 
For example if you are using passphrase "a" to access your accounts and you want to make sure that next time, let say after device disconnection, passphrase will still be the same you need to store this hash and on the next call use it like:

```javascript
TrezorConnect.someMethod({`
    device: {
        path: "device-path-gained-from-device-connect-event"
        state: "device-state-gained-from-device-changed-event"
   },
   ...otherParams
});
```

Now if you type invalid passphrase (let say "b") you will be notify about it

**Comment by shinsuny** [comment]
Thanks @szymonlesisz
