### ISSUE TITLE
api to check prerequisite

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#252]
Is there any `TrezorConnet API` to get prerequisites checks like:
1. Trezor Bridge status (running or not, version)   
2. `udev rules` installed or not
3.  other prerequisites if any

**Comment by ddeath** [comment]
Hi,

you can take a look here https://github.com/trezor/connect/blob/develop/docs/events.md where is describe how you can detect some device events.

Also you can look here: https://github.com/trezor/connect/blob/develop/src/js/device/DeviceList.js there is code which is responsible for discovering device lists.

Also you can take a look at low-level lib https://github.com/trezor/trezor-link (connect use it in background)

Maybe one question is why you need this information. If I am not mistaken the devs want to remove trezor-bridge completly and use only webusb or other usb libs... (you can see in DeviceList that trezor-bridge is only one "transport" option)

**Comment by shinsuny** [comment]
Thanks @ddeath !!
Your reply made many things more clear.
For now I am trying to focus on Trezor Model T, from my hit and trail I just found that Trezor Model T does not need Trezor Bridge anymore.

I feel [THIS](https://github.com/trezor/trezor-link) will fulfill my remaining quest.

**Comment by ddeath** [comment]
Just want to point out that if you are using connect, it does not need bridge because it use webusb:
https://caniuse.com/#feat=webusb

**Comment by prusnak** [comment]
@sarveshwar-singh don't use trezor-link directly but use Connect instead. You will run into problems.
