### ISSUE TITLE
Tests not working :(

### ISSUE THREAD

**Issue by karelbilek** [trezor/connect#256]
When I try to run tests, nothing happens

In the Karma window that gets open, I see nothing, and in the console, I see this error

```
http://localhost:8099/base/src/data/bridge/releases.json?r=1541617745719
Failed to load resource: the server responded with a status of 404 (Not Found)
networkUtils.js:18 Uncaught (in promise) Error: httpRequest error: base/src/data/bridge/releases.json?r=1541617745719 Not Found
    at _callee$ (networkUtils.js:18)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(:8099/anonymous function) [as next] (http://localhost:8099/base/src/__tests__/core/core.test.js:2930:21)
    at step (asyncToGenerator.js:17)
    at asyncToGenerator.js:28
```

The URL indeed does not exist. I do have git submodules checked out, including releases.json in src/data.

**Comment by karelbilek** [comment]
Interestingly, http://localhost:8099/base/src/data/coins.json?r=1541618407307 seems to load fine, but not releases.json

**Comment by karelbilek** [comment]
...oh, because it is missing in karma settings

**Comment by karelbilek** [comment]
Hm, now I got further - no releases.json fail, but the tests just hangs forever with `- Running /correct ...` :(

**Comment by keraf** [comment]
Tests are working now, closing issue.
