### ISSUE TITLE
Failed to execute 'postMessage' on 'Window' when calling stellarSignTransaction()

### ISSUE THREAD

**Issue by istrau2** [trezor/connect#258]
code:
```
async sign() {
        const account = this.store.getState().myAccount;
        const bip32Path = this.store.getState().bip32Path;

        if (!account) {
            this.errorMessage = 'Hey, you aren\'t logged in. You can\'t create a transaction without being logged in first silly. Please login and try again.';
            return;
        }

        const transaction = this.transactionsGenerator.multiOperationTransaction(this.operations, account.accountId, account.seqNum, this.memo);

        try {
            const signedTransaction = await TrezorConnect.stellarSignTransaction({
                path: 'm/' + bip32Path,
                networkPassphrase: window.stellarport.networkMode === 'public' ? 'Public Global Stellar Network ; September 2015' : 'Test SDF Network ; September 2015',
                transaction
            });

            this.signed({
                signedResult: signedTransaction
            });
        }
        catch (e) {
            this.errorMessage = e.message || e;
        }
    }
```
the failure is returned by `stellarSignTransaction` and stored in signedTransaction.

error/stack:
```
"Error: Failed to execute 'postMessage' on 'Window': function read(io) {
    return undefined;
  } could not be cloned.
    at Object.postMessage (webpack:///./node_modules/trezor-connect/lib/iframe/builder.js?:202:32)
    at _callee2$ (webpack:///./node_modules/trezor-connect/lib/index.js?:309:39)
    at tryCatch (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:62:40)
    at Generator.invoke [as _invoke] (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:114:21)
    at step (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:17:30)
    at eval (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:35:14)
    at new Promise (webpack:///./node_modules/core-js/modules/es6.promise.js?:164:7)
    at new F (webpack:///./node_modules/core-js/library/modules/_export.js?:35:28)
    at eval (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:14:12)
    at call (webpack:///./node_modules/trezor-connect/lib/index.js?:350:22)
    at _callee38$ (webpack:///./node_modules/trezor-connect/lib/index.js?:1343:32)
    at tryCatch (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:62:40)
    at Generator.invoke [as _invoke] (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/trezor-connect/node_modules/regenerator-runtime/runtime.js?:114:21)
    at step (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:17:30)
    at eval (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:35:14)
    at new Promise (webpack:///./node_modules/core-js/modules/es6.promise.js?:164:7)
    at new F (webpack:///./node_modules/core-js/library/modules/_export.js?:35:28)
    at Function.eval (webpack:///./node_modules/trezor-connect/node_modules/babel-runtime/helpers/asyncToGenerator.js?:14:12)
    at Function.eval [as stellarSignTransaction] (webpack:///./node_modules/trezor-connect/lib/index.js?:1357:23)
    at SignWithTrezorCustomElement._callee$ (webpack:///./src/app/resources/stellar/transaction-service/sign-transaction-modal/sign-with-trezor/sign-with-trezor.js?:106:91)"
```

**Comment by szymonlesisz** [comment]
looks like your "transaction" object gained from "transactionsGenerator" contains some unexpected non cloneable fields (like functions)
could you paste this object here?

**Comment by istrau2** [comment]
@szymonlesisz Ah, I see. It is the output of this function: https://stellar.github.io/js-stellar-sdk/TransactionBuilder.html#build
I guess I have to convert that into a JSON representation. Thanks.

**Comment by istrau2** [comment]
@szymonlesisz Are there any plans to release a version that allows passing `Transaction` generated from the official javascript stellar-sdk? Or, is there any recommendation (or ideally code) on how to convert `Transaction` to the JSON representation required by this library.

Frankly speaking, in its current state, I can't see this library being adopted by very many Stellar projects as everyone is using the official javascript stellar-sdk library.

For example us, at Stellarport, we have a signing service that we are trying to plug this library into. However, the signing service accepts `Transaction`s that are produced by the sdk. I don't know how we are going to convert those to this custom JSON representation.

**Comment by szymonlesisz** [comment]
I'm pretty sure that it is compatible with stellar-sdk. As you can see here: https://github.com/trezor/connect/blob/develop/src/js/types/stellar.js we are using the same fields and types as stellar-sdk.
That's why i was asking you to show this object you are trying to send to stellarSingTransaction method

**Comment by istrau2** [comment]
@szymonlesisz Its this object: https://stellar.github.io/js-stellar-sdk/Transaction.html

No, it is not compatible because the stellar-sdk's objects have non cloneable fields (which is what caused this issue in the first place) and no way to go to a simple json representation that I can see (aside from my writing a custom XDR parser).

To be clear, I know others are having this same issue (i.e. having trouble integrating with this library because of the stellar-sdk incompatibility)

**Comment by szymonlesisz** [comment]
I was asked to use those types while implementing [stellar support](https://github.com/trezor/connect/issues/127#issuecomment-399925204) i didn't figure it out by myself.
This is an open repository and we will welcome your pull request to fix this to fulfil your needs

**Comment by istrau2** [comment]
@szymonlesisz Ok, I just spent a solid hour trying to map the stellar-sdk Transaction to yours and can say that it is definitely not compatible. You should give it a try... I doubt that anyone will implement this library as is (other than a project that is willing to assemble the json manually).

**Comment by szymonlesisz** [comment]
Did you read my response above and visited a link with discussion about stellar support?
It's not "mine" variation of params, i didn't set it this way just because i can to make your or anyone else life harder.
In this discussion i asked several times how this params should look like to make it compatible with stellar api and then i set it in format they asked me to. After implementation i was told that everything is fine and working.

**Comment by istrau2** [comment]
@szymonlesisz Yes, I saw the link. I don't think this is your fault at all. I think there is some amount of miscommunication here (including mine).

I think the best way forward here is if just to show you what I tried:

```
//note at this point transaction is the return value of this function: https://stellar.github.io/js-stellar-sdk/TransactionBuilder.html#build
// which is a Transaction type with many noncloneable members such as functions
const jsonTransaction = sdkToTrezorTx(transaction);

const result = await TrezorConnect.stellarSignTransaction({
      path: 'm/' + bip32Path, //"44'/148'/2'"
      networkPassphrase: window.stellarport.networkMode === 'public' ? 'Public Global Stellar Network ; September 2015' : 'Test SDF Network ; September 2015',
       transaction: jsonTransaction
});
// result.success = false
// result.payload.error = "Firmware Error"

// This is my attempt at mapping the two transactions
function sdkToTrezorTx(sdkTx) {
     //once we map Transaction to json, memo disappears since it is a getter.
     const memo = sdkTx.memo;
     // Get rid of non cloneable members
     const result = JSON.parse(JSON.stringify(sdkTx));
        
     // Try and comply with trezor Transaction type
     delete result._memo;
     delete result.tx;
     delete result.signatures;
     result.memo = memo;

     return result;
}
```

Bascially, the StellarSdk Transaction is not the same as the Trezor Transaction. Also, some fields are not the same types. For example, Transaction.sequence is not a number, it is a string.

All that aside, I really just want to pass the ouput of `TransactionBuilder.build()` to `stellarSignTransaction`. It doesn't seem right that I should have to implement a custom mapper. I think these errors would become evident to you if you tested this on a Trezor emulator (that is what I am testing on).

**Comment by szymonlesisz** [comment]
There is no possibility to pass a complex object to TrezorConnect. 
It is not technically possible to send function-like object via "postMessage", which is the way your app communicate with injected iframe, and even if it would be possible we don't wont to run third party code inside our iframe for security reasons. That's why JSON is the only accepted format.

But since you mentioned that trezor Transaction object differs from the one you are trying to send i'm referencing once again to [this post](https://github.com/trezor/connect/issues/127#issuecomment-399925204) in discussion during implementation.

> (...)
> Building new transactions in stellar-sdk happens in **js-stellar-base** library
> Here's transaction object
> https://github.com/stellar/js-stellar-base/blob/master/src/transaction.js


And this is the exact object that TrezorConnect is expecting.

Did you try that?

**Comment by istrau2** [comment]
@szymonlesisz That exact object has function properties... Yes, I tried that exact object, it threw me the error that started this thread. 

I am not suggesting that you pass a complex object to the iframe. I am suggesting that you accept a complex object to the signing method. Then, you can implement whatever mapping logic you want to map it to a json representation and pass that to the iframe. That way, you don't pass the responsibility of  mapping the objects to the consumer of the library (like me), who might find it quite difficult (not to mention the difficulties of version control).

**Comment by szymonlesisz** [comment]
Sorry, we are not going to take the responsibility for maintenance third party libraries versions in our code.

Take a look at [AccountViewer](https://github.com/stellar/account-viewer/blob/e02bcdcce0e7890182a8ba0ac2833ea6b60a7ae9/controllers/send-widget.controller.es6#L460-L477) project, how they implement it.

**Comment by istrau2** [comment]
@szymonlesisz They have a very simple use case. Just sending payments. I have stellarport.io a fully functional DEX, I can't construct json objects manually.

I am not sure why you don't want to accept a Transaction object of the kind that StellarSdk produces. That does not mean that you have to maintain the StellarSdk. I mean, if the StellarSdk changes, you are going to have to make changes in you JSON representation anyway. It just comes down to having a mapping implementation in your library (so that developers don't have to create their own).

**Comment by szymonlesisz** [comment]
There are a couple of reasons for that.

1. Since we agreed on that i'm not going to send this object to the iframe i would need to parse and validate those values inside trezor-connect npm package which is a lightweight (~170KB) interface with only few essential methods just to create a communication channel between app, iframe and popup. It passes JSON params as they are, without any validation. This kind of validation simply does not belongs there. We don't want to put some coin logic in there.

2. Connect does not care about stellar or any other sdk and their versions. We don't need to change a thing if they change. Our changes relies ONLY on Trezor firmware and corresponding protobuf messages. And they are changing rarely.

**Comment by istrau2** [comment]
@szymonlesisz How would suggest that I proceed? Given that I have an arbitrary StellarSdk Transaction object, how do I use trezor connect? Is it possible? Perhaps another addon library is in order?

**Comment by szymonlesisz** [comment]
i don't think there is any lib for that.
If was you i would create my own library which will translate StellarSDK Transaction object into JSON format and share it with other people who experience the same problem. Eventually i would requests proposed changes via pull request in TrezorConnect repository

**Comment by istrau2** [comment]
@szymonlesisz I've been working on developing a mapping function. I have mapped a payment operation to the following JSON:

```
{
  "source": "GDNAQREX5VOHMYZ2QDHDY6A7XR2OYIE67EETL5MFCT6TCGHYA7YHACEW",
  "fee": 100,
  "sequence": "89703140756029441",
  "operations": [
    {
      "type": "payment",
      "destination": "GAXLG447OP53S2PHUY4MWYQ3RRE2MLI2Z2WNI6X2IQCAJQMVCXMQVLGM",
      "asset": {
        "code": "XLM"
      },
      "amount": 10000000
    }
  ],
  "memo": {
    "type": 1,
    "text": "abc"
  }
}
```

I am getting a response of form:
```
{
   success: false,
   payload: {
       error: "Firmware Error"
   }
}
```

Any thoughts on why that would be happening?

**Comment by szymonlesisz** [comment]
are you running emulator? or real device? if so which model and firmware?

**Comment by istrau2** [comment]
@szymonlesisz I am running against the emulator.

**Comment by prusnak** [comment]
@istrau2 run `PYOPT=0 make emu` to start the emulator, then look into debug output when Firmware error is printed out and paste the debug output here

**Comment by istrau2** [comment]
@prusnak Thanks. Is this what you are looking for:
```
1542211803617400 trezor.wire ERROR exception:
Traceback (most recent call last):
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 128, in session_handler
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 125, in session_handler
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 163, in protobuf_workflow
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 150, in protobuf_workflow
  File "/home/ishai/trezor-core/src/apps/stellar/sign_tx.py", line 26, in sign_tx
  File "/home/ishai/trezor-core/src/apps/stellar/sign_tx.py", line 75, in _operations
  File "/home/ishai/trezor-core/src/apps/stellar/operations/__init__.py", line 38, in process_operation
  File "/home/ishai/trezor-core/src/apps/stellar/operations/layout.py", line 157, in confirm_payment_op
  File "/home/ishai/trezor-core/src/apps/stellar/operations/layout.py", line 249, in confirm_asset_issuer
  File "/home/ishai/trezor-core/src/trezor/utils.py", line 46, in chunks
TypeError: object of type 'NoneType' has no len()
```

**Comment by istrau2** [comment]
Oh, I see. Is the issue that XLM has no issuer? Should I just leave the asset out?

**Comment by prusnak** [comment]
Try if that works

**Comment by istrau2** [comment]
@prusnak @szymonlesisz Ok, so removing the asset works. Is the rule that if native XLM is used then there is no asset included, otherwise include the asset?

**Comment by prusnak** [comment]
Yes, it seems that is the behaviour

**Comment by istrau2** [comment]
@prusnak @szymonlesisz Ok, what about this transaction:
```
{
  "source": "GDNAQREX5VOHMYZ2QDHDY6A7XR2OYIE67EETL5MFCT6TCGHYA7YHACEW",
  "fee": 100,
  "sequence": "89703140756029442",
  "operations": [
    {
      "type": "changeTrust",
      "line": {
        "code": "XRP",
        "issuer": "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5"
      },
      "limit": "922337203685.4775"
    }
  ],
  "memo": {
    "type": 0
  }
}
```

which produces the following error in the emulator:
```
1542214084817817 trezor.wire ERROR exception:
Traceback (most recent call last):
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 128, in session_handler
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 125, in session_handler
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 163, in protobuf_workflow
  File "/home/ishai/trezor-core/src/trezor/wire/__init__.py", line 150, in protobuf_workflow
  File "/home/ishai/trezor-core/src/apps/stellar/sign_tx.py", line 26, in sign_tx
  File "/home/ishai/trezor-core/src/apps/stellar/sign_tx.py", line 75, in _operations
  File "/home/ishai/trezor-core/src/apps/stellar/operations/__init__.py", line 21, in process_operation
  File "/home/ishai/trezor-core/src/apps/stellar/operations/serialize.py", line 36, in write_change_trust_op
  File "/home/ishai/trezor-core/src/apps/stellar/operations/serialize.py", line 164, in _write_asset
  File "/home/ishai/trezor-core/src/apps/common/writers.py", line 37, in write_uint32_be
TypeError: unsupported types for __le__: 'int', 'NoneType'
```

**Comment by istrau2** [comment]
Is it the memo? I tried removing it when there is no memo and get the same error (only earlier in the process).

**Comment by istrau2** [comment]
Here is a setOptions operation:
```
{
  "source": "GDNAQREX5VOHMYZ2QDHDY6A7XR2OYIE67EETL5MFCT6TCGHYA7YHACEW",
  "fee": 100,
  "sequence": "89703140756029442",
  "operations": [
    {
      "type": "setOptions",
      "inflationDest": "GCCD6AJOYZCUAQLX32ZJF2MKFFAUJ53PVCFQI3RHWKL3V47QYE2BNAUT"
    }
  ],
  "memo": {
    "type": 0
  }
}
```

It fails before even getting to the firmware (I assume in the trezor-connect js code). It returns:
```
{
  id: 2,
  payload: {
    code: undefined,
    error: "Cannot read property 'type' of undefined"
  },
  success: false
}
```

**Comment by prusnak** [comment]
@istrau2 please open an issue in https://github.com/trezor/trezor-core repo if there is an exception in the emulator - this report really does not belong here

**Comment by istrau2** [comment]
@prusnak Ok, will do. However, the last error I got probably does belong here. It is being generated by the javascript, not the firmware. You want me to include the last one in the new issue in trezor-core or leave it here?

**Comment by reqlez** [comment]
Is this related to the issue I'm having with the new Trezor Account Viewer ??? https://github.com/trezor/stellar-account-viewer/issues/2

**Comment by istrau2** [comment]
@reqlez This issue is closed and moved here: https://github.com/trezor/trezor-core/issues/421
