### ISSUE TITLE
Allow closing Trezor tab from JavaScript

### ISSUE THREAD

**Issue by federicobond** [trezor/connect#259]
When the user cancels a certain flow from their mobile device, we would like those changes to be reflected in the computer by automatically aborting and closing the Trezor tab.

Is there some way to do that with the current lib?

**Comment by szymonlesisz** [comment]
There is no such method for now, but it shouldn't be a problem to implement it.
You would like to call something like:

TrezorConnect.close();

to interrupt currently running request, did i understand correctly? Because i'm not sure what you mean by this "mobile cancellation" part

**Comment by federicobond** [comment]
Yes, you understood correctly.

**Comment by szymonlesisz** [comment]
I've added TrezorConnect.cancel(); method which will interrupt currently running process and close the popup.
Will be released as 6.0.3 soon

**Comment by federicobond** [comment]
Awesome, thanks!
