### ISSUE TITLE
Send script_type in GetPublicKey

### ISSUE THREAD

**Issue by tsusanka** [trezor/connect#261]
Discussed with @szymonlesisz. Connect now does not send GetPublicKey with `script_type` field, which obviously rules out script type validation (https://github.com/trezor/trezor-core/issues/345).

Consider doing with the coin_name fix described https://github.com/trezor/trezor.js/issues/73 (if applicable).

**Comment by prusnak** [comment]
Actually, this needs to be fixed together with https://github.com/trezor/trezor.js/issues/73 in order to fulfill the goal of simplifying the code on the fronted.
