### ISSUE TITLE
Sign BIP49 SegWit Multisig transaction，return “Invalid network version”

### ISSUE THREAD

**Issue by Ark-Chen** [trezor/connect#262]
When i want to sign BIP49 SegWit Multisig transaction, trezor return “Invalid network version”。

The same method, when i sign BIP44 Multisig transaction, it succeeded。

I want to konw why。Looking forward to your reply

**Comment by prusnak** [comment]
Show us your code, both working and non-working

**Comment by Ark-Chen** [comment]
```input : {
                address: "38GnfUJ1qu5nuiMQDX8scRCf2YLZZ9AKEq",//多签时为多签地址
                paths: [
                    {
                        addressType: "SPENDWITNESS",//SPENDADDRESS  SPENDWITNESS
                        path: "m/49'/1'/0'/0/0", //多签时为每次签名的path
                        xpub: "ypub6XoGXBU3Cn6YT6GjagKjfixiSqXQHbpWLghWd9hBFAxEYh71wTDj3ogGwY2vN3qVRpzz82TRCgDyajbTf3yt2rMzmtKnAzRh6X1KW9QRsPA"
                    },
                    {
                        addressType: "SPENDWITNESS",//SPENDADDRESS  SPENDWITNESS
                        path: "m/49'/1'/0'/0/1", //多签时为每次签名的path
                        xpub: "ypub6XoGXBU3Cn6YT6GjagKjfixiSqXQHbpWLghWd9hBFAxEYh71wTDj3ogGwY2vN3qVRpzz82TRCgDyajbTf3yt2rMzmtKnAzRh6X1KW9QRsPA"
                    },
                ],
                requires: 2,
                signIndex: 0,
               redeemScript:"522102659e9ea86d82e90ebc12b03ea650b5c61cb04fba353355833e017b1ab7a237a821036860ac5093e660c27578783e64a7f933588247bb9940de2cbe295eedcbbc89e052ae" //单签时为空--赎回脚本
            },```
# This is my local code.


## Parameters passed to the hardware：
## inputs:
```address_n: (5) [-2147483599, -2147483647, -2147483648, 0, 0]
amount: 10000
multisig: {pubkeys: Array(2), signatures: Array(2), m: 2}
prev_hash: "8730a1bcc381704ce7f0807eb35c5d9f90da0b37e79203bcadd4316dc0f8db5e"
prev_index: 0
script_type: "SPENDMULTISIG"```

## outputs:
```0: {address: "1CR8yvSBBLBkYbwNTxNDSq2zAxEfP5vWiY", amount: 1500, script_type: "PAYTOADDRESS"}
1: {address: "38GnfUJ1qu5nuiMQDX8scRCf2YLZZ9AKEq", amount: 7500, script_type: "PAYTOP2SHWITNESS"}```

## return:
```error: "Loading timed out"```

**Comment by Ark-Chen** [comment]
When I convert ypub to xpub：
## ypub6XoGXBU3Cn6YT6GjagKjfixiSqXQHbpWLghWd9hBFAxEYh71wTDj3ogGwY2vN3qVRpzz82TRCgDyajbTf3yt2rMzmtKnAzRh6X1KW9QRsPA
==> xpub6Cy1DWo846Z4bo5ckKY7TdsDGsNxLyq1RaBHqkoHsAaMVbHngo4ARk28vL5LN9Ba2BtBNYrrk1sRhSytwMZsEcgPuYdMb5cCpnwg7XWXLaY

## return 
==> error: "Requested unknown tx: 8730a1bcc381704ce7f0807eb35c5d9f90da0b37e79203bcadd4316dc0f8db5e"

**Comment by Ark-Chen** [comment]
@prusnak Please help you to see what is going on.

**Comment by szymonlesisz** [comment]
Hi Chappell-C,
Your code is incomplete, please paste the WHOLE object you are trying to send into "signTransaction" method. Including "coin" parameter. It's really difficult to help you without it. What are the values of
```
 multisig: {pubkeys: Array(2), signatures: Array(2), m: 2}
```
object?

**Comment by szymonlesisz** [comment]
first thing that comes to my mind is that you are trying to sign testnet transaction (**"49'/1'/0"**) with combined BTC addresses (which starting with "3" or "1" but should be "m" or "2")

**Comment by Ark-Chen** [comment]
I found the reason，
First, you should use xpub，not ypub or upub.
Second, The script_type of the outgoing address should be SPENDWITNESS not SPENDMULTISIG。
@szymonlesisz @prusnak Thank you for your help.
