### ISSUE TITLE
When TrezorBridge installed, device selection is not shown in case of multiple device 

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#264]
![image](https://user-images.githubusercontent.com/19986226/48592804-79ec7400-e98d-11e8-895d-182145de5cd8.png)

Ubuntu 16.04
TrezorConnect v6

In this state if i call any TrezorConnect API it automatically selects `Trezor Emulator` i have no way to select my real device. 

In case TrezorBridge is not installed ( working with WebUSB ) I have an option to select device even if only one device is connected to the computer ( although it does not detects Trezor Emulator  ).

I understand there is fallback approach for transport layer ( ? )  and  a mechanism to use previous successful transport layer ( ? ).

And as per my understanding TrezorBridge is going to be depreciate, so would not be it nicer to give WebUSB more priority than TrezorBridge?

**Comment by prusnak** [comment]
Trezor Bridge is not going to be depreciated. WebUSB is Chrome only, so unless all other browsers adopt this feature (they won't) Bridge is the top priority. WebUSB being second.
