### ISSUE TITLE
 TrezorConnect.stellarSignTransaction() is basically broken

### ISSUE THREAD

**Issue by MisterTicot** [trezor/connect#267]
Sorry guys but there's too much to make a detailed report of each one. I assume it's an alpha or something?

TrezorConnect.stellarSignTransaction() doesn't accept a standard Stellar Transaction object, one have to JSON.parse(JSON.stringify()) it.

After doing so, I found out that transaction parameters were generally mis-interpreted. I tried 5 transaction and got 5 errors:
  * A payment of 20 XLM is interpreted as a payment of 0.000002 XLM
  * sequenceBump value is not parsed and stay stuck at 0
  * manageData operation fails (invalid Buffer object)
  * setOption operation fails (Something related to signer parameter I guess)
  * A transactions with two payments failed mysteriously

* I finally got a signature for one of the transactions, but it seems to be in hex format. I converted it to base64 but its too long (84 vs 64 bytes). Any clue how I should handle this ?

I'm eager to implement Trezor Wallet support into my website but in the current state of affair it looks like a bad idea: the random parameter interpretation is actually a serious security issue. Hope you're going to work on that and bring us an awesome Stellar support :)

**Comment by MisterTicot** [comment]
I figured out a Stellar transaction object can't go through postMessage(). Why don't you use XDR which's a transaction representation that  can be passed as a base64 encoded string? You have to rebuild the transaction at some point anyway so it better let us passing it directly rather than using an intermediate format.

I know Stellar transactions are not trivial to handle: I wrote a library focused on manipulating transactions across various format (you can play with it here: https://cosmic.plus/web-cosmic-lib/demo.html). If you need any help you can [reach me](mailto:mister.ticot@cosmic.plus), I'll be happy to contribute.

**Comment by szymonlesisz** [comment]
Hi @MisterTicot, 
Yes, looks like we are not compatible with stellar-sdk we already discussing it here: 
https://github.com/trezor/connect/issues/258

There are couple of reasons for that, the main is that there is no possibility to send complex object thru postMessage like you noticed. 
I'm not familiar with stellar-sdk and i didn't know about existence of XDR/base64 representation of transaction, but it looks like this could be solution to our problem.

Main goal here is to transform Stellar Transaction object into protobuf format (in snake_case) which will be sent to device. Whole conversion is happening here:
https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/stellarSignTx.js#L62-L200

If there is possibility to get those data/fields straight from XDR format that is great news.
And of course you can contribute :) this is an open repo. 
If you have an idea how to convert XDR to protobuf format (https://github.com/trezor/connect/blob/develop/src/js/types/trezor.js#L380) we will be very happy to merge your PR :)

**Comment by MisterTicot** [comment]
Hi @szymonlesisz,

Using JavaScript StellarSDK, you can generate an XDR from a Transaction object using:

> const xdr = transaction.toEnvelope().toXDR("base64")

And then back to Transaction:

> const transaction = new StellarSdk.Transaction(xdr)

You'll the get a Transaction object that is not so far from the kind of object you're accepting right now, except that you'll have to make the parameter gymnastic that you're now imposing to the users of your library - which is a good thing :)

I'd like to make sure about the workflow here:

* Client pass the transaction over postMessage()
* Your softwtare (in the popup) convert it to protobuf
* protobuf is sent to device for display and sign

Now I'm lost about something: what it is that you're actually signing? Should be the transaction hash but it's derived from the XDR so if you don't use XDR... There's a missing part here on which I'm blocking here. Is the device building a transaction object for signing?

**Comment by szymonlesisz** [comment]
That's the thing, i mentioned that in other thread. We don't want to maintain multiple coins SDKs inside our repository.
Since it has to be translated from one format to another at some point, we agreed that it should be done outside of TrezorConnect.
It could be archived with additional library which will translate StellarSDK-Transaction object into TrezorStellar-Transaction object. This module could be even part of this repository, but imported separately as utility not bundled with the whole logic.
We don't want to extend our bundle with multiple sdk's and force people to download megabytes of code if they don't use them.

**Comment by MisterTicot** [comment]
Well ok then maybe you could just accept a transaction in trezorConnect.stellarSignTransaction() and make the necessary changes to it. Maybe this way you don't need to use any dependency.

By the way do you now about asynchronous  library loading? In https://cosmic.link I use it to load my Ledger library only when client ask for it. You don't have to d/l it when you don't use it.

I still wonder what you're actually signing?

**Comment by szymonlesisz** [comment]
those are the messages expected by Trezor device, StellarSdkTransaction object needs to be mapped into this format:
https://github.com/trezor/connect/blob/develop/src/js/types/trezor.js#L380-L494

About accepting Transaction object inside "signStellarTransaction" method. 
We agreed that in needs to be converted to some json or any other simple format before it is sent via postMessage, right?
Now, trezor-connect npm library is a lightweight interface with only few essential methods just to create a communication channel between your app and iframe + popup which are served from trezor.io domain.
It passes method params as they are, without any validation. This kind of validation/transformation simply does not belong there and we don't want to put some coin logic there.

My proposition is to create a standalone, not bundled utility and use it like (note, this is just an example):

```javascript
import TrezorConnect, { stellarSdkTransactionParser } from 'trezor-connect';

TrezorConnect.stellarSignTransaction({
    transaction: stellarSdkTransactionParser(stellatSdkTransactionObject.build())
});
```
This way, this piece of code will be used only by those who use Stellar and wont be loaded for people who uses connect with other coins

**Comment by szymonlesisz** [comment]
And, yes. Connect use lazy-loading. You will not download anything before you call some TrezorConnect method

**Comment by MisterTicot** [comment]
Ok then, but this needs further specifications and bug fixes because not everything works as expected.

You still didn't told me what the device is signing exactly?

**Comment by szymonlesisz** [comment]
I've pasted this fields 2 times already:
https://github.com/trezor/connect/blob/develop/src/js/types/trezor.js#L380-L494

those messages are converted to protobuf and sent via USB cable to the device.

**Comment by MisterTicot** [comment]
Ok but that's what need to be signed: if I make no error what needs to be signed is a hash of the XDR object.

**Comment by szymonlesisz** [comment]
I'm not sure what exactly you are asking about. Connect doesn't sign anything, it just pass some messages to the device in format expected by device. Trezor device cannot assume that everyone will use stellar-sdk therefore it cannot be third-party related, in fact it cannot assume that javascript will be used at all, you can also communicate with Trezor using python for example. That is why it has his own message structure.

**Comment by MisterTicot** [comment]
My question is "what the device is signing exactly?" As in "Precisely, how do you generate the signature you send back?"

XDR is not JavaScript related, it's the binary format we use on the ledger. It's what suppose to be signed so I'm wondering how do you obtain valid signatures without it.

**Comment by tsusanka** [comment]
Hi @MisterTicot,

on the firmware side we do actually use XDR. In other words, we serialize the transaction as required for the Stellar network and then sign it.

I haven't read your discussion thoroughly but maybe your question is, why Connect (or whatever) does not send XDR directly and Trezor would just sign it? That's because Trezor needs to understand the data it is sending to show visual confirmation. So we prefer to send the data to Trezor  in protobuf and then serialize it to XDR in Trezor.

Also we are not using any XDR library, but we are serializing somewhat "manually". This is to save code size and memory. If you're more interested what is Trezor doing have a look [here](https://github.com/trezor/trezor-core/tree/master/src/apps/stellar), it's Python so it's quite easy to read.

**Comment by tsusanka** [comment]
Also, @zuluCrypto is the author of Stellar for trezor one (and we wrote trezor t support based on that), so maybe they are able to provide more asistence on this.

**Comment by MisterTicot** [comment]
@tsusanka Ok thank you that's what I was looking for.

**Comment by MisterTicot** [comment]
@szymonlesisz @tsusanka 

I'm willing to work a bit on a converter - is there a kind of debug mode or some way I can extract the XDR generated by the device? I'd like to run conversion test so we can have the big picture of the things to fix. I already have a test suite so it's a matter of integrating Trezor with it: https://cosmic.plus/web-cosmic-lib/debug.html

**Comment by tsusanka** [comment]
That'd be great.

Yes the trezor-core has an emulator where you can use a debug mode (run with `PYOPT=0 ./emu.sh` after `make build_unix`) and then you can print the data into your console or do whatever.

The best way to procede however, would be to add some tests. The unit tests are located in [trezor-core repo](https://github.com/trezor/trezor-core/tree/master/tests), the device tests in [python trezor](https://github.com/trezor/python-trezor/tree/master/trezorlib/tests/device_tests). I believe the unit tests are a better fit, so you could do something like [this test for NEM](https://github.com/trezor/trezor-core/blob/master/tests/test_apps.nem.transfer.py). Basically, you create some specific protobuf message and call a function in [Stellar.operations.serialize](https://github.com/trezor/trezor-core/blob/master/src/apps/stellar/operations/serialize.py) and assert against some data.

So for example you create a StellarManageDataOp message with some data, send it to write_manage_data_op and check if the data are correct.

Sounds good?

**Comment by MisterTicot** [comment]
Ok, looks like I have everything I need. I'm not very familiar with Python, though. I think I'll take a day next week to dig into that and see were it goes :+1:

**Comment by MisterTicot** [comment]
It turned out I'll have no time to dig into that. I'll still be happy to provide the test case and review the progress, though.

**Comment by bosomt** [comment]
all referenced issues are already closed.
Can we consider it fixed ?
Can we close this issue ?

**Comment by MisterTicot** [comment]
@bosomt I don't have time to confirm that. I assume that if all issues are closed we can close this one too. Thank you for noticing, I plan to work on Trezor/Stellar integration again once I'll have some free time. If I encounter any issue I can open a new open.

**Comment by bosomt** [comment]
i'm closing this old issue.
As soon someone report broken transactions + and we will be able to reproduce it we will open new issue in correct repository

@szymonlesisz please close, i can't

**Comment by MisterTicot** [comment]
I'm closing it. I'm in the process of doing a complete check of what works & what doesn't & I will post a detailed report for each issue.
