### ISSUE TITLE
Different authentication modes

### ISSUE THREAD

**Issue by karel-3d** [trezor/connect#27]
TREZOR and Connect should behave differently under following authentication modes. Motivation: each action has different workflow and returned variables, only Sign up should display address

**Singing up** (trezor:signup) = linking TREZOR with account
- TREZOR message "HTTPS request" + site / challenge visual / "Sign up to this site?" (Cancel/Confirm)
- TREZOR message "Visual check. The following identity should match:" + address. (OK)
- Connect returns public key + signature
- site displays address and asks for visual validation and password authentication.

**Checking linked publick key** (trezor:checkidentity ~ something like Check on TREZOR (eye))
- site displays linked address and asks for visual validation
- TREZOR message "Visual check. The following identity should match:" + address. (OK)
- Connect returns nothing

**Singing in** (trezor:login)
- TREZOR message "HTTPS request" + site / challenge visual / "Log into this site?" (Cancel/Confirm)
- Connect returns public key + signature

**Action confirmation** (trezor:confirm) ~ for withdrawals inside account etc., when public key is known
- TREZOR message "HTTPS request" + site / challenge visual / "Confirm site action?" (Cancel/Confirm)
- Connect returns signature only

**Comment by runn1ng** [comment]
(node: I am just copypasting @sipak comment from elsewhere, ask him questions, I don't understand this issue really)
