### ISSUE TITLE
ECDH session key with JS API

### ISSUE THREAD

**Issue by dwarrier** [trezor/connect#270]
Hi,

 I would appreciate any help or advice for making ECDH encryption and decryption available in a Javascript Trezor API.

I'm interested in using the Trezor hardware wallet to provide an ECDH key for use with the Enigma project (a short description of the encryption process used in that project is [here](http://enigma.co/protocol/Appendix.html?#encryption), code is [here](https://github.com/enigmampc/enigma-contract/blob/8ee9977d2201492affc984f0e007891836eaee81/lib/enigma-utils.js#L244)). The documentation mentions a case where the user generates a one time keypair, but I'm assuming that it's safe for the user to use the Trezor to provide a shared key. 

Ideally, the API calls would be made from a browser with Javascript so that this can be done from a dApp frontend. I can see functionality for ECDH session key creation in the `python-trezor` repo [here](https://github.com/trezor/python-trezor/blob/5bb7dc39b882d3e0c5db97e3817262090c3d0e45/trezorlib/misc.py#L41). However, I couldn't find a JS implementation for generating a key with ECDH in this repo.

Is this a feature that any contributors are planning to implement? If not, would it be fairly straightforward to do myself?

**Comment by dwarrier** [comment]
Looks like the implementation of ECDH in the Trezor code [here](https://github.com/trezor/trezor-crypto/blob/f9523f97df2c965835001d551738bbe1b93b53df/ecdsa.c#L644) is different than the one in Enigma, since the Trezor code concatenates X and Y, and Enigma replaces Y based on whether it's even or odd.

Is the implementation in the Trezor API considered closer to the standard than the one used by Enigma?

**Comment by tsusanka** [comment]
Hi,

ECDH is a key agreement protocol, so you do not use it for encryption per se, but you can derive a key which you then would then use for encryption.

The `get_ecdh_session_key` is currently used for [SSH/GPG support](https://github.com/romanz/trezor-agent), written by @romanz. It is basically tied to the project (though unfortunately it is in the "wallet" app space). That being said, it does not make much sense to expose this API from Connect.

I don't know much about Enigma, but if you would like to add Enigma support you'll probably have to start in the firmware ([trezor-core](https://github.com/trezor/trezor-core)), because I guess encryption is not the only thing Enigma protocol requires.

**Comment by matejcik** [comment]
I mean, it would be technically possible to use Trezor as-is, but you'd have to do the encryption/decryption on the PC instead of inside Trezor itself. Hard to say if that's worth it.

> Is the implementation in the Trezor API considered closer to the standard than the one used by Enigma?

I don't think there's a standard to be close to. Trezor's implementation seems to match what GPG does, you'd have to convert Trezor's representation to Enigma's in order to arrive at the same shared key, but that should not be difficult.

**Comment by dwarrier** [comment]
Thank you both for your explanations and insight, and (in advance) for your patience.

 tsusanka, 

> ECDH is a key agreement protocol, so you do not use it for encryption per se, but you can derive a key which you then would then use for encryption.


  Got it, I would like to have the Trezor return a derived key, which would then be used to encrypt data in the browser with Enigma’s encryption code.

>  The get_ecdh_session_key is currently used for SSH/GPG support, written by @romanz. It is basically tied to the project (though unfortunately it is in the "wallet" app space). That being said, it does not make much sense to expose this API from Connect. 


I mentioned Connect because I saw that https://github.com/trezor/trezor.js would be deprecated, and I assumed I’d need to implement this in JS. If I just implemented this on my own, would you recommend using the Connect repo?  

> don't know much about Enigma, but if you would like to add Enigma support you'll probably have to start in the firmware (trezor-core), because I guess encryption is not the only thing Enigma protocol requires.  


Do you think it would be straightforward for me to expose [ecdh_multiply](https://github.com/trezor/trezor-crypto/blob/f9523f97df2c965835001d551738bbe1b93b53df/ecdsa.c#L644), in a JS API? I think I need the X and Y  separately to apply the adaptation in the Enigma implementation, I’m not sure whether `get_ecdh_session_key` would return those in a form I could use.
 
matejcik,  

> I mean, it would be technically possible to use Trezor as-is, but you'd have to do the encryption/decryption on the PC instead of inside Trezor itself. Hard to say if that's worth it.  


Do you mean that the user’s security is heavily compromised by using the derived key to encrypt information in the browser with Javascript? I assumed this was (relatively) secure because it’s what Enigma is already planning to do, and I thought this was a common practice.

>   I don't think there's a standard to be close to. Trezor's implementation seems to match what GPG does, you'd have to convert Trezor's representation to Enigma's in order to arrive at the same shared key, but that should not be difficult.  


That sounds promising. Is the easiest way of doing this the approach I described above with `ecdh_multiply`?

**Comment by matejcik** [comment]
> Do you think it would be straightforward for me to expose [ecdh_multiply](https://github.com/trezor/trezor-crypto/blob/f9523f97df2c965835001d551738bbe1b93b53df/ecdsa.c#L644), in a JS API? I think I need the X and Y separately to apply the adaptation in the Enigma implementation, I’m not sure whether `get_ecdh_session_key` would return those in a form I could use.
> 

I don't see why you would need to do that. What Trezor returns is: `0x04[32-byte X][32-byte Y]`. Just split the bytes and continue the calculation.

> Do you mean that the user’s security is heavily compromised by using the derived key to encrypt information in the browser with Javascript? I assumed this was (relatively) secure because it’s what Enigma is already planning to do, and I thought this was a common practice.

It certainly is a common practice, but that doesn't mean that it's secure ;)

But it really depends on your threat model. The issue here is that not only you expose the decrypted content to your browser, but you also expose the encryption key. Given that non-ephemeral ECDH is used, then depending on the details it could allow an attacker to steal the encryption key and recover all old (or forge new) messages between the two communicating parties (i.e., two users with Trezors).

(The keyword here is _could_. This is by no means a security analysis.)
Maybe this risk is acceptable to you, given that you will expose decrypted content to the browser anyway? Maybe there are other mitigations? Who knows.

**Comment by dwarrier** [comment]
> I don't see why you would need to do that. What Trezor returns is: 0x04[32-byte X][32-byte Y]. Just split the bytes and continue the calculation.

Got it, thanks. If there's already a python implementation for this, it seems fairly straightforward to port that to JS.

> But it really depends on your threat model. The issue here is that not only you expose the decrypted content to your browser, but you also expose the encryption key. Given that non-ephemeral ECDH is used, then depending on the details it could allow an attacker to steal the encryption key and recover all old (or forge new) messages between the two communicating parties (i.e., two users with Trezors).

This is a great point, I overlooked that the derived key would be non-ephemeral, and therefore very risky to expose. I think I misunderstood the [Enigma docs](http://enigma.co/protocol/Appendix.html?#encryption), because the use of a non-ephemeral symmetric key sounds bad. It would make more sense to me if they were using the KDF they mention to generate ephemeral private keys, and use these with a static public key, to derive one-time symmetric keys with ECDH. Is this possible? There's still the issue of the master key being exposed of course, if the KDF is called in the browser.

Assuming that they were doing this, would it be necessary that the KDF that Enigma selects matches the [one used by Trezor](https://wiki.trezor.io/Cryptocurrency_standards#SLIP10_-_Universal_private_key_derivation_from_master_private_key), in order to use Trezor with the Enigma protocol?

**Comment by matejcik** [comment]
I suspect we're getting confused. At least I am :)
Trezor is a device for managing long-lived private keys. I don't think there's any advantage to using it for an ephemeral DH exchange: your attacker doesn't need the private key for anything, if they can steal the session key (which you _are_ exporting), they're done. So you could as well run the whole exchange on the PC.

What you could do is _sign_ the ephemeral keys with a long-lived identity, which is what `SignIdentity` is for. But I don't see if that exists in the Enigma protocol.

(Generating ephemeral keys *from* long-lived keys seems wonky at best. Why not just generate it randomly?)

So, what role would Trezor perform here?

**Comment by matejcik** [comment]
hmm, I think I know what you are getting at - like, Trezor would hold a static "receiving key" and the counterparty would generate an ephemeral "sending key"? I suppose that could work (that's what NaCl does IIRC). But in that case Trezor is just doing the ECDH computation. It doesn't depend on your choice of KDFs, you're getting raw data out, it's up to you how you process them further.

**Comment by dwarrier** [comment]
> I suspect we're getting confused. At least I am :)

I apologize for the confusion matejcik, I'm not as familiar with Enigma's encryption process as I should be. I'll get a better handle on how (or if) Enigma expects the derived key to be ephemeral. Your responses so far have been very helpful for my own understanding, I appreciate your help in sorting this out.

> Trezor is a device for managing long-lived private keys. I don't think there's any advantage to using it for an ephemeral DH exchange: your attacker doesn't need the private key for anything, if they can steal the session key (which you are exporting), they're done. So you could as well run the whole exchange on the PC.

I may be confused as to how Trezor uses a KDF. From Trezor's perspective, is a KDF only used for generating one pair of keys across different curves like in [the Trezor spec](https://github.com/satoshilabs/slips/blob/master/slip-0010.md), or is it also used to generate multiple key pairs on a single curve from a master key?
I assumed that if an attacker obtained an ephemeral session key, it would be much better than them obtaining a non-ephemeral one, since they wouldn't be able to decrypt previous or future messages.

> (Generating ephemeral keys from long-lived keys seems wonky at best. Why not just generate it randomly?)

I don't have a good answer to this. The Enigma [docs](https://enigma.co/protocol/Appendix.html#encryption) say the following:

> Any user that wants to encrypt a message for the enclave can generate a one-time asymmetric key-pair, and use that to derive a one-time symmetric key as in the usual ECDH protocol. The one-time symmetric key is generated with a key derivation function (KDF) that is yet to be specified.

I thought the KDF that they specify would take the user's private key as input and generate multiple one-time asymmetric key pairs. This is a complete guess, but I assumed that if a user encrypts data with a public key from a previously generated key pair, and wants to decrypt it later, they would be able to do this by somehow deriving the private key again. Whereas if they generated the key pair randomly, they may not be able to retrieve data encrypted with a previous ephemeral key.

> So, what role would Trezor perform here?

My assumption was that at some point during the interaction with the Enigma frontend code to create the symmetric key, a user needs to enter their private key to generate a key pair with the KDF mentioned in the docs. I could very well be wrong about this, I will follow up with Enigma to understand what information the user exposes and how the key pair is meant to be generated. 

> hmm, I think I know what you are getting at - like, Trezor would hold a static "receiving key" and the counterparty would generate an ephemeral "sending key"? I suppose that could work (that's what NaCl does IIRC). But in that case Trezor is just doing the ECDH computation. It doesn't depend on your choice of KDFs, you're getting raw data out, it's up to you how you process them further.

This is a good suggestion, and more or less the opposite of what I was thinking (: I'm not sure this approach is possible, since the counterparty would be an Enigma node that would normally provide its public key. I don't know whether there's functionality on the Enigma enclave side to generate ephemeral sending keys, I will look into that if it turns out this is the only way to use Trezor to prevent exposing the user's private key.

The approach you describe does make more sense than the opposite. I was thinking to somehow generate dynamic "receiving keys" from the Trezor, and use the same "sending key" from the counterparty (it would probably be static since it's the public address of an Enigma node). But my understanding of how Trezor uses KDFs is probably incorrect, I don't think that Trezor can create multiple key pairs in the way the Enigma docs describe.

**Comment by matejcik** [comment]
Ah, I think you confuse what Enigma calls "KDF" with Trezor's deterministic key derivation.
I'm somewhat sure that Enigma means KDF as a diffuser. As in, take the elliptic curve point you get from ECDH, feed it through a couple rounds of hashing so that all properties of the original elliptic point are lost, and get out a suitable symmetric key.

Trezor OTOH is concerned with deriving keys deterministically (i.e., the purpose of key derivation is to always get back the same key given the same path). Which I believe is unsuitable for ephemeral keys - you'd need some sort of nonce to include in the path, and Enigma does not talk about anything of the sort.

> I assumed that if an attacker obtained an ephemeral session key, it would be much better than them obtaining a non-ephemeral one, since they wouldn't be able to decrypt previous or future messages.

My point is that when the keys are ephemeral, stealing the private key is the same as stealing the session key. You can't use the ephemeral private key for anything else than deriving the session key, so protecting it more than the session key doesn't buy you more security.

> I thought the KDF that they specify would take the user's private key as input and generate multiple one-time asymmetric key pairs. This is a complete guess, but I assumed that if a user encrypts data with a public key from a previously generated key pair, and wants to decrypt it later, they would be able to do this by somehow deriving the private key again. Whereas if they generated the key pair randomly, they may not be able to retrieve data encrypted with a previous ephemeral key.

But then the key isn't really ephemeral, is it? :))

**Comment by dwarrier** [comment]
> Ah, I think you confuse what Enigma calls "KDF" with Trezor's deterministic key derivation.
> I'm somewhat sure that Enigma means KDF as a diffuser. As in, take the elliptic curve point you get from ECDH, feed it through a couple rounds of hashing so that all properties of the original elliptic point are lost, and get out a suitable symmetric key.

Thank you for pointing this out. I came across https://wiki.openssl.org/index.php/Elliptic_Curve_Diffie_Hellman and what you're saying makes sense. The Enigma docs were probably referring to the common practice of using a KDF with the output of ECDH.

> My point is that when the keys are ephemeral, stealing the private key is the same as stealing the session key. You can't use the ephemeral private key for anything else than deriving the session key, so protecting it more than the session key doesn't buy you more security.

I think I see-- so you're saying that if the session key is exposed to an attacker, it doesn't matter that the private key was hidden and held on the Trezor? And so in this case, there wouldn't be any advantage in using the Trezor.

> But then the key isn't really ephemeral, is it? :))

For my own understanding, is it part of the definition of an ephemeral key that it can't be derived in a deterministic way from a static key? Anyway, I'm not even sure how that process would work.

I'm afraid I may have wasted your time, matejcik. With the way Enigma currently does its message encryption, Trezor is probably not necessary or advantageous for establishing a shared symmetric key (since using randomly generated keypairs is just as secure). I'll confirm this with the Enigma team.

I think the the only way Trezor could be used here is if it generated a random keypair, used it with a static public key to determine a one time shared symmetric key (using Enigma's ECDH adaptation), and encrypted a message, all without exposing the symmetric key. I'm assuming this means the encryption would have to be done within the Trezor itself, which as you said early on in this thread, is not currently possible. 



`

**Comment by matejcik** [comment]
> > But then the key isn't really ephemeral, is it? :))
> 
> For my own understanding, is it part of the definition of an ephemeral key that it can't be derived in a deterministic way from a static key? Anyway, I'm not even sure how that process would work.

The point of an ephemeral key is that it is not recoverable. Typically it should be short-lived, erased immediately after an encrypted exchange is over. In some usecases ephemeral keys are stored for later use, but erased as soon as that "later use" happens. This gives you forward secrecy - a compromise after-the-fact won't find any old keys.

You certainly _can_ derive ephemeral keys deterministically, but you need to ensure that you can't derive the same key later. So you would need some nonce as one of the inputs - a piece of data that you can erase with no possibility of getting it back.

> I think I see-- so you're saying that if the session key is exposed to an attacker, it doesn't matter that the private key was hidden and held on the Trezor? And so in this case, there wouldn't be any advantage in using the Trezor.

Correct. Because even if you exposed the private key, your attacker couldn't do anything worse with it than derive the session key. If they _have_ the session key, they don't need the private key for anything else.

---

I guess we can close the issue then?

**Comment by dwarrier** [comment]
> The point of an ephemeral key is that it is not recoverable. Typically it should be short-lived, erased immediately after an encrypted exchange is over. In some usecases ephemeral keys are stored for later use, but erased as soon as that "later use" happens. This gives you forward secrecy - a compromise after-the-fact won't find any old keys.
> 
> You certainly can derive ephemeral keys deterministically, but you need to ensure that you can't derive the same key later. So you would need some nonce as one of the inputs - a piece of data that you can erase with no possibility of getting it back.

This is helpful, I appreciate the explanation.

> I guess we can close the issue then?

Sure! Thank you for your patience and thorough responses, matejcik. I learned quite a bit from this conversation, I hope this helps others if they have similar questions.
