### ISSUE TITLE
trezor-connect using server url instead of trezor.io

### ISSUE THREAD

**Issue by lordcase** [trezor/connect#271]
I am trying to replicate the stellar account viewer implementation of trezor-connect. However it keeps lookong for the popup at the originating server's URL.

What does this depend on? I have tried the window.TREZOR_POPUP_ORIGIN = 'https://connect.trezor.io' solution however vith version6 it doesnt seem to work.
I have no local trezor-connect version, I just want to use the official one. What does this depend on?

Thx in advance

**Comment by szymonlesisz** [comment]
Hi @lordcase,
Connect is set to open popup from "connect.trezor.io" domain automatically, however if you want to use popup from different location you need to set 
window.__TREZOR_CONNECT_SRC = 'http://xxxx';

note that v4 is not compatible with v5+

**Comment by lordcase** [comment]
Thanks @szymonlesisz my mistake, it is working now perfectly!
