### ISSUE TITLE
BTC Transaction more utxos

### ISSUE THREAD

**Issue by garysen** [trezor/connect#276]
Sometimes there is an extreme case, when a transaction (BTC) contains
multiple UTXO (say 500 UTXOS), the hardware needs a long time to complete the
signature, and sometimes even cannot be signed successfully. What is the
optimization scheme? Thanks!

**Comment by tsusanka** [comment]
There is not much we can do about this one. We try to optimize as best as we can but until Bitcoin's Taproot arrives we need to stream previous transaction for each and every UTXO to calculate the fee which is demanding.

Do you have a real use case where BTC signing actually failed? Could you provide FW version?

**Comment by prusnak** [comment]
No response. Closing.
