### ISSUE TITLE
ethereumGetAddress returns address of incorrect path

### ISSUE THREAD

**Issue by piavgh** [trezor/connect#277]
This is the code for getAddress() function:

```
const defaultDPath = "m/44'/60'/0'/0";

getAddress = () => {
        return new Promise(async (resolve, reject) => {
            let result = await TrezorConnect.ethereumGetAddress({
                path: defaultDPath
            });
            console.log(result);
            if (result.success) {
                this.address = result.payload.address;
                resolve(result.payload.address);
            } else {
                console.log(result);
                reject(result.payload.error);
            }
        });
    };
```

For my case, it returns `0x38239D328e43d476e50673b23125f25f7f03a7D0`, but this address is corresponding to path `m/44'/60'/0'`, NOT the path `m/44'/60'/0'/0` that is in my code (the correct value should be `0xa2E4a0DCb8137cB2e178e1Dd881C5aB3171C3b62`)

This causes the signTransaction method to be wrong also.

**Comment by 0GCRYPT0** [comment]
Hi piavgh,
I believe that the address that you get returned is an Ethereum address generated from a private key derived from the combination of the path's private key and some salt from your trezor. If you're having difficulties sending ETH, you should try the new Ethereum wallet on beta-wallet.trezor.io it's pretty slick. Not sure if it's on the main channel yet.

Hope that helps you.

**Comment by szymonlesisz** [comment]
You default path is missing an address index. So it should looks like "m/44'/60'/0'/0/0"
Read more here: https://github.com/trezor/trezor-core/tree/master/docs/coins
