### ISSUE TITLE
Validate Stellar amounts are integers

### ISSUE THREAD

**Issue by tsusanka** [trezor/connect#278]
Since we use [stroops](https://www.stellar.org/developers/guides/concepts/assets.html#one-stroop-multiple-stroops) instead of lumens, we should validate amounts are in integers.

See https://github.com/trezor/trezor-core/issues/421#issuecomment-444018131 for more info.

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/connect/pull/279
