### ISSUE TITLE
XRP - ripple, unable to input destination tag

### ISSUE THREAD

**Issue by okipol88** [trezor/connect#283]
Hello,

I don't see an option to input a destination tag for XRP transaction.
Is it missing? It is pretty crucial to identify a transaction in case of exchanges.

**Comment by szymonlesisz** [comment]
Looks like it's missing in firmware, there is no "destination" field except for `msg.payment.destination` which is a receiver address.
Please move your issue to https://github.com/trezor/trezor-core/issues

**Comment by tsusanka** [comment]
Will do in https://github.com/trezor/trezor-core/issues/443
