### ISSUE TITLE
TrezorConnect without Bitcore

### ISSUE THREAD

**Issue by tynes** [trezor/connect#290]
Is it possible to sign transactions locally in the browser without fetching data from Bitcore?

Here it creates a backend:
https://github.com/trezor/connect/blob/develop/src/js/core/methods/SignTransaction.js#L102

Does this mean I should be using `trezor.js`?

**Comment by szymonlesisz** [comment]
To sign a non-segwit transaction you also need to know a input transaction hash. That is why there is a required connection to backend to fetch those data.
`trezor.js` will do the same. There is no possibility to sign this type of transaction in offline mode (yet)
However we could probably add another field to "signTransaction" method where you could put those referenced transactions in expected format (Trezor expects them in different format than data provided from backend; see next two lines of code that you highlighted - "getReferencedTransactions" and "transformReferencedTransactions" utils) 
I'm afraid that it will be too complicated to developers and will bring more issues like "signTransaction is not working". 
I will consult this with our team and let you know.

**Comment by tynes** [comment]
Thank you for the response. This functionality would be very useful to our application as it would allow for airgapped signing + privacy. We are using the bcoin wallet as a backend and have all of the information required locally to do the signing. We could map the data into the correct format required for the trezor. I am open to chatting some more as I believe this is a very important feature. I am sure that we are not alone in wanting this functionality

**Comment by szymonlesisz** [comment]
since 7.0.2 you can use `refTxs` field to sign transaction without connection to bitcore.
https://github.com/trezor/connect/blob/develop/docs/methods/signTransaction.md
