### ISSUE TITLE
Can't sign Bch transaction with custom path

### ISSUE THREAD

**Issue by werner** [trezor/connect#300]
I generate an address using an xpub for bitcoin cash with this path: `m/49'/0'/0'/0/0/145/0/0`. The address is `qrq8s6u93hyt0n7re93jekk43f30v68qtg2qeljm5r`.

I tried to sign a transaction, but it always fails with this generic error: `Failed to compile output`.

Is it possible to sign the transaction?.

The transaction I'm trying to sign is:

```json
{
    "inputs": [["","349bb875f6353fe94cadd2edc222d7480edfce856522848b98cb851536eba8ff", 0, 14110500]],
    "trezor_inputs": [
        { "address_n": [2147483697, 2147483648, 2147483648, 0, 0, 145, 0, 0],
          "prev_hash": "349bb875f6353fe94cadd2edc222d7480edfce856522848b98cb851536eba8ff",
          "prev_index": 0}
    ],
    "trezor_outputs": [
        {
            "script_type": "PAYTOADDRESS",
            "address": "qp48agdrqxrru8wlszugulwhrj7epn3jz5dcc2c23c",
            "amount": 14100500
        }
    ]
}
```

Thanks.

**Comment by prusnak** [comment]
You are using the wrong output address. It is missing the "bitcoincash:" prefix, the correct value is "bitcoincash:qp48agdrqxrru8wlszugulwhrj7epn3jz5dcc2c23c"

**Comment by werner** [comment]
Worked as expected, thanks
