### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by federicobond** [trezor/connect#301]
TypeScript has gained a lot of traction lately and it would be great to bundle some type definitions for it in this library. The API surface is pretty big though and it's likely I will get some of the details wrong. We already have some types we are using internally at Muun for our Web integration, which I could cleanup and contribute here.

Is this something you would be interested in supporting? We can kickstart the effort and use your help to incrementally add the remaining types.

**Comment by federicobond** [comment]
I submitted some type definitions for common and Bitcoin-related methods to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32308

**Comment by szymonlesisz** [comment]
Hi @federicobond,
Thanks for your contribution. We do have migration to TypeScript in our plans, but it's not high priority and right now we have more important things to do.  Just as you notice, this api is quite big and growing up everyday so this is not an easy task.
