### ISSUE TITLE
Correctly work with numbers larger then 2^53

### ISSUE THREAD

**Issue by tsusanka** [trezor/connect#302]
Unfortunately, some coins use integers larger than 2^53 - 1, where the precision can get [lost](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) during operations, because the integer does not fit in the IEEE-754 floating point standard ([more info](https://stackoverflow.com/questions/1848700/biggest-integer-that-can-be-stored-in-a-double)). This concerns Dogecoin, Stellar and maybe some others.

**Comment by refi93** [comment]
this affects also Cardano: https://github.com/trezor/connect/blob/5d843d41d40e9b6d20bd50da95420b3be700a7a4/src/js/core/methods/CardanoSignTransaction.js

https://cardanodocs.com/technical/protocols/binary-protocols/#basic-cardano-sl-data-types (max coin supply needs 56 bits to represent)

**Comment by kolontsov** [comment]
Hi, any updates on this issue?

**Comment by szymonlesisz** [comment]
Fixed in 8.0.7 for Cardano, Stellar, Ripple and Lisk. Bitcoin-like (doge, etc...) was unaffected
