### ISSUE TITLE
(Multi-sig) External addresses no xpub?

### ISSUE THREAD

**Issue by mralbertchen** [trezor/connect#311]
From reading the documentation and perusing the repo I've discovered that the multisig param as specified in MultisigRedeemScriptType must have an array of { node, address_n } which I understand to be master xpub and derivation path. This makes sense for trezor wallets, but what if I have a multi-sig address with non-HD-wallets as other signers? Is there a way to just simply pass the public key? From my understanding this parameter is only necessary to construct the redeem script which will be part of the sighash, so providing the public key should suffice?

**Comment by prusnak** [comment]
You can always generate XPUB (node) from the public key and use empty address path.
