### ISSUE TITLE
LTC TEST Tx not found

### ISSUE THREAD

**Issue by Ark-Chen** [trezor/connect#313]
I signed ltctest in a similar way to btctest，return "Tx not found, txid 9501a8d9e76deef2e8a379538d11f5f7f813bffae2d3fbf7de0cbbf79c8a0a52: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions."

I made a lot of attempts, but I don't know where the problem is.
Can you help me give me some tips?
Looking forward to your reply

**Comment by Ark-Chen** [comment]
TrezorConnect.setCurrency('TEST');

/*
{
	accountDiscoveryBip44CoinType: null,
	accountDiscoveryGapLength: null,
	accountDiscoveryLimit: null,
	bitcoreURLS: null,
	coin: undefined,
	coinInfoURL: null,
	currency: "TEST",
	currencyUnits: null,
	inputs: {
		0: {
			address_n: (5) [-2147483604, -2147483646, -2147483648, 0, 1]
			amount: 100000000
			multisig: {pubkeys: Array(2), signatures: Array(2), m: 2}
			prev_hash: "9501a8d9e76deef2e8a379538d11f5f7f813bffae2d3fbf7de0cbbf79c8a0a52"
			prev_index: 1
			script_type: "SPENDMULTISIG"
		},
	}
	outputs: {
		0: {address: "2NFraFRbT52SdsFqBK8wsNK4SeiyLgjEJSc", amount: 89990000, script_type: "PAYTOADDRESS"}
		1: {address: "n3LHY1vBuqjg3MNJYSuon5YJNetPb9vcN6", amount: 1000000, script_type: "PAYTOADDRESS"}
	},
	type: "signtx"
}
*/

**Comment by szymonlesisz** [comment]
Hi @Chappell-C ,
From the syntax it looks like you are using old version of connect (4 or below) which is not maintained.
Normally i would recommend you to use version 6 but unfortunately connect doesn't support Litecoin Testnet neither in newest or older versions. We just don't have any Litecoin testnet backends to work with.

TEST coin is used bitcoin testnet network only with bitcoin testnet backends which obviously doesn't have any record of transaction with hash "9501a8d9e76deef2e8a379538d11f5f7f813bffae2d3fbf7de0cbbf79c8a0a52"

There is already an issue on not using backends while signing transaction:
https://github.com/trezor/connect/issues/290

**Comment by Ark-Chen** [comment]
@szymonlesisz Thank you very much
