### ISSUE TITLE
Firmware of connected device is too old

### ISSUE THREAD

**Issue by ssalaberry** [trezor/connect#315]
A few hours ago, TREZOR stopped working. When connected to version 4 of trezor connect, it throws an exception of **Firmware of connected device is too old**.

We are using the following script https://connect.trezor.io/4/connect.js

Any help would be appreciated

**Comment by szymonlesisz** [comment]
Whats you FW version? Btw you should consider to update connect to newest version (6)

**Comment by ssalaberry** [comment]
After update the firmware, the device started working porperly. Yes @szymonlesisz , we have created a task in my project to do that. Thanks.

Can close this issue.
