### ISSUE TITLE
myetherwallet with ATH

### ISSUE THREAD

**Issue by lutsifer** [trezor/connect#329]
First i wish to apologize if this is not the right repo to post this problem, but I can't be sure where to put it actually.
I am trying to send ATH using myetherwallet, when I confirm sending operation from my trezor model one it throws error:

`{"exception":{"values":[{"type":"TypeError","value":"Invalid hex string","stacktrace":{"frames":[{"colno":268959,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"s","in_app":true,"lineno":138},{"colno":268765,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"o","in_app":true,"lineno":138},{"colno":17436,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"Generator.e.(anonymous function) [as next]","in_app":true,"lineno":206},{"colno":18340,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"Generator._invoke","in_app":true,"lineno":206},{"colno":17257,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"w","in_app":true,"lineno":206},{"colno":45058,"filename":"https://www.myetherwallet.com/js/chunk-069f93bf.d1920ef8.js","function":"?","in_app":true,"lineno":1},{"colno":1413,"filename":"https://www.myetherwallet.com/js/chunk-069f93bf.d1920ef8.js","function":"a","in_app":true,"lineno":1},{"colno":751,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"new u","in_app":true,"lineno":24},{"colno":965,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"c","in_app":true,"lineno":24},{"colno":1535,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"f","in_app":true,"lineno":24},{"colno":9940,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"Uint8Array.u.write","in_app":true,"lineno":24},{"colno":5021,"filename":"https://www.myetherwallet.com/js/vendors.3e5803c7.js","function":"x","in_app":true,"lineno":24}]}}],"mechanism":{"handled":true,"type":"generic"}},"event_id":"2ccf75a0756849a6affc1d3dc8615330","platform":"javascript","sdk":{"name":"sentry.javascript.browser","packages":[{"name":"npm:@sentry/browser","version":"4.6.0"}],"version":"4.6.0"},"environment":"web","release":"5.0.2","request":{"url":"https://www.myetherwallet.com/interface","headers":{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"}},"tags":{"network":"ATH","service":"wallet.atheios.com","walletType":"trezor"}}
`
I am getting again error trying to send from mycrypto.com wallet.
So it turns out that I have no way to access my ATH funds using trezor device?

**Comment by prusnak** [comment]
Use our next wallet: https://beta-wallet.trezor.io/next/

**Comment by lutsifer** [comment]
:) right away after you add an option to use alternative ethash coins. I was trying to send ATH.
