### ISSUE TITLE
TypeError: Cannot read property 'email' of null

### ISSUE THREAD

**Issue by andrewsource147** [trezor/connect#344]
When I update the newest version of trezor-connect, I got error when trying to connect trezor in my DAPP. 
```
var parseManifest = function parseManifest(manifest) {
  if (typeof manifest.email !== 'string') {
    return null;
  }

  if (typeof manifest.appUrl !== 'string') {
    return null;
  }

  return {
    email: manifest.email,
    appUrl: manifest.appUrl
  };
};

```

After comment manifest.email  and manifest.appUrl it worked.
![screen shot 2019-03-01 at 12 25 42 pm](https://user-images.githubusercontent.com/31321699/53618287-47eddd80-3c1d-11e9-9120-d54978b31a57.png)

**Comment by andrewsource147** [comment]
Sorry my bad. I cannot reproduce this issue now, maybe it conflicts with one of my chrome extensions.

**Comment by szymonlesisz** [comment]
Did you set your `TrezorConnect.manifest`?
We've added a new required method in which we would like you to provide a contact to reach you in case of any required maintenance.
you can read more here:
https://github.com/trezor/connect/blob/develop/docs/index.md#trezor-connect-manifest

**Comment by andrewsource147** [comment]
Thank you, will add that!
