### ISSUE TITLE
Trezor Connect JS Produces DIfferent Signature Than Python Trezor Lib

### ISSUE THREAD

**Issue by yuriygeorge** [trezor/connect#345]
Bitcoin Testnet

When I use the Python Trezor to generate a signature, I get this:
```
304402203d34d52cb84a0207809d903d6ae12890e74722469c97a59a873b23e96df9c13702202db4f3b2d6a4fef56067050bc599889f9fdba62c1aca73ac0a3348963f4165aa
```

But when I use Trezor Connect, I get something else:
```
30440220548b61674368e81bb99c6c3aeb8a49814544d6a397c77933e448b0e9c68e683e02206a03f31794ed19b39c658435c1471722574ac3a6081cc3bda3f217a8f3ba5610
```

I need to be able to generate the same signature using both libraries.

I notice the Python library has some additional parameters - prev_txes, but trezor-connect does not.

```python
trezorlib.btc.sign_tx(client, coin_name, inputs, outputs, details=None, prev_txes=None)
```
Other than the prev_txes parameters, the parameters I send to JS-Connect and Python-Trezor are exactly the same, below.

Can anyone take a guess why my signatures don't match up? May this have something to do with the prev_txes logic that Python Trezor library uses? Is there a way to send prev_txes to Trezor Connect?

```javascript
{
   "inputs":[
      {
         "address_n":[
            2147483693,
            0,
            0,
            0
         ],
         "prev_hash":"b42c658796927fb4d75aa7c5c404be78718c814b4fcd9a22a077a8c876a7240f",
         "prev_index":0,
         "script_sig":"00483045022100f96ce611c1e06e540acadc83d8b74c4e8e38aaedea6c1bae5f6e25ce07d83a2f02201960ad9b78c9f511d75444794a9b975391913f6526cd095de1d7f4edd7ee050c0101ff4cad524c53ff043587cf0000000000000000006109a29836a5adfc1e03c0ec9f9e606109d9392670d8bcabdacdfa7ce9e48ed5028cb7707b6a0b73a27946c044f3d2ea9356e9b163986c07c22e299e93e16d45aa000000004c53ff043587cf02b114b63000000000d499aa3ddd978271b43979d84a38656b296177c08e1babfb4fdc15f59c4bfec4023b7830d36f197844b7203a9fab93afde0d2eb45aa98352e394c750280ec97e950000000052ae",
         "sequence":4294967293,
         "script_type":"SPENDMULTISIG",
         "multisig":{
            "m":2,
            "pubkeys":[
               {
                  "node":"tpubD6NzVbkrYhZ4XJeyzHmeBT7k3caJqz8JJgnFUCPmDv287qWcVm4Sq7av35EpbF5hjHMqwRykp3PYhjnrvqwfmvEzoafLJkjZdw8sP8kRCr3",
                  "address_n":[
                     0,
                     0
                  ]
               },
               {
                  "node":"tpubDBSkiQYQ3thN8VgYvtYHBUJR7KUJZvDNzdJXJ45thgnnakd8hUALaBCkxSqoxyL4jxSbdiS2iobo2QzPYGmsJ6VJpcawSXM9XrrgDyzWTpr",
                  "address_n":[
                     0,
                     0
                  ]
               }
            ],
            "signatures":[
               "",
               ""
            ]
         },
         "amount":"11099696"
      }
   ],
   "outputs":[
      {
         "address":"n1iozfb1SY9tDj5vwaLtKJWZ6EgZrYpZej",
         "amount":"11089696",
         "script_type":"PAYTOADDRESS"
      }
   ],
   "coin":"Testnet",
   "locktime":1484660
}
```

**Comment by prusnak** [comment]
Show me the Python code you use to call `trezorlib.btc.sign_tx`

**Comment by yuriygeorge** [comment]
Thanks for your reply.

inside the btc.py file of the trezorlib python library, this function is called (by electrum) as:

```python
def sign_tx(client, coin_name, inputs, outputs, details=None, prev_txes=None)
```

with the following parameters

client: <trezorlib.client.TrezorClient object at 0x7fbc0c7ce7f0> with transport[ bridge:lib02]

coin_name: 'Testnet'

inputs: List of a single TxInputType object:
```python
[<TxInputType: {'address_n': [2147483693, 0, 0, 0], 
'prev_hash': b'\xb4,e\x87\x96\x92\x7f\xb4\xd7Z\xa7\xc5\xc4\x04\xbexq\x8c\x81KO\xcd\x9a"\xa0w\xa8\xc8v\xa7$\x0f', 'prev_index': 0, 'script_sig': b'\x00\x01\xff\x01\xffL\xadRLS\xff\x045\x87\xcf\x00\x00\x00\x00\x00\x00\x00\x00\x00a\t\xa2\x986\xa5\xad\xfc\x1e\x03\xc0\xec\x9f\x9e`a\t\xd99&p\xd8\xbc\xab\xda\xcd\xfa|\xe9\xe4\x8e\xd5\x02\x8c\xb7p{j\x0bs\xa2yF\xc0D\xf3\xd2\xea\x93V\xe9\xb1c\x98l\x07\xc2.)\x9e\x93\xe1mE\xaa\x00\x00\x00\x00LS\xff\x045\x87\xcf\x02\xb1\x14\xb60\x00\x00\x00\x00\xd4\x99\xaa=\xdd\x97\x82q\xb49y\xd8J8ek)aw\xc0\x8e\x1b\xab\xfbO\xdc\x15\xf5\x9cK\xfe\xc4\x02;x0\xd3o\x19xD\xb7 :\x9f\xab\x93\xaf\xde\r.\xb4Z\xa9\x83R\xe3\x94\xc7P(\x0e\xc9~\x95\x00\x00\x00\x00R\xae', 
'sequence': 4294967293, 
'script_type': 1, 
'multisig': <MultisigRedeemScriptType: 
{'pubkeys': [
<HDNodePathType: {'node': <HDNodeType: {'depth': 0, 'fingerprint': 0, 'child_num': 0, 'chain_code': b'a\t\xa2\x986\xa5\xad\xfc\x1e\x03\xc0\xec\x9f\x9e`a\t\xd99&p\xd8\xbc\xab\xda\xcd\xfa|\xe9\xe4\x8e\xd5', 'public_key': b'\x02\x8c\xb7p{j\x0bs\xa2yF\xc0D\xf3\xd2\xea\x93V\xe9\xb1c\x98l\x07\xc2.)\x9e\x93\xe1mE\xaa'}>, 'address_n': [0, 0]}>, 
<HDNodePathType: {'node': <HDNodeType: {'depth': 2, 'fingerprint': 2970924592, 'child_num': 0, 'chain_code': b'\xd4\x99\xaa=\xdd\x97\x82q\xb49y\xd8J8ek)aw\xc0\x8e\x1b\xab\xfbO\xdc\x15\xf5\x9cK\xfe\xc4', 'public_key': b'\x02;x0\xd3o\x19xD\xb7 :\x9f\xab\x93\xaf\xde\r.\xb4Z\xa9\x83R\xe3\x94\xc7P(\x0e\xc9~\x95'}>, 'address_n': [0, 0]}>], 
'signatures': [b'', b''], 
'm': 2}>, 
'amount': 11099696}>]
```

outputs: List of a single TxOutputType object: 
```python
[<TxOutputType: {'address': 'n1iozfb1SY9tDj5vwaLtKJWZ6EgZrYpZej', 'amount': 11089696, 'script_type': 0}>]
```
details: SignTx object:
```python
<SignTx: {'version': 2, 'lock_time': 1484660}>
```

prev_txes: Dictionary with a single key/value pair, with key being some bytes hash:
```python
b'\xb4,e\x87\x96\x92\x7f\xb4\xd7Z\xa7\xc5\xc4\x04\xbexq\x8c\x81KO\xcd\x9a"\xa0w\xa8\xc8v\xa7$\x0f'
```

and value TransactionType:
```python
<TransactionType: {'version': 2, 'inputs': [<TxInputType: {'prev_hash': b'\x88\xdf\x1f8\x12\x16\xaa.\t;\x03\xa7\x91\xdf\x12\xbb<n\xa0b3\xacN\xe38\xdeRq\x0e\xb8I\x9f', 'prev_index': 1, 'script_sig': b'H0E\x02!\x00\x889`9mx\x9c\xe7N>\xf0\xe3i\x1d\x181\xc2k\xac\x7f\xfa\x94\xb8\xd5\xb9\x1ax\x03\xfc\xa0\x86E\x02 [e\x14\xd1\xcd\xe2L\xa8\x1b\xbd{\xb2`\x88]\xb9\xbb]\x8dj`\xb1\xa4\xb2{mD\r5\xb4\xb2C\x01!\x02?\x92\xd5\x86zq\xaa\xcb@W\x96\xa7\x9e\xa1\x8a\x9b,\xba\xba\xc5/\xa5\xbfe\xd8AB\x10\x02\xc4a\xae', 'sequence': 4294967293}>], 'bin_outputs': [<TxOutputBinType: {'amount': 11099696, 'script_pubkey': b'\xa9\x14\x8c{\xa6\x8da;{\xd95\xf5\xa0\xca\x89\xdfT\x82?\x16\x9e\xef\x87'}>], 'lock_time': 1482215}>
```

I believe this is a non-segwit transaction. Derivation path I'm using is 'm/45'/0' (which is recommended by Electrum). Shouldn't/is there a way for Trezor Connect JS lib also be able to pass the prev_txes parameter for non-segwit transactions?

By the way, the signature is then returned in bytes format, for which then electrum calls the .hex() function to generate the signature: 
```python
304402203d34d52cb84a0207809d903d6ae12890e74722469c97a59a873b23e96df9c13702202db4f3b2d6a4fef56067050bc599889f9fdba62c1aca73ac0a3348963f4165aa
```

while Trezor Connect JS signature for the same inputs (minus the "prev_txes" parameter) is:
```python
30440220548b61674368e81bb99c6c3aeb8a49814544d6a397c77933e448b0e9c68e683e02206a03f31794ed19b39c658435c1471722574ac3a6081cc3bda3f217a8f3ba5610
```

By the way, I believe I'm using trezor connect version 6, by the way, since this is called:
https://connect.trezor.io/6/popup.html#loading

**Comment by szymonlesisz** [comment]
I will investigate this.
BTW, is there any particular reason why are you not using correct address_n? (it should have 5 places, and testnet should have values: `[ 2147483693, 2147483649, 2147483648, 0, 0 ]`

**Comment by prusnak** [comment]
@szymonlesisz they are using multisig

**Comment by szymonlesisz** [comment]
I am aware that's not the reason of this bug, i'm just curious :)
My second question is: which version of TrezorConnect are you using?

**Comment by prusnak** [comment]
maybe @matejcik can also help?

**Comment by yuriygeorge** [comment]
I am just using the standard:
```javascript
import TrezorConnect from 'trezor-connect'
```
and when the popup happens, it loads: 
https://connect.trezor.io/6/popup.html#loading

So, I'm guessing version 6.

Interestingly enough, when I try to run the Trezor Connect on localhost:8082, pointing to the v6 branch, (and then setting window.__TREZOR_CONNECT_SRC = 'https://localhost:8088/'), I get 
"Encountered invalid prev_hash"
but when I point my application to the standard connect.trezor.io, then I get the above output in my original post.

**Comment by szymonlesisz** [comment]
could you try to upgrade to 7.0.1 ? (by setting window.__TREZOR_CONNECT_SRC = 'https://connect.trezor.io/7/')

**Comment by yuriygeorge** [comment]
Sure, when setting window.__TREZOR_CONNECT_SRC = 'https://connect.trezor.io/7/', the trezor screen loads the "Confirm path - Path m/45'/0/0/0 is unknown Are you sure? Yes | No" I click yes (green checkmark), and then it fails, returning the error: 

Encountered invalid prev_hash

When I run the original version 6 (https://connect.trezor.io/6), interestingly enough, it does sign however, as described in above posts, just a different signature than from what is generated by python trezorlib

**Comment by yuriygeorge** [comment]
Regarding your question - is there any particular reason why are you not using correct address_n?

I'm not really sure, but I model the address_n from the Electrum's project. For testnet, and legacy (non-segwit) p2sh multi-sig, it choses this derivation path: m/45'/0, which I believe translates to the address_n above: [2147483693, 0, 0, 0]

**Comment by szymonlesisz** [comment]
Ok, i think i've find the issue. 
I think the reason will be the `locktime` field. Connect 6 ignore this parameter and doesn't send it to device. That's why your signature is different. It was added since connect 7.

Could you confirm that by signing your transaction using connect@6 and python-trezor without `locktime` ?

**Comment by szymonlesisz** [comment]
Now i will have a look on `Encountered invalid prev_hash` issue

**Comment by prusnak** [comment]
@szymonlesisz if you don't send `locktime` while streaming prevhash transactions this will also be the cause for `Encountered invalid prev_hash` issue (the prevhash tx in the above example has locktime set to non-default value)

**Comment by yuriygeorge** [comment]
Electrum automatically sets the locktime parameter to the current block I believe, but I hardcoded it so it did not pass the locktime to Trezorlib (i.e., setting it to None), which yielded this signature:
```
304402203f88e48bf50fd8ece0869fe82a8b28db4b6f3dbe200310c71a87ce5c8574763202202baab0aef7c2cdbe28a1d554d47b79682a2e53b0cf5cc7ca899650092230c6ee
```
Trezor connect@6 yielded this signature:
```
30440220548b61674368e81bb99c6c3aeb8a49814544d6a397c77933e448b0e9c68e683e02206a03f31794ed19b39c658435c1471722574ac3a6081cc3bda3f217a8f3ba5610
```
Still different. (The connect@6 library yielded the same signature the whole time, as above). Will play around some more.

I used these params for connect@6
```javascript
{"inputs": [{"address_n": [2147483693, 0, 0, 0], "prev_hash": "b42c658796927fb4d75aa7c5c404be78718c814b4fcd9a22a077a8c876a7240f", "prev_index": 0, "script_sig": "0001ff01ff4cad524c53ff043587cf0000000000000000006109a29836a5adfc1e03c0ec9f9e606109d9392670d8bcabdacdfa7ce9e48ed5028cb7707b6a0b73a27946c044f3d2ea9356e9b163986c07c22e299e93e16d45aa000000004c53ff043587cf02b114b63000000000d499aa3ddd978271b43979d84a38656b296177c08e1babfb4fdc15f59c4bfec4023b7830d36f197844b7203a9fab93afde0d2eb45aa98352e394c750280ec97e950000000052ae", "sequence": 4294967293, "script_type": "SPENDMULTISIG", "multisig": {"m": 2, "pubkeys": [{"node": "tpubD6NzVbkrYhZ4XJeyzHmeBT7k3caJqz8JJgnFUCPmDv287qWcVm4Sq7av35EpbF5hjHMqwRykp3PYhjnrvqwfmvEzoafLJkjZdw8sP8kRCr3", "address_n": [0, 0]}, {"node": "tpubDBSkiQYQ3thN8VgYvtYHBUJR7KUJZvDNzdJXJ45thgnnakd8hUALaBCkxSqoxyL4jxSbdiS2iobo2QzPYGmsJ6VJpcawSXM9XrrgDyzWTpr", "address_n": [0, 0]}], "signatures": ["", ""]}, "amount": "11099696"}], "outputs": [{"address": "n1iozfb1SY9tDj5vwaLtKJWZ6EgZrYpZej", "amount": "11089696", "script_type": "PAYTOADDRESS"}], "coin": "Testnet"}
```

For connect@7, still same invalid prev_hash error.

**Comment by szymonlesisz** [comment]
@yuriygeorge could you try it again with connect@7?

**Comment by yuriygeorge** [comment]
Nice, I'm no longer getting the invalid prevhash error, but the signatures are still different.
connect@7 inputs:
```javascript
{"inputs": [
{"address_n": [2147483693, 0, 0, 0], 
"prev_hash": "b42c658796927fb4d75aa7c5c404be78718c814b4fcd9a22a077a8c876a7240f", 
"prev_index": 0, 
"script_sig": "0001ff01ff4cad524c53ff043587cf0000000000000000006109a29836a5adfc1e03c0ec9f9e606109d9392670d8bcabdacdfa7ce9e48ed5028cb7707b6a0b73a27946c044f3d2ea9356e9b163986c07c22e299e93e16d45aa000000004c53ff043587cf02b114b63000000000d499aa3ddd978271b43979d84a38656b296177c08e1babfb4fdc15f59c4bfec4023b7830d36f197844b7203a9fab93afde0d2eb45aa98352e394c750280ec97e950000000052ae", 
"sequence": 4294967294, 
"script_type": "SPENDMULTISIG", 
"multisig": {"m": 2, "pubkeys": [
{"node": "tpubD6NzVbkrYhZ4XJeyzHmeBT7k3caJqz8JJgnFUCPmDv287qWcVm4Sq7av35EpbF5hjHMqwRykp3PYhjnrvqwfmvEzoafLJkjZdw8sP8kRCr3", "address_n": [0, 0]}, 
{"node": "tpubDBSkiQYQ3thN8VgYvtYHBUJR7KUJZvDNzdJXJ45thgnnakd8hUALaBCkxSqoxyL4jxSbdiS2iobo2QzPYGmsJ6VJpcawSXM9XrrgDyzWTpr", "address_n": [0, 0]}], 
"signatures": ["", ""]}, 
"amount": "11099696"}], 
"outputs": [{"address": "n1iozfb1SY9tDj5vwaLtKJWZ6EgZrYpZej", "amount": "11089696", "script_type": "PAYTOADDRESS"}], 
"coin": "Testnet", 
"locktime": 1483342}
```

Response from connect @ 7:
signature: 
```
304402207bbc96011398cacc4d96311230499bea4e2c01ae209499b37222dca7cbae2992022061e20104693934ada8fec857218c5ccc2ad3c62232bdf5792d8f3f7ee3c355c0
```
serializedTx:
```
01000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb400000000910047304402207bbc96011398cacc4d96311230499bea4e2c01ae209499b37222dca7cbae2992022061e20104693934ada8fec857218c5ccc2ad3c62232bdf5792d8f3f7ee3c355c001475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefeffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
```

For Electrum's python trezorlib:
signature:
```
3045022100914a6f2808bee5046c745292c33cfcb8016b9bfd4d8adf90d5614693267753c602201fe1e846861bb2ca73d332fc2a91e5958039ad0249d4bc43b97c450c8b15dc7f
```
serializedTx:
```
02000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb4000000009200483045022100914a6f2808bee5046c745292c33cfcb8016b9bfd4d8adf90d5614693267753c602201fe1e846861bb2ca73d332fc2a91e5958039ad0249d4bc43b97c450c8b15dc7f01475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefdffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
```

Oddly enough, the serializedTx output looks almost identical, except for the 2nd digit.
Also, I noticed that for Connect @ 7, the signature length is 140 characters, while for python trezor lib, the signature I get is 142.

**Comment by szymonlesisz** [comment]
i've decoded your serializedTx using: https://live.blockcypher.com/btc/decodetx/ and noticed that input sequence differs:
in connect@7 `4294967294` in electrum `4294967293`

**Comment by szymonlesisz** [comment]
and maybe signature sizes are different because electrum adds another field: `opt_in_rbf: true`

**Comment by matejcik** [comment]
The first byte is tx version. Does Connect also ignore the `version` field?

**Comment by matejcik** [comment]
also `opt_in_rbf` is caused by the sequence number being 0xFFFFFFFD (which is strictly less than 0xFFFFFFFE per [BIP-125](https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki)). Shouldn't Connect also be setting that value?

**Comment by yuriygeorge** [comment]
Yes, I see now that Electrum subtracts 1 from the sequence:
```python
txinputtype.sequence = txin.get('sequence', 0xffffffff - 1)
```
However, when I set sequence in Connect to match Python's (4294967293), I still get different signature:

connect@7 signature:
```
3045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa39870160
```
connect@7 serializedTx:
```
01000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb4000000009200483045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa3987016001475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefdffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
```
python sig/serializedTx: 
```
(see above)
```
I notice that Connect uses:
```
ver:1
```
but Python uses
```
ver:2
```

Electrum/python-trezorlib uses version 2 transactions, but Connect uses version 1. Maybe this is where the issue could be..

**Comment by matejcik** [comment]
> but Python uses
> 
> ```
> ver:2
> ```
> Electrum/python-trezorlib uses version 2 transactions, but Connect uses version 1. Maybe this is where the issue could be..

Python uses version 2 because you're specifying version 2 somewhere - see your `SignTx` object.
That might be Electrum's default? Trezor's built-in default is 1, which is what Connect seems to use.

**Comment by yuriygeorge** [comment]
Still, even when I change electrum's code to hardcode version 1, python returns this signature:
```
01000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb4000000009200483045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa3987016001475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefdffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
```

and serializedTx (which when loaded into https://live.blockcypher.com/btc/decodetx/ shows ver:1):
```
01000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb4000000009200483045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa3987016001475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefdffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
```

**Comment by matejcik** [comment]
@yuriygeorge your sequence numbers on the input are still different. note that in your connectv7 example you listed 429496729**4**, and in your python example you listed 429496729**3**

**Comment by yuriygeorge** [comment]
@matejcik you might be looking at an older post. I did re-run connectv7 with 429467293 (in a post above, quoted below), and the serializedTx then does then translate to the 4294967293 sequence when inserting it into https://live.blockcypher.com/btc/decodetx/:

> Yes, I see now that Electrum subtracts 1 from the sequence:
> 
> ```python
> txinputtype.sequence = txin.get('sequence', 0xffffffff - 1)
> ```
> 
> However, when I set sequence in Connect to match Python's (4294967293), I still get different signature:
> 
> connect@7 signature:
> 
> ```
> 3045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa39870160
> ```
> 
> connect@7 serializedTx:
> 
> ```
> 01000000010f24a776c8a877a0229acd4f4b818c7178be04c4c5a75ad7b47f929687652cb4000000009200483045022100f519029dc283e2a39d8c309cbfda1292eb567c26e0de2b8968c037e3ffc1e07b0220399b047ebbad51c2ae916835ac13d8733956f4bb6e6a25cbd8d46ffa3987016001475221022d8f900be868382e0914de78ee41c2a5e198270099e830abc63b8227ebe4f1bd2103ef9e4d0f9c7362a15389ccee86cbed23539d6382d03ee4f62d590fffe4244ec252aefdffffff012037a900000000001976a914dda09432c6566e364145be22809605dc5a015f3e88ac4ea21600
> ```

**Comment by szymonlesisz** [comment]
now, if you compare both signatures the only difference is in:

connect
```javascript
    "received": "2019-03-04T17:37:12.260182711Z", 
    "relayed_by": "54.226.13.27", 
```

electrum
```javascript
    "received": "2019-03-04T17:38:05.977014645Z", 
    "relayed_by": "3.94.208.97", 
```

which imho is legit

**Comment by szymonlesisz** [comment]
i'm just adding new, optional field `version` to connect where you can explicitly set it to whatever you want

**Comment by yuriygeorge** [comment]
That would be great!
Hardcoding electrum/python-trezor-lib to use version 1 doesn't seem to work. It may return the exact same serializedTx as connectv7, but when I go to update the new signature, the electrum code fails to locate the matching public key from the signature:

```python
signature = '304402207bbc96011398cacc4d96311230499bea4e2c01ae209499b37222dca7cbae2992022061e20104693934ada8fec857218c5ccc2ad3c62232bdf5792d8f3f7ee3c355c0'+'01'
tx_for_trezor.update_signatures([signature])

public_key = ecc.ECPubkey.from_sig_string(sig_string, recid, pre_hash)
#public key not found
```

I'm hoping that if I set ver:2 in trezor connect explicitly, then it will work.

**Comment by szymonlesisz** [comment]
Ok, so i've created a new branch for this fix:
https://github.com/trezor/connect/tree/fix/signTx-missing-params

@yuriygeorge could you test it locally if it solves this issue before we put it in production?

just add `"version": 2` to the params

**Comment by yuriygeorge** [comment]
Will do

**Comment by yuriygeorge** [comment]
It works! Same signature produced:
```
3045022100914a6f2808bee5046c745292c33cfcb8016b9bfd4d8adf90d5614693267753c602201fe1e846861bb2ca73d332fc2a91e5958039ad0249d4bc43b97c450c8b15dc7f
```
and confirmed that it works with Electrum, too. So, I guess the version number seemed to be the culprit!

Thank you very much!

**Comment by szymonlesisz** [comment]
Great, thanks for for cooperation!
