### ISSUE TITLE
Issue with NEM Trezor Wallet

### ISSUE THREAD

**Issue by j-mikhail** [trezor/connect#349]
Hello, I am having trouble getting the NEM Universal Client with Trezor Support v2.4.2 to connect to the Trezor servers. When I click on the Next button, and the Trezor Connect popup appears, it appears to hang at "Loading..."

Examining the debug console, I see this odd message:
```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://connect.trezor.io’) does not match the recipient window’s origin (‘https://connect.trezor.io’).
```

Not sure what to make of that. Thoughts?

**Comment by prusnak** [comment]
I suggest opening the issue in the NEM client repository.
