### ISSUE TITLE
How to sign/decode unsigned transaction

### ISSUE THREAD

**Issue by chris41188** [trezor/connect#35]
Hi

I am interested in using the sign api to sign an unsigned transaction
e.g.
0100000001bf1f87c5041063d8353f3d8e109fb11405456d7972c5f401308ced36eb9e8fea010000001976a914e1869fa1cec7741a502e7a5bd938ed8f5e354b5488acffffffff0200000000000000002e6a2c0b0b8cb664864cdf2ff70668595e63567b9d8ece36b2383513b6eeab7f1c15e70466593f13bb49618b8afe7079e93a00000000001976a914e1869fa1cec7741a502e7a5bd938ed8f5e354b5488ac00000000

Looking at the api I need to use inputs and outputs, 
TrezorConnect.signTx(inputs, outputs, function (result) {

Is there a way to decode this hex into compatible inputs and outputs for the TrezorConnect.signTx function?

**Comment by prusnak** [comment]
No. TREZOR needs to know which private key to use and this is not stored in the unsigned transaction.

**Comment by chris41188** [comment]
Thanks for the reply

So the unsigned transaction hex is a transaction containing coins from the trezors private keys

Actually I plan to send counterparty tokens to my trezor

Then create a transaction to spend those tokens using counterparty but I need trezor to sign that transaction
