### ISSUE TITLE
cardanoSignTransaction API params

### ISSUE THREAD

**Issue by shinsuny** [trezor/connect#350]
Found little bit inconsistency in `inputs` [parameter](https://github.com/trezor/connect/blob/develop/docs/methods/cardanoSignTransaction.md#params).

In [types](https://github.com/trezor/connect/blob/65b4a064125e5e65fb5010b0fd0b43a75d06238d/src/js/types/cardano.js#L58) :
```
type CardanoInput = {
    path: $Path,
    tx_hash: string,      // P1
    output_index: number, // P2
    type?: number,
}
```

but actual validation is done some [different parameter name](https://github.com/trezor/connect/blob/65b4a064125e5e65fb5010b0fd0b43a75d06238d/src/js/core/methods/CardanoSignTransaction.js#L39).
```
        const inputs: Array<CardanoTxInput> = payload.inputs.map(input => {
            validateParams(input, [
                { name: 'path', obligatory: true },
                { name: 'prev_hash', type: 'string', obligatory: true },   // P1
                { name: 'prev_index', type: 'number', obligatory: true },  // P2
                { name: 'type', type: 'number', obligatory: true },
            ]);
            return {
                address_n: validatePath(input.path, 5),
                prev_hash: input.prev_hash,
                prev_index: input.prev_index,
                type: input.type,
            };
        });
```

- P1 -> `tx_hash != prev_hash`
- P2 -> `output_index != prev_index`

**Comment by szymonlesisz** [comment]
i will fix that, thanks!
