### ISSUE TITLE
Need to Be Able to Pass Prev-Tx Parameter to Trezor Connect Similar to Python Trezorlib

### ISSUE THREAD

**Issue by yuriygeorge** [trezor/connect#351]
I notice that the python trezorlib library has ability to override/and pass your own prev_txes data structure for non-segwit transactions into the signTransaction method.

I really really need this in Trezor Connect JS version, too. The reason why is that I pre-generate a dependent transaction, that is used as an input into the transaction I sign with the Trezor. However, this pre-generated transaction is **not yet broadcasted** to the network - I need to pass it manually.

Since, I can't pass my own prev_txes, I get this error.

ERROR: Tx not found, txid 9170ec1688c98621946321d53e52e391dd5b3d511b58ad316795fd547a750b0e: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.

I'm currently using the **origin/fix/signTx-missing-params** branch, (since I need to also use/pass the **version** parameter). Could someone please add this additional "prev_tx" parameter in there? Thank you in advance

**Comment by szymonlesisz** [comment]
Hi,
I've already add `refTxs` param In branch `fix/signTx-missing-params` where we've fixing `network` parameter 

Commit here:
https://github.com/trezor/connect/commit/258a1dd3e7c693be40411d20ec7f484d0178a579

**Comment by yuriygeorge** [comment]
Very well, I tested it using the extra refTxs parameter, and everything seems to be working fine. Thanks.
```javascript
{
   "inputs":[
      {
         "address_n":[
            2147483693,
            0,
            1,
            0
         ],
         "prev_hash":"4e99c23373a44773555d51b8f036c2781344d42168a6c08d60a8da97ad6c3e20",
         "prev_index":1,
         "script_sig":"0001ff01ff4cad524c53ff043587cf02b114b63000000000d499aa3ddd978271b43979d84a38656b296177c08e1babfb4fdc15f59c4bfec4023b7830d36f197844b7203a9fab93afde0d2eb45aa98352e394c750280ec97e95010000004c53ff043587cf0000000000000000006109a29836a5adfc1e03c0ec9f9e606109d9392670d8bcabdacdfa7ce9e48ed5028cb7707b6a0b73a27946c044f3d2ea9356e9b163986c07c22e299e93e16d45aa0100000052ae",
         "sequence":4294967293,
         "script_type":"SPENDMULTISIG",
         "multisig":{
            "m":2,
            "pubkeys":[
               {
                  "node":"tpubDBSkiQYQ3thN8VgYvtYHBUJR7KUJZvDNzdJXJ45thgnnakd8hUALaBCkxSqoxyL4jxSbdiS2iobo2QzPYGmsJ6VJpcawSXM9XrrgDyzWTpr",
                  "address_n":[
                     1,
                     0
                  ]
               },
               {
                  "node":"tpubD6NzVbkrYhZ4XJeyzHmeBT7k3caJqz8JJgnFUCPmDv287qWcVm4Sq7av35EpbF5hjHMqwRykp3PYhjnrvqwfmvEzoafLJkjZdw8sP8kRCr3",
                  "address_n":[
                     1,
                     0
                  ]
               }
            ],
            "signatures":[
               "",
               ""
            ]
         },
         "amount":"None"
      }
   ],
   "outputs":[
      {
         "address":"n1iozfb1SY9tDj5vwaLtKJWZ6EgZrYpZej",
         "amount":"5990000",
         "script_type":"PAYTOADDRESS"
      }
   ],
   "coin":"Testnet",
   "locktime":1486453,
   "refTxs":[
      {
         "hash":"4e99c23373a44773555d51b8f036c2781344d42168a6c08d60a8da97ad6c3e20",
         "version":2,
         "lock_time":1484293,
         "inputs":[
            {
               "address_n":[

               ],
               "prev_hash":"c41dee56ce03c3cdd17b26cbc1a81b6e458d0f14f0cb3c74e3e3de3759823b3a",
               "prev_index":0,
               "script_sig":"00483045022100e38ffd4bc3c8ab4f252408eb3e7048bb971525cceba7895545bf608eb8e41f17022042b6631e577f124a8c0db377e1ccc504e9a35482b4766121bbf6131bdfb1174101473044022059f5fed4c6bbe50fc5ef191ffbf77584175fe5b958ff3e6b6df9f4c6936c7a0802204e12792c85fe7f531d3c8049f3c8429585d94c5ca33565db0af053d4d00ac84201475221028b083881dc2ef42b7696bd220f147c9a16a59a4c8d66b0263b5c747ef8dc4ed02102dc2c0761d847ee2dd4bf4d4b8afc573c7f7f0448b71b3b05e05051e833fb3afa52ae",
               "sequence":4294967293
            }
         ],
         "bin_outputs":[
            {
               "amount":4990000,
               "script_pubkey":"76a914ed22b2701eb1d96242915f4d21e04b0086dd239388ac"
            },
            {
               "amount":6000000,
               "script_pubkey":"a9143e8ac7f3fa2967198be897a16c2e6bf98e993dfd87"
            }
         ]
      }
   ],
   "version":2
}
```

**Comment by yuriygeorge** [comment]
Hi, will this be merged into v7, or v8? For now, I must run my own local server to access this feature, correct? Can you let me know what plans would be to merge this into v7 or v8 so then I can connect to trezor.io servers? Thanks

**Comment by szymonlesisz** [comment]
It will be released today/tomorrow. I'll let you know here

**Comment by yuriygeorge** [comment]
Thanks, on a separate, related issue, I notice that the custom "locktime" field is not displayed on the Trezor display screen when set. How can the user be certain that the locktime field was actually set? Is it possible in the near future to make Trezor display the locktime field if it is set? Otherwise, seems to defeat the purpose.

**Comment by szymonlesisz** [comment]
This is not related to connect, it's a firmware issue so you should ask this question in here: https://github.com/trezor/trezor-core

**Comment by szymonlesisz** [comment]
7.0.2 released

**Comment by yuriygeorge** [comment]
Great! Thanks, verified!
