### ISSUE TITLE
requestLogin() with passphrase?

### ISSUE THREAD

**Issue by pruflyos** [trezor/connect#353]
The documentation of https://github.com/trezor/connect/docs/methods/requestLogin.md kind of suggests that you can set the param `useEmptyPassphrase` to `false`. I guess this should cause the flow to ask for an additional passphrase on login, right? 
Well it doesn't seem to work right now. Even with `useEmptyPassphrase: false` no passphrase is asked during `requestLogin`.

**Comment by szymonlesisz** [comment]
`requestLogin` is designed to be paswordless, same as `cipherKeyValue`. Yes, you are right that docs could be misleading with this param so i've updated it. 
Thanks
