### ISSUE TITLE
requestLogin() with multiple domains

### ISSUE THREAD

**Issue by pruflyos** [trezor/connect#355]
As far as I understand `TrezorConnect.requestLogin()` uses the `origin` header to derive the public key and signature. So if my application is available on multiple domains the same user (or Trezor device) will end up with different identities depending on which domain he uses to access the application. 

Or even if I just have a single domain and I want to migrate to another domain, user's won't be able to access their accounts anymore. Is there a migration strategy?

Is there a setting that something else than the origin header can be used to derive the identity?

**Comment by szymonlesisz** [comment]
Since origin and public key are strictly combined there is no migration strategy for this case, same like in any other U2F
