### ISSUE TITLE
MultisigRedeemScriptType with external pubkeys

### ISSUE THREAD

**Issue by oti-dev** [trezor/connect#362]
Hello,

How do I construct MultisigRedeemScriptType.pubkeys out of external pubkeys that do not come from an HD wallet? This issue has already been posted before, and this answer was supposedly a solution:

>You can always generate XPUB (node) from the public key and use empty address path.

_Originally posted by @prusnak in https://github.com/trezor/connect/issues/311#issuecomment-459091206_

I don't understand how to do this, though. How do I generate xpub out of an arbitrary pubkey?

**Comment by szymonlesisz** [comment]
TrezorConnect will convert xpubs to `HDNode` for you [here](https://github.com/trezor/connect/blob/develop/src/js/utils/hdnode.js#L112-L121)
So your params should look like:
```javascript
pubkeys: [
    {node: 'your-xpub', address_n: [path-to-your-xpub]},
    {node: 'somebody-else-xpub', address_n: [1 - doesn't matter, since it's not your xpub Trezor will not found it anyway]},
    {node: 'somebody-else-xpub', address_n: [1 - doesn't matter, since it's not your xpub Trezor will not found it anyway]}
],
```

**Comment by oti-dev** [comment]
The function you mentioned also expects an xpub as a parameter, which I don't have. But what if I use bitcoin core and I don't have an xpub? I have a regular public key, pregenerated from bitcoin core. 

I have a pubkey like this:
023a94c415f8dc012ff9b71780f21d14f005db7ee276646c2e9e788ddf709649fd

In Bitcoin core I would've been able to use it for multisig transaction. In Trezor connect I'm required to provide an xpub and address_n, which I assume are used just to get the key I already have and make redeemScript out of it. I just need a workaround to convert the pubkey in aforementioned format to the format that is expected by TrezorConnect.signTransaction input parameters multisig attribute.

**Comment by prusnak** [comment]
You can convert any pubkey into the xpub. See https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Serialization_format

* set version bytes correctly (0x0488b21e)
* set depth to 0x00
* set fingerprint to 0x00000000
* set child number to 0x00000000
* set chain code to 0x00 x 32
* set public key to your public key

So your xpub in hex will look like this:

`0488b21e0000000000000000000000000000000000000000000000000000000000000000000000000000000000023a94c415f8dc012ff9b71780f21d14f005db7ee276646c2e9e788ddf709649fd`

Serialize the resulting 78 bytes to xpub via Base58 encoding
