### ISSUE TITLE
LoadDevice doesn't seem to work

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/connect#363]
Against `v7.0.1`, I'm getting:

```
TypeError: trezor_connect_1.default.loadDevice is not a function
```

Is there some mode I need to put TrezorConnect into that tells it I know what I'm doing and enables `loadDevice()`? I'd like to use it for regression testing a library we're writing.

**Comment by szymonlesisz** [comment]
loadDevice is not implemented yet, but we are working on implementation of all device management methods here:
https://github.com/trezor/connect/pull/320

**Comment by keepkeyjon** [comment]
oh, wonderful. thank you!
