### ISSUE TITLE
Trezor Connect Support for Ravencoin (RVN)

### ISSUE THREAD

**Issue by MangoFarmAssets** [trezor/connect#364]
We have a bip44 wallet for Ravencoin (asset aware) and are integrating Trezor using Trezor Connect.  Connect is functioning and we are able to load the XPUB from the device for watch-only purposes.  

We have run into an issue when signing a RVN transaction.  RVN is supported in the device firmware, and the json is in the bitcoin defs (https://github.com/trezor/trezor-common/blob/master/defs/bitcoin/ravencoin.json), but RVN is not in the support.json file for Trezor Connect (https://github.com/trezor/trezor-common/blob/master/defs/support.json) - this resulted in a coin not found error when signing the TX.  

We would like to request RVN support in Trezor Connect.  Any assistance would be appreciated.

**Comment by prusnak** [comment]
@szymonlesisz Is it enough to just add `"bitcoin:RVN": true,` into `connect` tree of `support.json` and rebuilding/redeploying connect?

**Comment by prusnak** [comment]
@MangoFarmAssets Do what I suggest above in your locally deployed Connect.
 Then try whether SignTransaction, PushTransaction, ComposeTransaction calls work for you.

If everything works, please open a pull request to trezor-common where you submit the change mentioned above.

**Comment by MangoFarmAssets** [comment]
Will do @prusnak.  Thanks very much.
