### ISSUE TITLE
Allow signTransaction if no backend is defined

### ISSUE THREAD

**Issue by prusnak** [trezor/connect#369]
We should allow the coins with no backends defined in their JSON because they still can be used via `signTransaction` if the caller provides the necessary info.

**Comment by AlexITC** [comment]
From what I see on [SignTransaction.js](https://github.com/trezor/connect/blob/develop/src/js/core/methods/SignTransaction.js#L152), this is already supported, isn't it?

**Comment by szymonlesisz** [comment]
already implemented here https://github.com/trezor/connect/commit/b0ec953bae95ff0b454cd6fc9050308783c96a92
