### ISSUE TITLE
Property 'manifest' does not exist on type 'typeof TrezorConnect

### ISSUE THREAD

**Issue by dwolfgram** [trezor/connect#373]
Hello!

I just updated to v7.0.2 and the required manifest function does not exist of type TrezorConnect. I tried to `npm install @types/trezor-connect@latest` but it is a v6 types. Any guidance on this? Thanks :)

**Comment by szymonlesisz** [comment]
Hi,
We are not maintaining @types/trezor-connect those types are created by someone else for version 6.
See [this thread](https://github.com/trezor/connect/issues/301)
