### ISSUE TITLE
Trezor icons too small

### ISSUE THREAD

**Issue by bosomt** [trezor/connect#375]
Trezor icons are too small and it's hard to distinguish if it's model One or model T

![Screenshot_20190408_103654](https://user-images.githubusercontent.com/31506317/55710153-44066580-59ea-11e9-885c-cf6896ea4ffc.png)

**Comment by tsusanka** [comment]
Will be done as part of the Connect pop up redesign. Being tracked in https://github.com/trezor/trezor-suite/issues/4363.
