### ISSUE TITLE
Monero Support

### ISSUE THREAD

**Issue by dternyak** [trezor/connect#376]
With the addition of Monero to the Monero GUI for Trezor, it'd be great if this repo could be updated with Monero support.

**Comment by prusnak** [comment]
This is not planned at the moment. It does not make sense to have a web wallet for privacy oriented coin.

**Comment by dternyak** [comment]
@prusnak Thanks for the reply. Just to play devil's advocate, a web based wallet does not necessarily imply privacy risks if that's the main reason for closing this issue.

MyMonero (which was started by Ricardo Spagni) offers a web based wallet for many years now. 

With https://github.com/monero-project/monero/pull/4139, users should be able to run their own light wallet infra, and a neat UX would be to interact with your Trezor via your browser that's connected to your own light wallet server. Even in the case where you interact with a centralized service, the choice to share your view keys with a single counterparty does not necessarily create a lot of risk for privacy, as your transactions are still private on-chain.

I hope you'll consider adding monero support at a future time!
