### ISSUE TITLE
Undefined error with Connect/RVN integration

### ISSUE THREAD

**Issue by MangoFarmAssets** [trezor/connect#379]
When attempting to sign a Ravencoin send transaction (with an included Reference tx) using Trezor Connect, the following error is returned with an undefined error code: ".TxAck.TransactionType.TxInputType#address is not a field: undefined".

The following object is what is being submitted to the signTransaction function: 
{inputs:[{address:"RQnwRPQdDeoNLLsJCCTZiE9SRxREppqaaQ",prev_index:0,prev_hash:"40fedb3604b360d294a3e1e0313bb1b45f49cb5db79de3a5df88139690b98e2d"}],
outputs:[{address:"RXapTZWPyRGakjCbYDXe9SXodsQ6GxSoZF",amount:"500000000",script_type:"P2PKH"},{address:"RHiSKcze4gyxhUVDzT84MnLaNF2Y3seK3L",amount:"499000000","script_type":"P2PKH"}],
refTxs:
[{hash:"40fedb3604b360d294a3e1e0313bb1b45f49cb5db79de3a5df88139690b98e2d",
inputs:[{prev_hash:"aa3b62a32c3e40fc9fccb199a54a80c418c0ea05e0e77f2679decf3168dcd957",prev_index:2,script_sig:"473044022031ff611af9cdf06bedf29b2c445fa0413835eec2293cc5d08e9bdd85b8110f750220571d9a47219838f8cd41f9eefe96867ae11483154f331521099c923aa75062610121029ffab7557014b15bfe300c2050667d5ed92735b20e89ee07ba3f71a190ceda05",sequence:4294967295}],
bin_outputs:[{amount:1000000000,script_pubkey:"76a914aa2a2156f556a20e8d76a96ad101292bd30c2f8588ac"},{amount:20190800000,script_pubkey:"76a9144139edbb6a1139c0878856445901d43a0cb90dbe88ac"}],lock_time:0,version:2}],coin:"rvn"}

**Comment by szymonlesisz** [comment]
This error is correct.
there is no `address` field in [transaction input](https://github.com/trezor/connect/blob/develop/src/js/types/params.js#L124-L136) 
You should to use `address_n` where you specify path for account which is a "owner" of this utxo

**Comment by MangoFarmAssets** [comment]
Thank you!
