### ISSUE TITLE
Issue with Polis extended Pub and Priv prefix

### ISSUE THREAD

**Issue by eabz** [trezor/connect#380]
Hello, 
I am testing the Polis integration over connect. 
While I get the extendedPubKey data from trezor, I am getting a xpub prefix, double checked integration on trezor-common and is correctly defined: https://github.com/satoshilabs/slips/blob/master/slip-0132.md#registered-hd-version-bytes

Can I get a workaround to get this fixed?

Greetings.

**Comment by prusnak** [comment]
You swapped xprv_magic and xpub_magic values in the json. Please send a fix.

**Comment by eabz** [comment]
Thanks
