### ISSUE TITLE
Stellarport fails singing some dummy transaction

### ISSUE THREAD

**Issue by tsusanka** [trezor/connect#382]
From email:

Looks like there is some issue with the new firmware signing some transactions. Is there any way you could test it out at stellarport.io ? You can try going to Wallet > Profile and setting a nickname. In order to set a nickname, it asks you to sign a dummy transaction and gets stuck with an error of "Illegal Buffer".

---------

I'm not 100% sure this is a firmware issue, this might caused by incorrect use of Connect. Will investigate.

**Comment by prusnak** [comment]
@szymonlesisz can you have a look too?

**Comment by szymonlesisz** [comment]
i'll have a look

**Comment by szymonlesisz** [comment]
According to [protobuf messages](https://github.com/trezor/connect/blob/develop/src/data/messages/messages.json#L7989) value should be sent as bytes, which in this case means `Buffer.toString('hex')`. Value in plain base64 will not be accepted by protobuf transalation and this is the place in code where it's failing

Fix:
`Buffer.from("rflvVyDLDyNg6SiuxXJ87SG57+SsFINDKOt1nty2w3uXwVE20Jt7wwnAz6eLUWBs8xMIsBthn4jRn+2aec4jog==", 'base64').toString('hex')`

**Comment by prusnak** [comment]
@istrau2 please fix your code according to the suggestion above

**Comment by istrau2** [comment]
@prusnak @szymonlesisz @tsusanka 
We are now passing the values in `hex` to connect and there are no errors. However, the signature seems to be incorrect. I can't figure out if this is an issue with the data that I am passing to connect or a bug in connect or the firmware.

Here is an example case:

I pass the following transaction to connect:
`{"source":"GD7SV72HJSL2VMJAEN4LYX3VXIFHAZ4FJDVBPTLEERTIWN3TWN2KYO7L","fee":100,"sequence":"0","timeBounds":{"minTime":"1555439731","maxTime":"1555440031"},"operations":[{"source":"GDZPDP7JQMR66FOUN7EOLXRYOICHFDIBEVYLL6ISXA7P2HTNIP775K7B","type":"manageData","name":"5374656C6C6172706F72742061757468","value":"990AFD8BB15ABA507522D597A6A9DFDF3F4029C9A2A51CE921CBFDEC58D187E29D80D26B7FE332BDF324B20D61520A148866D93475A2C01A06757571825EB178"}],"memo":{"type":0}}`

and receive the following signature in the response:
`b871f4a7149fc8aa9efa9c46d77760cbdad3af25f4a58671f86272b7d246de772d3db9351a66e2145a0c5ebcf861d3d413c36ae445de0eab5f66198655c79601`

apparently, this signature is incorrect.

Am I doing something wrong?

If you would like to test, please go to stellarport.io and try to change the nickname with a Trezor on Wallet > Profile.

**Comment by prusnak** [comment]
Why do you think the signature is incorrect? What format are you expecting?

**Comment by istrau2** [comment]
@prusnak 

Because of the following is false:
```
const keypair = StellarSdk.Keypair.fromPublicKey("GDZPDP7JQMR66FOUN7EOLXRYOICHFDIBEVYLL6ISXA7P2HTNIP775K7B");
const verified = keypair.verify(transaction.hash(), transaction.signatures[i].signature())
```
We use the code above to verify all transactions that pass through Stellarport. All the other ones are fine but this one is producing a false result.

**Comment by prusnak** [comment]
That's because you are AGAIN using hex representation used by Protobuf in the context which expects some native Stellar encoding. You are a developer, read the documentation and understand it. You cannot expect us to do all the homework for you.

So once again: you receive the signature in hex form. Convert it to whatever format required by StellarSdk. Which format? This is written in the Stellar documentation, which I recommend you to read.

**Comment by istrau2** [comment]
@prusnak No, I don't think that is it. `transaction` above is a well formed StellarSdk transaction. I think I probably communicated the issue badly above. I left out some code for the sake of brevity:

```
const result = await TrezorConnect.stellarSignTransaction({
            path: 'm/' + bip32Path,
            networkPassphrase: window.stellarport.networkMode === 'public' ? 'Public Global Stellar Network ; September 2015' : 'Test SDF Network ; September 2015',
            transaction: jsonTx
        });

// convert hex string returned from trezor into binary
let signature = this._hexToUint8Arr(result.payload.signature);

// get the address that the trezor signed with.
let signedAddress = StellarSdk.StrKey.encodeEd25519PublicKey(this._hexToUint8Arr(result.payload.publicKey));

// format the signature for the stellar sdk
let keyPair = StellarSdk.Keypair.fromPublicKey(signedAddress);
let hint = keyPair.signatureHint();

// second signature added
transaction.signatures.push(new StellarSdk.xdr.DecoratedSignature({hint, signature}));

// now try and verify the signature against the keypair
const verified = keyPair.verify(transaction.hash(), transaction.signatures[1].signature());

//verified is false but why?
```

All other Trezor signatures are working fine with the code above. It is only this specific transaction that isn't passing. Here are some of the features of the transaction that may be causing this:

- The transaction contains a manageData operation
- The operation source account is different from the transaction source account
- The transaction contains 2 signatures (i.e. the signature that trezor connect is producing is being attached to the transaction as its second signature, it already had one)

Thanks again.

**Comment by tsusanka** [comment]
Could you try on Trezor One as well? If the signature differs or not

**Comment by istrau2** [comment]
@tsusanka I am testing on the Trezor One. I don't have a model T to test on currently.

**Comment by tsusanka** [comment]
You can test using an emulator, see here https://github.com/trezor/trezor-firmware/blob/master/core/docs/emulator.md

**Comment by istrau2** [comment]
@tsusanka Yes, unfortunately I am on windows and I have to spin up a VM to test. I will test on emulator after ensuring that it works on the a real Trezor One first. Currently, I am experiencing the issue above on the real Trezor One. Can we address that?

**Comment by MisterTicot** [comment]
@istrau2 Can you check the displayed information on your Trezor device for timebounds?

**Comment by istrau2** [comment]
Hi @MisterTicot. Thanks for reporting. Can you be more specific on what issue you are seeing. In other words, what operation(s) are you submitting and what timebounds are you seeing (or not seeing)? What were you expecting to see and what appears to be incorrect?

Thanks.

**Comment by MisterTicot** [comment]
@istrau2 
I'm not reporting an issue
I was suggesting that your transaction from 16 April failed because Trezor doesn't handle timebound properly. You asked about it:

> apparently, this signature is incorrect.
> 
> Am I doing something wrong?

I think you can confirm it by trying to sign the transaction again, and checking the timebound information displayed on the device.

**Comment by istrau2** [comment]
@MisterTicot Ah, I see. The original issue is from many months ago. I don't remember how I resolved it but I did =)
