### ISSUE TITLE
trezor-connect@7.0.2-electron.4 issue

### ISSUE THREAD

**Issue by Gabriel-2010** [trezor/connect#383]
I am trying to integrate trezor connect with electron. I have npm install trezor-connect@7.0.2-electron.4, but when I call TrezorConnect.getAddress, if failed with "Uncaught TypeError: Cannot read property 'handleMessage' of undefined" in iframe.js:78

Here is my code:
  getAddresses = async () => {
    var TrezorConnect = require('trezor-connect').default;
    TrezorConnect.manifest({
      email: '***@***.org',
      appUrl: 'https://github.com/***'
    })
    const result = await TrezorConnect.getAddress({
      path: "m/49'/0'/0'/0/2",
      coin: "btc"
    });
    console.log(result);
  }

**Comment by Gabriel-2010** [comment]
I followed the demo "https://github.com/szymonlesisz/trezor-connect-electron-boilerplate.git" and fixed this issue.  The solution is using "https://sisyfos.trezor.io/connect-electron/" instead of "https://connect.trezor.io/7/trezor-connect.js". Although I don't know the reason, it is working now.

**Comment by szymonlesisz** [comment]
Sorry i didn't managed to respond on time.
This branch is not released to public yet, changes made there are not compatible with endpoint hosted on `connect.trezor.io/7` that's why you need to use endpoint on `sisyfos.trezor.io/connect-electron` which is a playground/test environment for connect.
Therefore i'm warning you to not use this endpoint for production builds

**Comment by Gabriel-2010** [comment]
@szymonlesisz 
Thanks for your reply. If I want to integrate trezor-connect into electron for production builds, how can I do? Waiting for a new release or something else I didn't know? Many Thanks.

**Comment by szymonlesisz** [comment]
yes, wait for official release of version 8, it will be out soon

**Comment by Gabriel-2010** [comment]
> yes, wait for official release of version 8, it will be out soon

Sounds great. Thanks.
