### ISSUE TITLE
What is Stellar result.publicKey?

### ISSUE THREAD

**Issue by istrau2** [trezor/connect#385]
I am getting the following response from `stellarSignTransaction`:
{
   id: 2,
   result: "success",
   {
        payload: {signature: "...", publicKey: "f2f1bfe98323ef15d46fc8e5de387204728d012570b5f912b83efd1e6d43fffe"}
    }
}
in this case, what is `publicKey`?

I was testing with the following trezor public key: `GDZPDP7JQMR66FOUN7EOLXRYOICHFDIBEVYLL6ISXA7P2HTNIP775K7B`. How do I get `GDZPDP7JQMR66FOUN7EOLXRYOICHFDIBEVYLL6ISXA7P2HTNIP775K7B` from `f2f1bfe98323ef15d46fc8e5de387204728d012570b5f912b83efd1e6d43fffe`?

Thanks.

**Comment by prusnak** [comment]
I can give you this code, but if you don't understand it, you need to look into Stellar documentation how to convert public key to address:

https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/stellar/helpers.py#L19-L26
