### ISSUE TITLE
cardanoGetPublicKey method   return "Forbidden key path"

### ISSUE THREAD

**Issue by bitcodernull** [trezor/connect#388]
TrezorConnect.cardanoGetPublicKey({path:"m/44'/1729'/1'", showOnTrezor : false})

return :

code: "Failure_DataError"
error: "Forbidden key path"

------
Maybe i miss something , how to resolve it
thanks

**Comment by refi93** [comment]
Cardano's coin index is 1815', not 1729'. 1729' is Tezos:  https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by bitcodernull** [comment]
thanks
i  change the path, it works


On trezon, should path be in accordance with the bip44 specification?

I tested it, TrezorConnect.getPublicKey can make a non-compliant path, such as m/0/0/0

Cardano must meet the specifications?

**Comment by prusnak** [comment]
Yes
