### ISSUE TITLE
On trezon, should path must be in accordance with the bip44 specification?

### ISSUE THREAD

**Issue by bitcodernull** [trezor/connect#389]
On trezon, should path must be in accordance with the bip44 specification?

I have tested it, TrezorConnect.getPublicKey can make a non-compliant path, such as "m/0/0/0" or "m".   using path "m", i can get the root xpub for secpk1, it is great.
Cardano/stellar path must meet the specifications?

---------------
i want to get root xpub , then use the same path to derivative child xpubs for different coin， so i can get the same address for some different coins, such as eth and etc. then when other people send me the coins, they will be not easy to make mistakes on address .

_Originally posted by @bitcodernull in https://github.com/trezor/connect/issues/388#issuecomment-484740023_

**Comment by prusnak** [comment]
Yes
