### ISSUE TITLE
Fee 0.199  TEST is unexpectedly high, Send anyway

### ISSUE THREAD

**Issue by ribuluo000** [trezor/connect#390]
When I call the function
```
  const signTransaction = async (accountInfo) => {
    const item = accountInfo.payload.utxo[accountInfo.payload.utxo.length-1];
    const prev_index = item.index;
    const prev_hash = item.transactionHash;
    const params = {
      inputs: [
        {
            address_n: [(44 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 0],
            prev_index,
            prev_hash,
        }
      ],
      outputs: [
          {
              address_n: [(44 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 1],
              amount: '10000',
              script_type: 'PAYTOADDRESS',
          },
           {
              address: 'mwcVgjQTWDiph86DJpCPjuudwBbSahME7P',
              amount: '18899000',
              script_type: 'PAYTOADDRESS',
          }
      ],
      coin: 'testnet'
    };
    const result = await TrezorConnect.signTransaction(params);
    console.log('signTransaction', result)
  
    return result;
  
  };

```

I got the content show on my trezor : 
```
Fee 0.199  TEST is unexpectedly high, Send anyway

```
the 0.199 is all my balance, and than I click the cancel button.

Now I have these problems:
How can I set my fee?
How can I get the `params` used in `TrezorConnect.signTransaction(params)` correctly, and 
how can I get the `inputs`, `address_n`,`prev_index`,`prev_hash`,`outputs` and more?
Thanks!

**Comment by ribuluo000** [comment]
Is there any other document about `TrezorConnect.signTransaction(params)`?
I found this document below, but I coundn't understand every field in this document.
```
https://github.com/trezor/connect/blob/develop/docs/methods/signTransaction.md
```

**Comment by ribuluo000** [comment]
I found prev_hash change the Fee number...
When the prev_hash is `68bc0bba65cefdc43d5e00ddce10441a1b642980ea9faf487a0932389a3bcb4c` the Fee is very high.

When the prev_hash is `9bf451983e69f3e285caff7b789123c0ac56e438fad36e7b4565583317ab6dfd` the Fee is 0.002- amount.
What should I do, to get or set a nomal Fee?

**Comment by prusnak** [comment]
You do not set the fee. It is set implicitly. The fee is everything you don't spend.

**Comment by szymonlesisz** [comment]
for example:
your input has value 100
you want to spend 5 to some address, and get rest to your change address.
then:
``` javascript
outputs: [
          {
              address_n: [(44 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 1],
              amount: '94',
              script_type: 'PAYTOADDRESS',
          },
           {
              address: 'mwcVgjQTWDiph86DJpCPjuudwBbSahME7P',
              amount: '5',
              script_type: 'PAYTOADDRESS',
          }
      ],
```
In this case fee is '1' (100 - 5 - 94)


Btw, you've set bitcoin in derivation path, it should be :
```
address_n: [(44 | 0x80000000) >>> 0, (1 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 1],
```

**Comment by szymonlesisz** [comment]
alternatively, you can use [ComposeTransaction](https://github.com/trezor/connect/blob/develop/docs/methods/composeTransaction.md) method where you don't have to worry about utxos and you are able to set custom fee

**Comment by ribuluo000** [comment]
> alternatively, you can use [ComposeTransaction](https://github.com/trezor/connect/blob/develop/docs/methods/composeTransaction.md) method where you don't have to worry about utxos and you are able to set custom fee

I want to deal with utxos, but I don't know how to do. Is there any examples? Thanks! @szymonlesisz

**Comment by prusnak** [comment]
https://trezor.github.io/connect-explorer/#/composetx

**Comment by ribuluo000** [comment]
I want to use 

```
TrezorConnect.signTransaction({
  "coin": "test",
  "inputs": "[{
    address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 1, 0],
    amount: "123456789",
    prev_index: 0,
    prev_hash: "20912f98ea3ed849042efed0fdac8cb4fc301961c5988cba56902d8ffb61c337",
    script_type: "SPENDP2SHWITNESS"
}]",
  "outputs": "[{
    address: "mwcVgjQTWDiph86DJpCPjuudwBbSahME7P",
    amount: "12300000",
    script_type: "PAYTOADDRESS"
},
{
    address_n: [49 | 0x80000000, 1 | 0x80000000, 0 | 0x80000000, 1, 0],
    script_type: "PAYTOP2SHWITNESS",
    amount: Number(123456789 - 11000 - 12300000).toString(),
}]",
  "push": true
})
```

But I got this error.

![image](https://user-images.githubusercontent.com/9551756/56861753-9aa60480-69d6-11e9-9a1b-7bbf2c1b67f7.png)

**Comment by ribuluo000** [comment]
Is there any document about TrezorConnect.signTransaction?

> Is there any other document about `TrezorConnect.signTransaction(params)`?
> I found this document below, but I coundn't understand every field in this document.
> 
> ```
> https://github.com/trezor/connect/blob/develop/docs/methods/signTransaction.md
> ```

**Comment by ribuluo000** [comment]
相关问题以及example 请看以下链接
https://github.com/trezor/connect/issues/391
