### ISSUE TITLE
Port 21325 net::ERR_CONNECTION_REFUSED in Electron

### ISSUE THREAD

**Issue by JasonHJ** [trezor/connect#392]
Hi all:
When I connected to trezor, it would popup a window and then print a error like :
'POST http://127.0.0.1:21325/ net::ERR_CONNECTION_REFUSED'.
It works on my Mac, and wrong on my ubuntu virtual machines.

Does anybody ever had this problem?

**Comment by prusnak** [comment]
Don't you have a firewall running the Ubuntu VM?

**Comment by JasonHJ** [comment]
Hi @prusnak 
The UFW service has been turned off

**Comment by szymonlesisz** [comment]
did you a set proper origin to http request?

https://github.com/szymonlesisz/trezor-connect-electron-boilerplate/blob/master/src/electron.js#L58-L64

**Comment by Gabriel-2010** [comment]
> did you a set proper origin to http request?
> 
> https://github.com/szymonlesisz/trezor-connect-electron-boilerplate/blob/master/src/electron.js#L58-L64

I met the same issue. I also tried "trezor-connect-electron-boilerplate" by following steps:
```
git clone https://github.com/szymonlesisz/trezor-connect-electron-boilerplate.git
cd trezor-connect-electron-boilerplate
npm install
npm run dev

```
The console shows "POST http://127.0.0.1:21325/ net::ERR_CONNECTION_REFUSED.
The GUI shows "Install Bridge" button. When click it, nothing happened.

I am sure Ubuntu VM's firewall is disabled.
```
sudo ufw status
Status: inactive

sudo iptables -L -nChain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination       
```

**Comment by Gabriel-2010** [comment]
I found the solution. It is working after I installed trezor bridge from trezor.io.
