### ISSUE TITLE
Feature request: Ability to set timeout for potentially long running methods

### ISSUE THREAD

**Issue by slowbackspace** [trezor/connect#394]
eg `blockchainSubscribe`

**Comment by keraf** [comment]
A global interaction timeout has been implemented but it would be great to have an optional per method timeout parameter. Tagging as enhancement.

**Comment by tsusanka** [comment]
I think global interaction timeout is great and enough for now? And as this issue is 3 years old it seems we do not need it at the moment. Please reopen if that is not the case.
