### ISSUE TITLE
fork of bitcoin but 10 decimals satoshis instead of 8 decimals

### ISSUE THREAD

**Issue by maulikvora** [trezor/connect#395]
We have already Flashcoin supprted by Trezor Connect, which is a clone of Bitcoin.

We are facing a problem related to Satoshi decimals.
Generally Bitcoin and its Clones have 
1 BTC = 100 000 000 Satoshis  (8 Decimals)
1 LTC = 100 000 000 Litoshis. (8 Decimals)

But for FLASH,
its, 1 FLASH = 10 000 000 000 Satoshis (10 Decimals)

But Trezor firmware considers it 8 Decimals always and its showing different amounts on User Interface, for eg. if we are transferring 1 FLASH, it shows 100 FLASH to user.

So, wanted to see if there is any setting/parameter, we need to change to consider FLASH as 10 decimal Satoshi instead of 8 Decimal regular Satoshi

Thanks in Advance.

**Comment by keepkeyjon** [comment]
It's hardcoded to 8 in the firmware: https://github.com/trezor/trezor-firmware/blob/236ca1ae830d3c0b7fd9755a1286141484e0b567/legacy/firmware/layout2.c#L38 You'd have to make it read from the coin table instead.
