### ISSUE TITLE
Supported Coins List

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/connect#398]
I'd like to build a compatibility matrix for beta.shapeshift.com... Is there json-formatted list of coins supported by TrezorConnect vs wallet.trezor.io vs 3rd party wallets served up somewhere on trezor.io? Or is the recommended thing to do for us to submodule trezor-firmware/common/defs so we can access support.json / coins_details.json from our frontend?

**Comment by szymonlesisz** [comment]
Hi @keepkeyjon, you can find complete list of coins supported by connect here:
https://connect.trezor.io/7/data/coins.json

Those data are generated from trezor-firmware/common/defs. 
You can find a script, in `tools/cointool.py` which will dump all definitions depending on filters.
for example: `cointool.py dump -p -d connect` will generate all coins with `connect` set to true

**Comment by keepkeyjon** [comment]
wonderful, thank you!
