### ISSUE TITLE
How to add new coin on trezor connector? and MEW, MyCrypto.

### ISSUE THREAD

**Issue by trustfarm-dev** [trezor/connect#399]
Thanks, for trezor.

We have launched new coin , derived from ethereum.

1. ChainID is 0x8288 (33416) EIP-155 Supports.
2. note url : https://teonode1.tao.foundation

Coin Name  is  TEO : you can refer https://forum.tao.foundation
Exchanges are  :  BISQ (P2P) , Graviex.net  , Stex.com

And running MEW variants TAO wallet sites are
https://wallet.tao.foundation  ,  also github is https://github.com/tao-foundation/taowallet 

Can you guide what to do? and Can you review the upgrade points?
Also PR is welcome.

Also, you did , It is also bounty jobs! and open your wallet .
Because I didn't fully tested your trezor wallet in testnet season , I closed ux which hw supports line.

Thanks,

**Comment by trustfarm-dev** [comment]
Basically added TREZOR support , 
but 
![image](https://user-images.githubusercontent.com/18391665/57997796-894da500-7b09-11e9-88a9-61ae4085edaa.png)

Can you inform when error?

**Comment by szymonlesisz** [comment]
Hi @trustfarm-dev,
From what i understood you want to add TEO (or TAO?) coin to be supported by Trezor.
Follow developers contribution instructions:

https://wiki.trezor.io/Developers_guide:Contributing

**Comment by trustfarm-dev** [comment]
@szymonlesisz  Thanks, I will do.
