### ISSUE TITLE
bug: "device call in progress" race

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/connect#403]
I'm seeing a race on the state of `runPromise`, which gets cleared after a message is sent, instead of just before:
 https://github.com/trezor/connect/blob/c7fb0032a8475cc09ec29ccc860fbe76066f4169/src/js/device/Device.js#L172

This shows up on rapid back-to-back calls to TrezorConnect, where the first request gets cancelled by the user, and then the second request gets rejected with a "device call in progress" response, even though we already got the "cancelled" response back from the first event. If I insert a `setTimeout` delay between the two calls, it starts working.

I think it might be fixed by clearing the runPromise just before `postMessage`-ing the response, but I'm not familiar enough with the code to be sure that won't break any other assumptions.

**Comment by tsusanka** [comment]
It seems to me this is fixed in develop:

https://github.com/trezor/connect/blob/cfeb056f1d3c6b2f40fd45bb20e63931dea3f57b/src/js/device/Device.js#L200-L204

Please reopen if this issue persists.
