### ISSUE TITLE
Can't able to send  eth amount using sign in transaction

### ISSUE THREAD

**Issue by fintegri** [trezor/connect#407]
Hi,

Here is the code I used to send ETH amount but it throw error on params

**Example code:**

var amount = 0.001;
	amount = amount * 100000000;
	amount = "0x"+amount.toString(16);
TrezorConnect.signTransaction({ 
    path: "m/44'/60'/0'/0/",
    transaction: {
    	
        to: "0x9cb019E497De945500c88D1cE3800aE9250ddE84",
        value: amount,
        data: "0x01",
        chainId: 1,
        nonce: "0x0",
        gasLimit: "0x5208",
        gasPrice: "0xbebc200"
    }
}).then(function(result) {

    console.log(result) // hexadecimal string with "0x" prefix
})

**Output:** 

{payload: {…}, id: 1, success: false}
id: 1
payload:
error: "Invalid parameters: Parameter "inputs" is missing."
__proto__: Object
success: false
__proto__: Object

**Comment by mralbertchen** [comment]
Incorrect method - that is for Bitcoin / UTXO-based signing, which is why it's looking for the inputs argument.

For Ethereum, the correct method is https://github.com/trezor/connect/blob/develop/docs/methods/ethereumSignTransaction.md
