### ISSUE TITLE
signTransaction SPENDMULTISIG is showing a firmware error on firmware v2+

### ISSUE THREAD

**Issue by mralbertchen** [trezor/connect#408]
This code has been and still is working fine on TrezorOne v1.8

On v2.1.1 Trezor Model T, I get a warning that says 'Path m/48/0/0 is unknown. Are you sure?' - even after pressing yes and going through all the confirmation, the response I get is

`code: "Failure_FirmwareError"
error: "Firmware error"` 

Not sure if SPENDMULTISIG is not supported on v2+ or if the firmware is actually bugged. Thanks.

My inputs:

```[
  {
    "address_n": [
      48,
      0,
      0
    ],
    "prev_hash": "34051309d6383ffd5e63db0e3a2a221b536277a530ad9ec11bbd3a3e026dddb1",
    "prev_index": 0,
    "script_type": "SPENDMULTISIG",
    "multisig": {
      "pubkeys": [
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLT5EKNJwMeAXatWeuHroDiyEi4FoJ9PTKMpVnBAH2qMxE4gzUKc",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLTGHNvQUaz7BBLY88u2PWEaC1W2VcYxsgsmzdmmj248UcvDWGax",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLUKj5qhSecbaTmREr8kAYcr9YGuUzwQuJNearFCZmNWn8GA7Xkv",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLUp8eAxhRGtUtDKiTA8SaJUeJYjmtTY8vqTfr3BHB2rLLwrtZsW",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLVfJZQfnEYuKPhZjoPEXPVogGhvFLvrJuRoj4iC4XiGSXka8BTm",
          "address_n": []
        }
      ],
      "signatures": [
        "",
        "",
        ""
      ],
      "m": 3
    },
    "amount": "190659"
  },
  {
    "address_n": [
      48,
      0,
      0
    ],
    "prev_hash": "18a8f3db55fc644ff490946c5c414741447a11cb4a10246eb45b6ea9c0b95fba",
    "prev_index": 1,
    "script_type": "SPENDMULTISIG",
    "multisig": {
      "pubkeys": [
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLT5EKNJwMeAXatWeuHroDiyEi4FoJ9PTKMpVnBAH2qMxE4gzUKc",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLTGHNvQUaz7BBLY88u2PWEaC1W2VcYxsgsmzdmmj248UcvDWGax",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLUKj5qhSecbaTmREr8kAYcr9YGuUzwQuJNearFCZmNWn8GA7Xkv",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLUp8eAxhRGtUtDKiTA8SaJUeJYjmtTY8vqTfr3BHB2rLLwrtZsW",
          "address_n": []
        },
        {
          "node": "tpubD6NzVbkrYhZ4WLczPJWReQycCJdd6YVWXubbVUFnJ5KgU5MDQrD998ZJLVfJZQfnEYuKPhZjoPEXPVogGhvFLvrJuRoj4iC4XiGSXka8BTm",
          "address_n": []
        }
      ],
      "signatures": [
        "",
        "",
        ""
      ],
      "m": 3
    },
    "amount": "100000000"
  }
]

```

My outputs:

```
[
  {
    "address": "mpEojWCX1EMudNAEdJc3SPzwQMk5N3Ay7y",
    "script_type": "PAYTOADDRESS",
    "amount": "500000"
  },
  {
    "address": "2N9c84VkvjehBnm1hFXNNEai71mnZ6VS6TY",
    "script_type": "PAYTOADDRESS",
    "amount": "99590659"
  }
]
```

**Comment by szymonlesisz** [comment]
At the first sight: your "address_n" is not hardended, this is why you get `Path m/48/0/0 is unknown. Are you sure?` warning.
Also derivation path needs to point to correct change address (receiver of this input)
Try with:
```
address_n: [(48 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, 0, 0],
```

[Read more about path](https://github.com/trezor/connect/blob/develop/docs/methods/path.md)

**Comment by fujiwaraizuho** [comment]
I'm also experiencing the same problem.
Is there any solution?

My Inputs:
<pre>
const inputs = [
    {
        address_n: [(44 | 0x80000000) >>> 0, (22 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, 0, 0],
        prev_hash: 'b4070e816f727a795cc364f44ba0bb88d7174e8532076f63122f7e529d2c22a9',
        prev_index: 0,
        script_type: 'SPENDMULTISIG',
        multisig: {
            pubkeys: [
                {
                    node: 'xpub6BUscMAn3MQuSesDGrzwcxupp6bhTAqWajuqNShwNb9dngnToRsEwosiDJEvjYy8RG4YmXVVW8BKeCE48zxQ329fspfPcGQcgyritMWhQY7',
                    address_n: [(44 | 0x80000000) >>> 0, (22 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, 0, 0]
                },
                {
                    node: 'xpub6D2uwwCysWUc3SCMvMLN4nc9WSE3NnfgBrLmBbn446xXUU3D5gYgcnm6L78YfUb38vtaYQQ5b3a1puJ7UspxEvMTKmhuUpVpqd2on46KxZE',
                    address_n: [(44 | 0x80000000) >>> 0, (22 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, 0, 1]
                },
                {
                    node: 'xpub6DFadUYnXJukJ82oK26MPEgPd7aT9wcjWpMvWBqD88THnZLeiYXVvhy9Hp9eDxTrvAkdRcQabGLn5xSjYpeYYCHoWDrFhPC6ZYq9UyXmFQE',
                    address_n: [(44 | 0x80000000) >>> 0, (22 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, 0, 1]
                }
            ],
            signatures: ['', '', ''],
            m: 2
        }
    }
];
</pre>
My Outputs:
<pre>
const outputs = [
    {
        address: 'MNjfv4Xj147c8yhircbjzREmVsBYCvT2RF',
        amount: '99943450',
        script_type: 'PAYTOADDRESS'
    }
];
</pre>
