### ISSUE TITLE
https://sisyfos.trezor.io/connect-electron is no longer available

### ISSUE THREAD

**Issue by floating** [trezor/connect#417]
https://sisyfos.trezor.io/connect-electron is no longer available and broke the current build. What is the official connect source with electron event functionality?

**Comment by floating** [comment]
?

**Comment by floating** [comment]
Could we get an update on this?

**Comment by pankrats** [comment]
@szymonlesisz probably would know

**Comment by floating** [comment]
@szymonlesisz Any info?

**Comment by floating** [comment]
Can we please just get an update on this? We'd really like to release a fix and we're not sure the status of things. We had everything working with connect.

**Comment by szymonlesisz** [comment]
Hi, sorry for delay, i'm just finishing working on version 8, it should be available by the end of the week

**Comment by floating** [comment]
Great, thanks @szymonlesisz!

**Comment by floating** [comment]
@szymonlesisz Where can I find version 8 details?

**Comment by szymonlesisz** [comment]
package `trezor-connect@8.0.0-rc.1` with electron support is already released,
i will keep it as `beta` release for a while to make sure that every implementation is working correctly.

You don't have to specify custom `connectSrc` now, just use default at https://connect.trezor.io/8/

**Comment by eabz** [comment]
Thanks @szymonlesisz I have been waiting this release for months. 
Tested and works!
