### ISSUE TITLE
Invalid parameters: Method eosGetPublicKey not found

### ISSUE THREAD

**Issue by jafri** [trezor/connect#420]
When calling `await TrezorConnect.eosGetPublicKey`. It launches https://connect.trezor.io/7/popup.html#loading and then returns the following error:

```
"Invalid parameters: Method eosGetPublicKey not found"
```

**Comment by jafri** [comment]
I believe the https://connect.trezor.io/7 link needs to updated to the new version

**Comment by szymonlesisz** [comment]
released as 7.0.4, sorry for delay
