### ISSUE TITLE
TrezorConnect.stellarSignTransaction does not allow inclusion of additional signatures

### ISSUE THREAD

**Issue by ConnorMac** [trezor/connect#426]
When trying to setup and sign mutli-signature transactions with a Trezor the stellarSignTransaction transaction json object does not allow the inclusion of a signatures array. 

This means it's impossible to sign with more than 1 account as the the Trezor will not being signing the correct transaction without the first signature and the JS SDK will return an invalid signature error when trying to add any signature after the first.

**Comment by ConnorMac** [comment]
@szymonlesisz Any chance to have a look at this yet? Trying to make sure I'm not missing something that isn't documented.

**Comment by prusnak** [comment]
Please check the supported fields in this protobuf definition: https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-stellar.proto

If you require fields that are not there, the operation is not supported in the firmware (and that's the reason why it is not in the Connect).
