### ISSUE TITLE
Unable to sign transaction when upgraded to 1.8.0 and using https://connect.trezor.io/7/trezor-connect.js

### ISSUE THREAD

**Issue by adacai1982** [trezor/connect#427]
When try to sign a btc transaction through the latest trezor connect after upgrading the firmware to 1.8.0 the web page stucked at "Please follow the instructions on the device", although I've already confirmed the transaction on the device.

**Comment by szymonlesisz** [comment]
it should be fixed now (7.0.5), sorry for inconvenience
