### ISSUE TITLE
Iframe timeout when calling trezor-connect inside sandboxed iframe

### ISSUE THREAD

**Issue by ghost** [trezor/connect#429]
Hey, @szymonlesisz. Getting `Iframe timeout` error when using trezor-connect inside sandboxed iframe with parameters `allow-scripts allow-popups`. Any help will be appreciated

It works with `allow-same-origin` parameter added, but I don't want to add it for a reason

Plunkr with example: https://plnkr.co/edit/670gh1P132uIPkpXgNrW?p=preview

**Comment by szymonlesisz** [comment]
I think `allow-same-origin` is required to allow postMessaging between elements

**Comment by ghost** [comment]
@szymonlesisz postMessage is working without `allow-same-origin` option when using with `*` parameter as origin parameter
Example here: https://plnkr.co/edit/9f1s3fUjptjyHw2cvuTt?p=preview

**Comment by szymonlesisz** [comment]
yeah, but i don't want to use "*", for a reason :)
