### ISSUE TITLE
about dust_limit ？

### ISSUE THREAD

**Issue by Ark-Chen** [trezor/connect#431]
dust_limit value on the btc chain is 546, but I see that the source code must be higher than 546
Can't equal 546 because of other reasons?

![image](https://user-images.githubusercontent.com/31213168/62455932-f89e7100-b7a9-11e9-9853-733495644f0d.png)

**Comment by szymonlesisz** [comment]
`coinInfo` precisely data inside [coins.json file](https://connect.trezor.io/7/data/coins.json) are generated from [trezor-firmware/common](https://github.com/trezor/trezor-firmware/tree/master/common) repository.
If you think this value is invalid please report it there
