### ISSUE TITLE
EOS Action Error

### ISSUE THREAD

**Issue by jafri** [trezor/connect#437]
When passing in this action to EOS Trezor:

```
        actions: [{
            account: "eosio",
            authorization: [{
                actor: "bloksservice",
                permission: "active",
            }],
            name: "voteproducer",
            data: {
                voter: "bloksservice",
                proxy: "",
                producers: ["eoscafeblock", "hkeoshkeosbp"]
            },
        }]
```

Trezor connect returns this error:
```
Invalid parameters: Eos serialization error, "undefined" should be a string
```

**Comment by szymonlesisz** [comment]
could you provide whole "transaction" json?

**Comment by jafri** [comment]
@szymonlesisz 

```
{
    "path": "m/44'/194'/0'/0/0",
    "transaction": {
        "chainId": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
        "header": {
            "expiration": "2019-08-14T16:06:27.000",
            "refBlockNum": 8806,
            "refBlockPrefix": 1017497600,
            "maxNetUsageWords": 0,
            "maxCpuUsageMs": 0,
            "delaySec": 0
        },
        "actions": [
            {
                "account": "eosio",
                "name": "voteproducer",
                "data": {
                    "voter": "bloksservice",
                    "proxy": "",
                    "producers": [
                        "eoscafeblock",
                        "hkeoshkeosbp"
                    ]
                },
                "authorization": [
                    {
                        "actor": "bloksservice",
                        "permission": "active"
                    }
                ]
            }
        ]
    }
}
```

**Comment by szymonlesisz** [comment]
according to [types](https://github.com/trezor/connect/blob/develop/src/js/types/eos.js#L110-L114) it should be:
```
data {
 account: 'bloksservice'
...
}
```

you have used `voter` instead.

**Comment by jafri** [comment]
@szymonlesisz that is incorrect. It is voter on the EOS blockchain
<img width="455" alt="Screen Shot 2019-08-15 at 12 29 40 AM" src="https://user-images.githubusercontent.com/13677357/63076872-d1574a80-bef3-11e9-88a0-38f4c44f9277.png">

**Comment by szymonlesisz** [comment]
EOS support was added to trezor-connect as a pull request by a third party and tbh i don't know much about this network, therefore there is a possibility that not all parameters have proper name.
I will change this to "voter". Could you please have a look and check the rest of EOS actions parameters are valid [here](https://github.com/trezor/connect/blob/develop/src/js/types/eos.js#L70-L144)? I don't want to make multiple releases because of this

**Comment by jafri** [comment]
@szymonlesisz should be good now: https://github.com/trezor/connect/pull/438

**Comment by szymonlesisz** [comment]
Cool, thanks for contribution!
It's merged and will be released in few hours as 8.0.1

**Comment by jafri** [comment]
@szymonlesisz what is the process for adding new actions? Provide new types and new display messages?

**Comment by szymonlesisz** [comment]
It would be to easy :)
Firstly you need to add those actions to the [firmware](https://wiki.trezor.io/Developers_guide-Contributing#Adding_a_new_coin)
After that you need to build new protobuf messages from `trezor-common` submodule and finally add types and [param tranformation](https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/eosSignTx.js#L167) to `trezor-connect` (parameters need to be transformed from "input" to "protobuf")

**Comment by jafri** [comment]
Thanks for the steps @szymonlesisz :)
