### ISSUE TITLE
Wrong bitcore URLs

### ISSUE THREAD

**Issue by slush0** [trezor/connect#44]
https://connect.trezor.io/1/connect.js refers "bitcore2.trezor.io" and "bitcore3.trezor.io". Correct are "bitcore1" and "bitcore3"; "bitcore2" will be discontinued soon.

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/connect/commit/c0ca4f5fb60f8f62881cc5d97a0d4c1a269e8b92
