### ISSUE TITLE
How to set login page icon (hostIcon) in current Connect?

### ISSUE THREAD

**Issue by Crypto2** [trezor/connect#442]
Upgrading from v4 here, got everything working but can't figure out how to set the image shown on the login page? I've tried icon, hosticon, and hostIcon in in the requestLogin() params but seemingly no result.

**Comment by szymonlesisz** [comment]
We have decided that we don't want to inject images from a thirdparty servers.
If you want to have your logo inside popup please make a PR with modified [config.xml](https://github.com/trezor/connect/blob/develop/src/data/config.json#L25) file where you specify your url and image and add your image to [icons directory](https://github.com/trezor/connect/tree/develop/src/data/icons)

**Comment by Crypto2** [comment]
Before I do a PR is this the correct format? https://github.com/CoinPaymentsNet/connect/commit/b50e6eb6498b8b8f8d65f6119987aa8056584365#diff-eddd43f5c219d893a272123d5754ddc4
