### ISSUE TITLE
Add support for EOS REX

### ISSUE THREAD

**Issue by danra** [trezor/connect#443]
REX support is missing when connected to bloks.io with Trezor One.
From what I understood talking with bloks.io, to support this, Trezor Connect has to add support for the operation (or more in general, to non-standard EOS contracts).

Thanks,
Dan

**Comment by szymonlesisz** [comment]
Hi @danra, not quite.
Connect is just a API which provides UI for the user and provide communication with Trezor device. Adding new operation to connect doesn't solve anything. From what i know connect supports all types of operations known by the device. [Here's](https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-eos.proto#L68-L82) a complete list of known operations.
To support new type of operation you need to add it to the firmware in the first place.
[Here's how to do that](https://wiki.trezor.io/Developers_guide-Contributing)

**Comment by danra** [comment]
I see - I will try and open a matching issue for the Trezor Wallet, then.

Thanks,
Dan
