### ISSUE TITLE
Add possibility to use custom or non-bitcoin Bitcore server

### ISSUE THREAD

**Issue by prusnak** [trezor/connect#45]
[getAccountInfo](https://github.com/trezor/connect#get-account-info) calls and others (`signTx`, `composeAndSignTx`, etc.) are contacting Bitcore instance to access the blockchain. The list of instances is hard-coded in the Connect code, but the list is limited to Bitcoin-only instances, which makes Connect unusable for alt-coins.

I see two options, how to fix the problem:

1) Connect detects the coin by parsing given BIP44 path, or even better the coin will be given explicitly as another parameter of the call. Connect will have a hard-coded list of Bitcore instances for each coin and use these.

2) We will allow the user of Connect API to specify the 3rd party Bitcore URL

I am voting for 1) although it means we'd need to host a Bitcore instance for every supported altcoin, because with 2) one can provide a malicious Bitcore instance.

**Comment by MrDefacto** [comment]
At least Dash instance +1 ;-)

**Comment by kantai** [comment]
Hi @prusnak -- I'd like to cast a vote in favor of option (2) -- perhaps giving the user a dialog to chose a different bitcore URL during the connect-approval popup (a related question is, does the bitcore node configuration setting in a user's wallet affect this at all?)

A (probably common?) use case currently not served by `connect.js` is the ability to use a Trezor to make testnet transactions on a local regtest network. This is useful for a couple different things, but mostly it is much easier to test behaviors on a local regtest network than on the public testnet. This can be done with `trezor.js`, but I see that's being deprecated in favor of `connect.js`, so it'd be great to see support for that here as well.

**Comment by keraf** [comment]
Custom backends can be set using `Trezor.blockchainSetCustomBackend`.

See: https://github.com/trezor/connect/blob/develop/src/js/core/methods/blockchain/BlockchainSetCustomBackend.js

Closing issue.
