### ISSUE TITLE
trezor.io was on this blacklist (used by pihole)

### ISSUE THREAD

**Issue by stachrom** [trezor/connect#451]
**blacklist**: https://github.com/StevenBlack/hosts 
--> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
This is used by pihole https://github.com/pi-hole/pi-hole. 

And why on earth is the password manager (https://github.com/trezor/trezor-password-manager) not able to connect to trezor (t1) - without a working DNS connection to connect.trezor.io? 

Can you explain, why this is necessary or point me to a explanation/wiki/doku?  

Thank you -

**Comment by stachrom** [comment]
not anymore - they removed it already.  
--> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts is clean again. 

I think the ban is introduced by https://gitlab.com/ZeroDot1/CoinBlockerLists

**Comment by szymonlesisz** [comment]
thanks for report
