### ISSUE TITLE
Unknown message

### ISSUE THREAD

**Issue by mroz22** [trezor/connect#454]
Probably we need to load message definitions conditionally because of the new backupType field. This happens when I send resetDevice with backupType field with 2.1.1 fw

![image](https://user-images.githubusercontent.com/30367552/65164331-fbdd7b80-da3c-11e9-83da-f27f3f19cd86.png)

**Comment by tsusanka** [comment]
@mroz22 please open a new one in trezor-suite if this is still relevant, but as you have refactored trezor-link I think it is not..
