### ISSUE TITLE
Error: Cannot read property 'lookupTransaction' of undefined

### ISSUE THREAD

**Issue by rossgeesman** [trezor/connect#46]
I am getting the following error when attempting to compose a transaction with this library.
```
{
  "success": false,
  "error": "Cannot read property 'lookupTransaction' of undefined"
}
```
This is happening in both my implementation and in your examples here https://connect.trezor.io/1/examples/. I've tried in Safari and Chrome with the same results. Is it possible that my Trezor has an issue? Thanks!

**Comment by prusnak** [comment]
cc @karelb

**Comment by runn1ng** [comment]
thanks, will look at it later

**Comment by rossgeesman** [comment]
I'm still getting this error. Has there been any progress?

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/connect/pull/48

**Comment by runn1ng** [comment]
It's fixed on connect.trezor.io/1/ now
