### ISSUE TITLE
[BUG?] Stellar signing / `bumpSequence` operation

### ISSUE THREAD

**Issue by MisterTicot** [trezor/connect#463]
**Issue**

Trezor seems to parse the `bumpTo` field incorrectly and produce an invalid
signature.

**Transaction Template**

```
{
  "source": "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
  "sequence": 0,
  "operations": [
    {
      "type": "bumpSequence",
      "bumpTo": 100
    }
  ],
  "fee": 100
}
```

**Device Display**

```
Bump Sequence
Set sequence to:
0
```

**Comment by szymonlesisz** [comment]
connect expects `to` [parameter](https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/stellarSignTx.js#L207) you are using `bumpTo`.

Should i rename it?

**Comment by MisterTicot** [comment]
I think so, as you're trying to match the official API: https://www.stellar.org/developers/guides/concepts/list-of-operations.html#bump-sequence

As far as I can tell, people who support Trezor are not making use of this feature so far, so I think this still time to change it.

(By the way thank you for pointing it, I totally missed it when looking for solutions)

**Comment by MisterTicot** [comment]
Fixed
