### ISSUE TITLE
About the 7 issues I opened

### ISSUE THREAD

**Issue by MisterTicot** [trezor/connect#468]
I'm writing an open-source library to ease integration of the Trezor wallet with Stellar applications. I just released a beta here: https://www.npmjs.com/package/@cosmic-plus/trezor-wallet

During the development, I tried to submit every & each possible transaction to the test network, and I opened an issue for each cases I could not solve.

In most case, I'm not sure if it is a bug or me doing something wrong. Please help me solving those in a timely fashion so I can release a production-ready library soon.

**Comment by szymonlesisz** [comment]
Hi @MisterTicot, 
Thanks for your reports, but all of your issues are targeting the firmware so please move them to the [proper repository](https://github.com/trezor/trezor-firmware/)
`trezor-connect` is only a dummy api to call known Trezor messages - so if firmware doesn't have them implemented connect will not help you with that

**Comment by MisterTicot** [comment]
@szymonlesisz Can you do it please? I don't have the required permissions to transfer an issue.

**Comment by MisterTicot** [comment]
By the way, are you absolutely sure each issue is related to the firmware? It seems to be that some of the issues may be API related.

**Comment by szymonlesisz** [comment]
[this one](https://github.com/trezor/connect/issues/463)  probably belongs here, but tbh. i dont have enough time to debug it right now

**Comment by MisterTicot** [comment]
@szymonlesisz 

Ok then I can only leave it in that state hoping you'll take over it soon. Unfortunately I can't sort it out for you.

Please acknowledge that I can't decently release a stable version of the library until those issues are solved. So if you guys still aim at a wide support into Stellar apps you probably want to take over it soon.

**Comment by tsusanka** [comment]
@MisterTicot thanks for the reports. We will transfer most of the issues to trezor-firmware, even the ones where we are not sure, because we need to debug how the firmware behaves. Could you please write to each issue which Trezor are you using (Model One vs T) and which fw version?

We will try to address this soon, but please note that we have other duties at the moment as well. Also, the firmware for model T is written in micropython so the [stellar implementation](https://github.com/trezor/trezor-firmware/tree/master/core/src/apps/stellar) should be quite easy to understand, feel free to have a look and file a PR.

**Comment by MisterTicot** [comment]
@tsusanka I'm using Trezor One with the latest firmware

**Comment by szymonlesisz** [comment]
Hi @MisterTicot ,
I've fixed multiple issues [here](https://github.com/trezor/connect/pull/474/commits/d317e35cee43bebc43504553b208569f88bd54e0)

- fixed [`uint64` issue](https://github.com/trezor/connect/issues/464)
- fixed [`bumpSequence` issue](https://github.com/trezor/connect/issues/463)
- fixed flowtype (required/optional params and amounts/sequence/... as strings)

I've also add a tool which could help you (and hopefully others) to transform `StellarSDK.Transaction` object into `TrezorConnect.StellarTransaction` object.
You can find it [here](https://github.com/trezor/connect/blob/develop/src/js/plugins/stellar/plugin.js)
And added to documetation [here](https://github.com/trezor/connect/blob/develop/docs/methods/stellarSignTransaction.md#stellar-sdk-compatibility)

Additionally i've write tests for every known operation supported by `Trezor`, then i've use results (signatures) from `trezor-connect` and compare them with `StellarSDK` transaction results.
You can check [this repo](https://github.com/szymonlesisz/trezor-connect-stellarsdk) to verify the results

I hope now everything will work as expected

**Comment by MisterTicot** [comment]
@szymonlesisz 

I'm looking into it - I think I'm going to PR a few changes. Anyway, this is great work. Thank you for that.

Any clue when this can be released? Meanwhile, is there a way I can include the latest revision into my test interface?

**Comment by MisterTicot** [comment]
@szymonlesisz 

https://github.com/szymonlesisz/trezor-connect-stellarsdk/pull/1
https://github.com/trezor/connect/pull/478

Please let me know if everything is ok.

**Comment by szymonlesisz** [comment]
> Any clue when this can be released? Meanwhile, is there a way I can include the latest revision into my test interface?

connect with those changes was already released 2 days ago:
https://www.npmjs.com/package/trezor-connect/v/8.0.7

new firmware is released every first wednesday of the month, however you can already test it with emulator from master branch
https://github.com/trezor/trezor-firmware/blob/master/core/docs/emulator/index.md

> Please let me know if everything is ok.

I've add a comment to your PR

**Comment by szymonlesisz** [comment]
I've noticed that you also did a PR in firmware with `manageBuyOffer` operation. Maybe i should add/prepare connect to support it too? And what about `pathPaymentStrictSend`? tbh i don't understand stellar too much and i don't know what it does exactly, but i've noticed that we don't have support for those two operations

**Comment by MisterTicot** [comment]
> I've noticed that you also did a PR in firmware with manageBuyOffer operation. Maybe i should add/prepare connect to support it too?

That would be great!

> And what about pathPaymentStrictSend? tbh i don't understand stellar too much and i don't know what it does exactly, but i've noticed that we don't have support for those two operations.

This is a new operation that is expected to get enabled for mainnet in two weeks and that is already available on the testnet. Details are [here](https://www.stellar.org/developers/blog/horizon-v0-22-0-released-protocol-12-support).

It is a conversion+transfer. pathPaymentStrictReceive (previously pathPayment) is like:

`Convert up to N Ethereum to send exactly 200USD to Alice`

pathPaymentStrictSend is like: 

`Convert exactly N Ethereum to send at least 200USD to Alice`

We don't know the exact conversion rate ahead of time, so one side of the conversion have to be rangebound while the other can be fixed.

**Comment by MisterTicot** [comment]
> connect with those changes was already released 2 days ago:
https://www.npmjs.com/package/trezor-connect/v/8.0.7

I'm not sure if this is intended, but this is marked as a beta release - the latest being 7.0.5. Is it safe to switch?

**Comment by szymonlesisz** [comment]
yes, it is safe to use. it's marked as `beta` because there was [multiple breaking changes](https://github.com/trezor/connect/blob/develop/CHANGELOG.md#800) in communication process between host, iframe and popup and also in "backend" layer and export targets (nodejs and electron support). I'm still adding/fixing few things there, but it affects only "bitcoin-like" and "ethereum-like" coins and i don't want break those integrations by releasing it as public until i finish :)

it will be public in few weeks

**Comment by MisterTicot** [comment]
I just swiched to Trezor-Connect 8.x & latest T1 firmware:

- `bumpSequence` works fine

- `changeTrust` gives me `user cancelled` instead of showing the operation confirmation screen. I tried with `limit: "0"`, `limit: "10000000000"` and max limit (`"9223372036854775807"`). Example:

```
{
  "operations": [
    {
      "type": "changeTrust",
      "asset": {
        "code": "ETH",
        "issuer": "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR",
        "type": 1
      },
      "limit": "10000000000"
    }
  ],
  "fee": 100
}
```

- `manageData` still breaks on non-4 byte round values, so I guess the firmware
  fix has not been released yet.

_Note:_ I used [my own tx-transformer](https://github.com/cosmic-plus/js-trezor-wallet/blob/master/src/trezor-tx.js) - not tried to switch to yours yet.

**Comment by szymonlesisz** [comment]
`changeTrust` is expecting "line" not "asset" field

> so I guess the firmware fix has not been released yet.

I wouldn't expect to be released since fixes was added 14 days ago :)

Like i said before, you can test it with emulator from master branch of `trezor-firmware` those fixes are already there. This is where i get trezor signatures from (signatures used on my test repo)

**Comment by MisterTicot** [comment]
> changeTrust is expecting "line" not "asset" field

Right on the spot − works great now. Looks like we're not far from having everything fixed. Thank you guys :D.
