### ISSUE TITLE
getPublicKey incorrectly reports `Bitcoin Account #1` for ETH xpub

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/connect#469]
If I call `getPublicKey` with:

```
{ bundle: [{
  coin: 'Bitcoin',
  path: [2147483692, 2147483708, 2147483648], // a.k.a. m/44'/60'/0'
  crossChain: true
}] }
```

The UI says we're requesting ` Bitcoin legacy account #1`, which isn't correct. It should probably say something like `All Ethereum accounts` or something similar.

**Comment by szymonlesisz** [comment]
use `ethereumGetPublic` key method instead or do not use "crossChain" parameter
