### ISSUE TITLE
Iframe timeout -> Popup blocked

### ISSUE THREAD

**Issue by Cabecinha84** [trezor/connect#506]
I was trying to use the official trezor connect on one electron app and got a iframe timeout and a popup saying that the popup was blocked when trying to use any api method.
Had the same problem with trezor-connect-electron-boilerplate project and raised a issue there.
<img width="960" alt="Error_trezor_connect" src="https://user-images.githubusercontent.com/42519726/70387807-892bce80-19a1-11ea-9fc0-f8c00f26b15d.png">

Can you help me?

**Comment by szymonlesisz** [comment]
I cannot help you without code example

**Comment by Cabecinha84** [comment]
just running boilerplate project without changing anything. The error on print screen is what I get running it.
https://github.com/szymonlesisz/trezor-connect-electron-boilerplate/issues/5

**Comment by szymonlesisz** [comment]
Oh i see, yeah this example is a little bit outdated and i don't have a time to maintain it.
Change connect version:
`yarn add trezor-connect@8.0.11-extended`

Use proper endpoint (or do not set it at all, it's default value):
`
TrezorConnect.init({
    connectSrc: 'https://connect.trezor.io/8/',
}
`



You can also check one of these examples (not finished yet):
https://github.com/trezor/connect/tree/feature/examples/examples/electron

**Comment by Gabriel-2010** [comment]
I have the same issue. It always appeared when trying to use any API method. But it works occasionally after many tries. Does it have a good solution? I doubt whether the timeout period is too short?

**Comment by Cabecinha84** [comment]
Hello, even with those changes, it doesn't work. Really would like to give it a try to add trezor support to zelcore.

**Comment by szymonlesisz** [comment]
see complete examples how to run connect in electron:
https://github.com/trezor/connect/tree/develop/examples/electron

**Comment by Nevquit** [comment]
Why this issue was closed without any conclusion? @Cabecinha84 Has the issue gone away?
