### ISSUE TITLE
Can we make `TrezorConnect.getAddress` work with multisig addresses?

### ISSUE THREAD

**Issue by dhruvbansal** [trezor/connect#509]
The `TrezorConnect.getAddress` method does not respect `multisig` or `script_type` parameters when passed.  This prevents the Trezor device from displaying a multisig address, at least when being accessed through TrezorConnect.

* The [docs for TrezorConnect.getAddress](https://github.com/trezor/connect/blob/develop/docs/methods/getAddress.md) do not discuss the `multisig` nor `script_type` parameters.
* The [datatype definitions here](https://github.com/trezor/connect/blob/develop/src/data/messages/messages-v7.json#L572-L586) seem to suggest that `TrezorConnect.getAddress` can accept these parameters.
* But the [code for TrezorConnect.getAddress](https://github.com/trezor/connect/blob/develop/src/js/core/methods/GetAddress.js) just skips over them even if they are passed.

Trezor devices are certainly [capable of properly displaying multisig addresses](https://github.com/trezor/trezor-firmware/blob/08117331859edeaa210b8349b1c0e1efd6d0e23c/python/src/trezorlib/messages/GetAddress.py#L24-L25).  The Python API respects the `multisig` and `script_type` parameters which allows wallets such as Electrum to implement [multisig address display on Trezors](https://github.com/spesmilo/electrum/blob/428b63822b359d56d6ececabf406a43589545d24/electrum/plugins/trezor/trezor.py#L333-L346).

The TrezorConnect API supports `multisig` and `script_type` parameters in other contexts, for example when defining an input to a multisig address in `signTransaction`.

Adding this functionality would make Trezor devices much more secure for those accessing them through a web browser.

**Comment by prusnak** [comment]
Hey Dhruv!

We just released connect 8.0.13 with your changes. Please test them out and report back whether everything works as expected.

Thank you for the contribution and @szymonlesisz for reviewing and adapting the changes!
