### ISSUE TITLE
Message builder exports functions and are used as classes

### ISSUE THREAD

**Issue by nodech** [trezor/connect#512]
I changed babel configs so it outputs `async/await` code for node.js to make debugging easier, but it can't be used right now:
 Message builder: https://github.com/trezor/connect/blob/develop/src/js/message/builder.js exports functions that will be exported as arrow functions if you target later browser/node, but because arrow functions can't be used as constructors it will fail.

So either message builder needs to become actual class (or in worst case, change to function instead of arrow function to behave like legacy classes)
or
usage should change from `new DeviceMessage(..)` to `DeviceMessage(...)`.

Right now babel transpiles them to functions (not arrow functions), so they also act as constructors (even though they don't return constructed object, but new one) and syntax `new DeviceMessage` does not fail.

**Comment by szymonlesisz** [comment]
again, good catch :) and thanks for your contribution :)

to be honest this is that part of the code which i likely do not touch until it's working :)
but seriously, we are planning massive refactoring to typescript and monorepo structure so this kind of stuff will be refactored

**Comment by nodech** [comment]
I believe that will take quite some time, looking forward to new updates. I could create PRs that I am using currently locally to get rid of the errors and have modern js output for node.
It is not be a big change though.
