### ISSUE TITLE
Device: firstRunPromise will resolve many times

### ISSUE THREAD

**Issue by nodech** [trezor/connect#513]
Even though first run promise, should be resolved once -- https://github.com/trezor/connect/blob/929d37c59bb1d079861fb27cffb795f19c5a477f/src/js/device/Device.js#L303 will resolve every time there's incoming call (If understand that part correctly)

Fact is, that promise resolves several times, it could probably fixed by `this.loaded` first.

**Comment by szymonlesisz** [comment]
there is only one place in code where it's checked:
https://github.com/trezor/connect/blob/develop/src/js/core/Core.js#L359-L362

so resolving this promise multiple times will not have any side effects.
Anyway thanks for pointing that out, it should be done better

**Comment by nodech** [comment]
Yeah, there are no side effects. Just test runner threw an error that there were multiple resolves, so I decided to look into it.
