### ISSUE TITLE
No bundle payload (babel issue?)

### ISSUE THREAD

**Issue by nodech** [trezor/connect#514]
Somehow changing target for this code:
https://github.com/trezor/connect/blob/929d37c59bb1d079861fb27cffb795f19c5a477f/src/js/core/methods/GetPublicKey.js#L34

Specifically object spread into array: `[ ...message.payload ]`, this wont change with the new target where spreads are available and wont work because `Object is not iterable`, whereas old target (IE9) will produce `[].concat(message.payload)` which does totally different thing and you could argue is not what you expect based on `...message.payload` when it's an object. 

I think this could be rewritten as `[ message.payload ]`, unless `payload` is array sometimes (that is why this is an issue not a PR :)). This logic exists in several files as well.

**Comment by szymonlesisz** [comment]
good catch, params validation is a mess and needs to be refactored

Thanks
