### ISSUE TITLE
help

### ISSUE THREAD

**Issue by prettyCoders** [trezor/connect#518]
![图片](https://user-images.githubusercontent.com/36216120/72595090-09036c00-3944-11ea-815d-6102aa349fde.png)

**Comment by szymonlesisz** [comment]
your derivation path `m/45'/0/0/0` is not valid [bip44 path](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) and doesn't match Bitcoin Testnet pattern. It should be: `m/44'/'1'/0'` or `m/48'/'1'/0'` or `m/84'/'1'/0'`

however if you still want to get keys from your custom path "coin" parameter should not be set
