### ISSUE TITLE
help

### ISSUE THREAD

**Issue by prettyCoders** [trezor/connect#519]
![图片](https://user-images.githubusercontent.com/36216120/72606501-ad43dd80-3959-11ea-8ef3-3959409413b8.png)
What is the script_sig?Is redeemScript?

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/72606744-1c213680-395a-11ea-93bc-78244f8ff815.png)
This is my input ,It can be sign success, but it is invalid

**Comment by prettyCoders** [comment]
anybody there?

**Comment by szymonlesisz** [comment]
its a input script signature hex
https://tbtc1.trezor.io/tx/b42c658796927fb4d75aa7c5c404be78718c814b4fcd9a22a077a8c876a7240f
