### ISSUE TITLE
getting an address from getAccountInfo

### ISSUE THREAD

**Issue by tommq** [trezor/connect#524]
I am integrating connect into out react app. I would like user to be able to choose an address from trezor which we save for later use.

I tried the getAccountInfo method the discovery way, but response only has xpub/zpub/ypub and derivation path. I call:

```
TrezorConnect.getAccountInfo({
            coin: 'btc',
        })
```

And get:

```
{
  "id": 1,
  "success": true,
  "payload": {
    "path": "m/84'/0'/0'",
    "descriptor": "zpub6re7R4ohPAumTNrJAFbfMTwSwVjRBTsM7qaNDurmz5YoZhVX1eY1tRYjGJk7YJfBZntffJftXkjWEhxUg",
    "balance": "0",
    "availableBalance": "0",
    "empty": true,
    "history": {
      "total": 0,
      "unconfirmed": 0
    }
  }
}
```

My question is if there is any way to get the address user selected. Dealing with xpubs seems unnecessary and complex as we support multiple coins.

Also, the getAccountInfo method docs are outdated.

**Comment by szymonlesisz** [comment]
use:
`
TrezorConnect.getAccountInfo({
  coin: "btc",
  details: "tokens"
});
`
https://trezor.github.io/connect-explorer/#/method/getAccountInfo-advanced
