### ISSUE TITLE
trezor connect generates bech32 adresy by default

### ISSUE THREAD

**Issue by PavelNiedoba** [trezor/connect#547]
But trezor web interface don't support them. Please generate addresses recognized by web client by default. also finish bech32 support.

here is what happens to trezor users

https://client.simplecoin.eu/en/post/adresses-bc1-bech32-from-trezor-wallet 

i don't want to give them heart attacks

**Comment by szymonlesisz** [comment]
fixed https://github.com/trezor/connect/pull/548 and already released
Thanks for pointing that out
