### ISSUE TITLE
Connect Stuck on Loading (Firefox)

### ISSUE THREAD

**Issue by lnbc1QWFyb24** [trezor/connect#554]
When using version `8.0.13`, the connect popup stays stuck on the loading spinner when using Firefox(version `74.0.1`). 

Version `8` works correctly on Chrome, and version `7` also works correctly on both Firefox and Chrome.

**Comment by szymonlesisz** [comment]
is it still an issue with 8.1.1 ?

**Comment by bosomt** [comment]
works fine in Trezor connect explorer in latest Firefox 75.0

![conn8](https://user-images.githubusercontent.com/31506317/79967855-a9ab7f80-848f-11ea-9cb7-faa60390e6cc.gif)

**Comment by lnbc1QWFyb24** [comment]
Hey @szymonlesisz, I am not sure why I am getting different results in Firefox, have tried changing browser settings and still get the same result where it just sits on the loading spinner: 

![trezor-connect](https://user-images.githubusercontent.com/29873495/81513563-baebfb80-936c-11ea-9b93-f27d7ece6849.gif)

Firefox version `76.0.1 (64-bit)` on OSX

**Comment by lnbc1QWFyb24** [comment]
Actually nevermind, there must have been something borked in my Firefox preferences. Deleting the Firefox folder in `~/Library/Application Support/` fixed it. Sorry for the trouble!
