### ISSUE TITLE
How to sign P2WSH transactions using Trezor?

### ISSUE THREAD

**Issue by CodeForcer** [trezor/connect#555]
I run a non-custodial exchange and would like to support Bitcoin trading for my customers using their Trezor wallets.

Unfortunately, to do so I require the ability for a Trezor to sign a transaction which contains a custom unlocking script, according to the BIP 143 standard as defined here (https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#Native_P2WSH). I cannot figure out how to do this with Trezor.

For reference, although Electrum wallet doesn't yet support this officially, I was still able to hack together a working signature using their latest master branch since their inclusion of PSBT (version 4.0.0+).

Here is an example using Electrum open-source libraries of getting a valid BIP143 signature for a transaction from 1 input (given witness script, from value, previous output hash, and previous output idx) to 1 output (given output value and address):
```
from electrum import bitcoin, transaction

def get_bip143_signature(to_address,
                         to_value,
                         from_value,
                         prev_out_hash,
                         prev_out_idx,
                         witness_script,
                         priv_key_wif,
                         *,
                         nsequence=None):
    txOutput = transaction.TxOutput.from_address_and_value(to_address, to_value)
    tx = transaction.PartialTransaction(None)
    tx.add_outputs([txOutput])        
    prevout = transaction.TxOutpoint(bytes.fromhex(prev_out_hash), prev_out_idx)
    txInput = transaction.PartialTxInput(prevout=prevout)
    txInput._trusted_value_sats = from_value
    if nsequence:
        txInput.nsequence = nsequence
    txInput.witness_script = bytes.fromhex(witness_script)
    tx.add_inputs([txInput])
    sig = tx.sign_txin(0, bitcoin.deserialize_privkey(priv_key_wif)[1])
    return sig
```

I'm looking to achieve the same thing (valid signing of P2WSH tx's) while allowing traders on my site to instead use their Trezor wallets, rather than our onsite wallets.

Is there any way this kind of P2WSH signing can be done, either officially supported, or a workaround using the arbitrary signing functionality?

Thanks

**Comment by prusnak** [comment]
You can't sign arbitrary custom scripts with Trezor.

**Comment by CodeForcer** [comment]
@prusnak is there any plans to support P2WSH with Trezor in the future? Without P2WSH support it severely limits the use cases of Trezor, compared to competitors such as Ledger.

**Comment by prusnak** [comment]
P2WSH is supported with standard scripts only for now. It might change in the future, see https://github.com/trezor/trezor-firmware/issues/416

**Comment by CodeForcer** [comment]
Ok thanks @prusnak , looking forward to its support in the future. I guess a more comprehensive way to include it might just be to implement full support for signing PSBT's. Then you would get custom P2WSH scripts plus a bunch of other use-cases like embedding data in the Blockchain with OP_RETURN
