### ISSUE TITLE
Please add popup blocked notification to Trezor Connect explorer

### ISSUE THREAD

**Issue by bosomt** [trezor/connect#574]
When you are running Connect Explorer on different domain than trezor.io then popup if often blocked.
Maybe add warning of notification/check  to disable Privacy badger or different privacy/ad blocker.

![image](https://user-images.githubusercontent.com/31506317/79960926-4e28c400-8486-11ea-8786-813d9fcef1f5.png)

**Comment by keraf** [comment]
Currently being worked on in the feat/popup-block-notif branch. Code is there, need to fix the CI and add tests.

![Screenshot_2020-07-22 TrezorConnect Trezor](https://user-images.githubusercontent.com/30026749/88169613-845c1800-cc1c-11ea-98bc-4e9e4b641156.png)

**Comment by keraf** [comment]
PR has been merged, thanks @szymonlesisz !
