### ISSUE TITLE
v7 and v8 no longer work for browsers routing traffic through a Tor proxy

### ISSUE THREAD

**Issue by brianddk** [trezor/connect#576]
I'm noticing a consistent hang when accessing either `connect.trezor.io/7/popup.html` (MyCrypto) or `connect.trezor.io/8/popup.html` (MEW) over Tor, but any site using `connect.trezor.io/6/popup.html` (Stellar) seems to be fine.

Is Trezor using Cloudflare or any other type of anti-Tor CDN that might be triggering this issue?  Is there any other clear difference between v6 and v7 that might impact Tor?

It is easily reproducible by piping any Mozilla browser through a Tor Proxy.

### Update

Not as reproducible as I has originally thought... I was able to get through on MEW through a different system.  Perhaps the problem is on MEWs side blocking tor exit nodes.

**Comment by szymonlesisz** [comment]
yes, thats the question, we didn't change anything on our side so if 6 works 7 and 8 should too (its only a subdir)
could you try to do some operation here:
https://trezor.github.io/connect-explorer/#/method/ethereumGetPublicKey

**Comment by keraf** [comment]
Looks to be resolved, closing issue. Please re-open if that's not the case.
