### ISSUE TITLE
Problem signing a Transaction

### ISSUE THREAD

**Issue by matiu** [trezor/connect#6]
Trying to sign a transaction with the following arguments:

```
inputs:[{
address_n: Array[5]
0: -2147483604
1: -2147483648
2: -2147483648
3: 0
4: 0
prev_hash: "c543d6d7d2f2e13f340f7fc48a6b048dc91bd761acd6f21d13ccfdbf0d5c5af4"
prev_index: 1
}]

outputs: [{
address_n: Array[5]
0: -2147483604
1: -2147483648
2: -2147483648
3: 1
4: 0
amount: 14840
script_type: "PAYTOADDRESS"
,{
address: "3EPpjULHyMeNn6W4fLkCH5GGmyRdqeYY13"
amount: 20000
script_type: "PAYTOADDRESS"
}]
```
(sorry the format, captured from the browser's console).

Returns:
```
Object {success: false, error: "Encountered invalid prevhash"}
```

Any hint?

**Comment by prusnak** [comment]
@jpochyla any clues?

**Comment by jpochyla** [comment]
Somehow the tx from insight-api is not getting hashed properly, investigating.

**Comment by matiu** [comment]
please let us know if you need any more info.

**Comment by jpochyla** [comment]
This seems to be it! Can you confirm it fixes the testcase?

**Comment by matiu** [comment]
no, it is not working.

While not we get the screen at the device asking to confirm the transaction, afterwards the API response is:

```
{success: false, error: "Failed to compile output"}
```

**Comment by jpochyla** [comment]
The `script_type` of second output needs to be `PAYTOSCRIPTHASH`. All possible output script types are specified here:

https://github.com/trezor/trezor-common/blob/master/protob/types.proto#L47

`PAYTOADDRESS` is a little confusing name.

**Comment by matiu** [comment]
ok, worked, thanks! We will integrate multisig now.

Sorry the silly question.. This integration will work only on desktop
version, right?

On Mon, Sep 28, 2015 at 5:03 PM, Jan Pochyla <notifications@github.com>
wrote:

> The script_type of second output needs to be PAYTOSCRIPTHASH. All
> possible output script types are specified here:
>
> https://github.com/trezor/trezor-common/blob/master/protob/types.proto#L47
>
> PAYTOADDRESS is a little confusing name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trezor/connect/issues/6#issuecomment-143859572>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by jpochyla** [comment]
So far yes, but theoretically it's possible usb apis in mobile chrome could support our chrome extension. But now, only desktop.
