### ISSUE TITLE
Multisig output validation error

### ISSUE THREAD

**Issue by jlopp** [trezor/connect#606]
At Casa we've been using Trezor Connect v6 for several years. Recently, v6 started displaying version compatibility warnings that scare our users even though we haven't seen any compatibility issues.

We tried updating to TC v7 but when trying to sign a transaction it throws an error "Timestamp not enabled on this coin." TC v7 still shows the version compatibility warnings, so we're not really interested in getting this working.

We have also tried updating to TC v8 and it works fine for signing transactions with a single output, but when signing transactions with a change output it throws the following error: "Output 1 scripts differ"

I'm wondering if this might be related to https://github.com/trezor/connect/issues/520

To clarify, Casa is creating P2SH-wrapped P2WSH outputs.

Here's the logic we use for constructing change outputs; works with v6 but not v8:

```
          const change = {
            address_n: [account.keyPathPurpose, account.keyPathCoinType, keyPathAccount, changePath(true), tx.changeAddressPath],
            amount: `${output.value}`,
            script_type: 'PAYTOP2SHWITNESS',
            multisig: {pubkeys: outputNodes, signatures: [], m: account.requiredSignatures}
          };
```

**Comment by szymonlesisz** [comment]
could you provide some (not)working code for this?

**Comment by jlopp** [comment]
To be clear, the code above DOES work against Trezor Connect 6. It does NOT work when used with Trezor Connect 7 or Trezor Connect 8.

After further testing we have noticed that changing script_type to 'PAYTOADDRESS' then we are able to sign a transaction with Trezor Connect 8. It appears that something changed in the output validation logic that breaks validation for our P2SH-P2WSH change outputs.

**Comment by szymonlesisz** [comment]
it's highly possible since v6 had signTxValidation [commented out](https://github.com/trezor/connect/blob/v6/src/js/core/methods/helpers/signtxVerify.js) and thats why it is working

**Comment by szymonlesisz** [comment]
i understand that you dont want to paste your xpubs here, so you can remove them from fixtures
I just need inputs/outputs and other additional params (your xpubs will not work with my device anyway)

**Comment by szymonlesisz** [comment]
i think i've found this:
https://github.com/trezor/connect/blob/develop/src/js/utils/addressUtils.js#L87

this util ignores `PAYTOP2SHWITNESS` script_type :/

**Comment by szymonlesisz** [comment]
no, it's not it, you have problem with change output not external output (this util is for external)

what's your `account.keyPathPurpose` (should be 49' for PAYTOP2SHWITNESS, 48' for PAYTOMULTISIG see https://github.com/trezor/connect/blob/develop/src/js/utils/pathUtils.js#L65)

**Comment by jlopp** [comment]
Casa's change output paths are generally in the form of m/49/0/X/1/0

This issue is starting to sound a lot like https://github.com/trezor/trezor-firmware/issues/1044

The short version is that there really isn't consensus on specific derivation paths for multisig wallets and it seems controversial for hardware device libraries to be enforcing usage of specific paths. It sounds like if we want this to work then we'll have to forgo change output validation, which is unfortunate.

**Comment by szymonlesisz** [comment]
resolved by https://github.com/trezor/connect/pull/652
