### ISSUE TITLE
Add Cardano Shelley support and unable to run tests

### ISSUE THREAD

**Issue by gabrielKerekes** [trezor/connect#611]
Hi, we are working on updating Trezor to support the Cardano Shelley era to which Cardano should switch soon. You can see our Trezor issue [here](https://github.com/trezor/trezor-firmware/issues/948) or our [draft PR here](https://github.com/trezor/trezor-firmware/pull/1048). With Trezor being updated we also need to update Trezor Connect. 

I am curious to know, whether we can simply make the changes and submit a PR or whether you would like some say in it beforehand?

Also, I am trying to run the tests and I am unable to do so. I've tried many things, but in short this is what happens. I run

`yarn test -k -d -t cardanoGetPublicKey -e ../vl-trezor-firmware/core/ -b ../trezord-go/`

An emulator starts, asks me to wipe the device. I hold the button to wipe device, `Success` message gets sent from the emulator, however nothing further happens. It gets stuck. I feel like it might be some problem with debuglink and trezor bridge, but I am unable to identify the issue closer. I've tried running both the emulator and bridge separately, but it didn't help.

I also noticed there are jest tests. 

`yarn test:unit`

runs fine (but it it's unrelated to my changes). 

`yarn test:integration` 

fails with some obscure error in the script. 

`yarn jest --verbose -c jest.config.integration.js`

fails on `common.setup.js` on line 33 (`process.exit(1)`) - there's a comment above the line
`// this means that something in trezor-user-env got wrong.`
which doesn't really help me.

Running Trezor Core device tests on the emulator works without any issues.

Could you please help me run the tests? Not only would I like to update them along with the code, but it's also nice to be able to run them during development. 

If you need any further information, I'll be glad to provide it of course.

**Comment by szymonlesisz** [comment]
Hi @gabrielKerekes,
Looks like there were some changes in DebugLink (emulator) and python-trezor since FW 2.3.2 (tests works fine with 2.3.1) We need to implement those changes here, in python layer as well

I'll let you know here when its ready

**Comment by mroz22** [comment]
Hi @gabrielKerekes,
We have just updated our tests a little, not perfect yet but we are getting somewhere now. 

I managed to run tests againts custom firmware locally, some docs on it here: https://github.com/trezor/connect/blob/develop/tests/README.md

If you run on macOS, you may have problem running it locally, I haven't tried. If this is your case, I may add your draft firmware into our docker image and you will see results at least in travis.

**Comment by gabrielKerekes** [comment]
Hi @mroz22, thanks for your help. I am however still struggling to run the tests. I am running on Ubuntu btw.

I can run the tests without a custom firmware, that works fine. However, I am confused about what it is I am supposed to link to with the `-b` parameter. Do I:
1. Build custom firmware with the `build-docker.sh` command in the root of trezor firmware repo, rename `firmware.bin` to `trezor-emu-core-v2.9.9` and link to that?
**OR**
2. Build custom emulator by calling `make build_unix` in the `core` folder? What file/folder should I rename to `trezor-emu-core-v2.9.9` in this case? (I tried renaming and linking to `emu.py`, the whole `build` folder, the `micropython` file in `build/unix/` and even the `unix` folder)

With everything I've tried I get a message with `"code": "Transport_Missing"` as response in all the tests.

**Comment by mroz22** [comment]
Oh, I need to improve docs on it. But before I do..
in trezor-firmware repo

`pipenv sync`
`pipenv shell`
`cd core`
`PYOPT=0 pipenv run make build_unix_frozen`

now you should see core/build/unix/micropython executable. You may verify that you are able to run it  by `./micropython -m main` This should open emulator.

`cd build/unix`
`mv micropython trezor-emu-core-v2.9.9`

cd to trezor-connect

`./tests/run.sh -b ~/repos/trezor-firmware/core/build/unix/trezor-emu-core-v2.9.9 -f 2.9.9 -g -i getPublicKey`

So please try to use the micropython file.

**Comment by gabrielKerekes** [comment]
Yaay, this worked. Thank you!
