### ISSUE TITLE
Passphrase prompt with Metacat is not secure and annoying

### ISSUE THREAD

**Issue by blockomoco** [trezor/connect#617]
Hi,

When using Trezor with passphare and Metamask (via the chrome browser plugin) the passphrase needs to be typed in order to sign every single transaction.

There are 2 issues with this:

a) it is bad for security, because if someone tracks my keyboard they will get the passphrase. It is not possible to type in the passphrase on the device for the Metamask integration. And even if it was possible that brings us to the next point:

b) it is fairly annoying to re-type the passphrase over and over again. 

Is it possible to configure Trezor so that a passphrase does not need to be provided for each single transaction ? Or to whitelist certain services (like Metamask) so that the passphrase only needs to be provided once ? Or that it applies for a certain duration of time before needing to re-type it ?

Before typing the passphrase the following is displayed:
```
The current version of firmware (2.3.1) may be not compatible with the running version of Trezor Connect.
The current version of firmware contains major changes that could affect the efficient functionality of Trezor Connect.
```

which is why Im reaching out to this subproject (aka Trazor Connect).

**Comment by szymonlesisz** [comment]
Hi @blockomoco ,
Like you've noticed Metamask doesn't implement newest TrezorConnect version. Thats why your passphrase state is not persistent and you are not able to type passphrase on your device. 
Tbh there is nothing much we can do about it. We've already inform them two months ago, yet still no response: https://github.com/MetaMask/metamask-extension/issues/8349
