### ISSUE TITLE
handling pin creation

### ISSUE THREAD

**Issue by curve-25519** [trezor/connect#625]
hello again!

having trouble setting a pin due to 'pin mismatch' errors. assuming the two matrices i am given look as follows:

```
215
794
638
```
and:
```
873
451
926
```

lets say i want to keep things simple and use a pin of `2222`. the `uiResponse` payload I send back should simply be `1111` for the first response and `8888` for the second, correct? this doesnt seem to work for me but neither does sending back the real pin (`2222`) each time. what am i doing wrong here?

**Comment by curve-25519** [comment]
the calling function, just in case you are wondering:

```javascript
TrezorConnect.uiResponse({type: UI.RECEIVE_PIN, payload: String(this.pin.value)}); // this.pin.value is a string of numbers
```

**Comment by mroz22** [comment]
Numeric keyboard mapping is used. See here: https://github.com/trezor/trezor-firmware/tree/master/python#pin-entering

**Comment by curve-25519** [comment]
@mroz22 fantastic. glad it was something really simple. thank you!
