### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jameshilliard** [trezor/connect#661]
I noticed that connect was re-licensed from `LGPL-3.0+` to `T-RSL` in #234, however it doesn't appear that contributions to the connect project prior to this change were licensed under anything other than `LGPL-3.0+` which is a copyleft license that generally can't be changed without obtaining permission from all project contributors.

Were contributor license agreements obtained from all outside connect contributors in order to re-license connect to `T-RSL`?

**Comment by prusnak** [comment]
Hi James!

Before 19th of October 2018, when the change happened, there were just a handful (5 to be exact) of external contributors to the project. I remember discussing this with them over email/gitter and there was no opposition to the change.

**Comment by jameshilliard** [comment]
@prusnak Generally you would want to obtain CLA's from them in order to ensure the license change is valid. Asking for objections alone is probably not sufficient.

**Comment by husticdf** [comment]
Related question - my understanding is that the license would prohibit bundling trezor-connect in a Web GUI produced by one company and then sold to another company.

"...specifically excludes the right to distribute the software outside of your company."

Would my understanding be correct?

**Comment by prusnak** [comment]
> Would my understanding be correct?

Correct. The company in question might be able to contact us and negotiate alternative distribution terms, of course.
