### ISSUE TITLE
Bug: Show passphrase is broken

### ISSUE THREAD

**Issue by keraf** [trezor/connect#664]
### Description
Clicking on "Show passphrase" shows the value from the passphrase input into the confirm passphrase input when revealing it. When unchecking "Show passphrase", it empties the confirm passphrase input. When the input is not identical/empty in the confirm passphrase field, checking "Show passphrase" can be used to copy the first input into the second one and pass the passphrase match check.

**Video**
[![Video](https://img.youtube.com/vi/9ba6l2cMDp4/0.jpg)](https://youtu.be/9ba6l2cMDp4)

### Steps to reproduce
1. On connect explorer, execute a method that requires a passphrase input (GetAddress for example).
2. Go to the step where the passphrase is requested.
3. Enter any text into the first input (passphrase).
4. (optional) Enter a different text into the second input (passphrase confirm).
5. Check "Show passphrase".
6. Observe (1.).
7. Uncheck "Show passphrase".
8. Observe (2.)

### Observation
1. The second input is overwritten by the first one when "Show passphrase" is checked. This also validates the passphrase match check.
2. The second input is now emptied.

### Intended behavior
Display the passphrases as entered when "Show passphrase" is checked. When unchecking it, leave the values as entered.

### Additional info
- **OS:** Ubuntu 20.04
- **Browser:** Firefox 79.0 (64bit)
- **Bridge:** 2.0.30
- **Device:** Trezor One (fw 1.9.2)

**Comment by waltonzt** [comment]
@keraf Is this still an issue you want someone to look into? If so I can take a look at it. Might need to ask some questions about how to add a password to the emulator in `trezor-user-env` if that is possible.

**Comment by tsusanka** [comment]
We will completely redesign connect-popup in https://github.com/trezor/trezor-suite/issues/4363 let's leave it for that. Thanks @waltonzt for the offer, we failed to respond, sorry 😢.
