### ISSUE TITLE
Get uuid and name of Trezor device

### ISSUE THREAD

**Issue by benjaminlim00** [trezor/connect#668]
Hi, does this library provide anyway of retrieving the uuid and name of the Trezor device?

**Comment by keraf** [comment]
Hi, 

You can use `TrezorConnect.getFeatures()` that will return you some information about the device such as a the deviceId and label.

**Comment by benjaminlim00** [comment]
Thank you :) Why is it not included under [https://github.com/trezor/connect/blob/develop/docs/methods.md](url)?

**Comment by keraf** [comment]
A few methods are currently missing in the documentation, I'll be looking to get them added soon. Created issue trezor/trezor-suite#4872 to track that task.
