### ISSUE TITLE
TrezorConnect.composeTransaction fix fee mode

### ISSUE THREAD

**Issue by benjaminlim00** [trezor/connect#674]
Hi, is it possible to call TrezorConnect.composeTransaction with a predetermined fee price type? I would like to call the method such that the user does not get to choose the fee price type (fixed on high) so as to push the transactions to be mined sooner

**Comment by keraf** [comment]
Hi @benjaminlim00, the documentation is not entirely up to date (see trezor/trezor-suite#4872) but if you look at the methods in the project, you should be able to see the parameters. I haven't digged too deep myself but I believe you can pass `feeLevels` (array). I would recommend looking at the tests to see actual use of these methods.

Unfortunately, as the documentation is not up to date yet, I can only recommend looking at the method definitions and tests for anything that isn't documented. Hopefully we'll get it updated soon.

**Comment by szymonlesisz** [comment]
usage of custom FeeLevels in composeTransaction is limited to a certain mode.
This method works in two modes:
1. [composing with device](https://github.com/trezor/connect/blob/develop/src/ts/types/account.d.ts#L225-L229), with guide thru every step: account selection, fee selection (levels are generated automaticaly)
2. [precomposing without device](https://github.com/trezor/connect/blob/develop/src/ts/types/account.d.ts#L186-L197), utxo selection and calculation
