### ISSUE TITLE
Multiple account discovery with single browser prompt

### ISSUE THREAD

**Issue by refi93** [trezor/connect#679]
I was trying to get account xpubs for multiple (Cardano) accounts with Trezor connect via the `cardanoGetPublicKey` call and I get a new prompt in the browser for each account number respectively (account 1, account 2, etc)  which could be annoying to the user if they have several accounts, especially for a web wallet that does not "remember" already derived account xpubs across different visits of the site, making the user go through the process each time they visit the site.

Is there a generic way to authorize Trezor to return multiple account xpubs prompting the user only once? If not, do you know how/if BTC or other crypto-currency (web) wallets without persistent storage are dealing with this?

**Comment by keraf** [comment]
Hi @refi93,

Could you provide some code please?

The documentation for `cardanoGetPublicKey` show an example for getting public keys of multiple accounts:
```javascript
TrezorConnect.cardanoGetPublicKey({
    bundle: [
        { path: "m/44'/1815'/0'", showOnTrezor: false }, // account 1
        { path: "m/44'/1815'/1'", showOnTrezor: false }, // account 2
        { path: "m/44'/1815'/2'", showOnTrezor: false }  // account 3
    ]
});
```

**Comment by refi93** [comment]
I see - sorry, I skipped on reading the docs and that's exactly what I was looking for, thank you!

My original idea was to not request the xpubs upfront but allow for sequential discovery as described in BIP44 (https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery) and just "pre-authorize" the individual requests for xpubs but after a second thought there aren't probably much benefits to that if any - in the end you need to know the range of accounts you are going to explore anyway, to make that hypothetical "pre-authorization" request.
