### ISSUE TITLE
secure popup window fails to work with Icecat

### ISSUE THREAD

**Issue by wanderer** [trezor/connect#683]
The secure popup window tries to force the user to use chrome or firefox. Icecat is a fork of firefox so it should work.

**Comment by keraf** [comment]
There are no immediate plans to support more browsers. I would still think it would be a good idea to change the message into a warning and leave the option for the user to proceed with an unsupported browser.

**Comment by prusnak** [comment]
You can use the [UserAgentSwitcher](http://chrispederick.com/work/user-agent-switcher/) extension mentioned here: https://www.gnu.org/software/gnuzilla/addons.html to change the UA to Firefox. This should do trick. If it doesn't, please use Firefox.
