### ISSUE TITLE
Question: Rebuilding protobuf messages

### ISSUE THREAD

**Issue by refi93** [trezor/connect#691]
I noticed the `make protobuf` command in this repo regenerates `./src/data/messages/messagesN.json`

https://github.com/trezor/connect/blob/b4ece42257d749ea2259468fa974ebced0ed18c8/Makefile#L53

I have two questions:

1. Why doesn't it update directly messages.json?
2. If I'm locally developing and modifying the protobuf messages, should I just overwrite messages.json with messagesN.json or am I supposed to call something different in order to use those updated protobuf messages?

**Comment by szymonlesisz** [comment]
i'm not 100% sure but if i remember correctly it's generated as a new untracked file to avoid potential bug during the build. 
while developing locally you can temporary set it to:

./node_modules/.bin/proto2js ./[your-local-path-to]/trezor-firmware/common/protob/combined.proto > ./src/data/messages/messages.json
