### ISSUE TITLE
How to use Trezor Connect in a web worker?

### ISSUE THREAD

**Issue by Mrtenz** [trezor/connect#697]
In web workers, elements like `window` and `document` aren't available. It seems that Trezor Connect relies on `window` to create the popup, so trying to use it in a web worker results in:

```
ReferenceError: window is not defined
    at new PopupManager (677dbfc884ba1416c228.worker.js:40290)
    at initPopupManager (677dbfc884ba1416c228.worker.js:38721)
```

Is there any other way to do this? WebUSB if that's not limited to just trezor.io only anymore (#511)?

**Comment by szymonlesisz** [comment]
Hi @Mrtenz ,

currently there is no possibility to use TrezorConnect in a web worker since the whole code is running and relays on window elements like `iframe` and `window.open` (popup)
