### ISSUE TITLE
Bower.io works with "Releases" on GitHub

### ISSUE THREAD

**Issue by cmgustavo** [trezor/connect#70]
Installing trezor-connect with `bower install` failed because your Github repo hasn't any release.

**Comment by runn1ng** [comment]
We don't actively use bower for releasing.

I will remove trezor-connect from bower later. Sorry for the confusion.

**Comment by craigmacgregor** [comment]
You can specify the commit instead to get it to work:

"trezor-connect": "https://github.com/trezor/connect.git#c1a00f9f0f4a13239ba13ddd589c6ca61f2e7876",

(taken from bitpay/copay bower.json)
