### ISSUE TITLE
Option to prioritize passphrase insertion on device (in nodejs)

### ISSUE THREAD

**Issue by refi93** [trezor/connect#714]
We are implementing a CLI app in nodejs (https://github.com/vacuumlabs/cardano-hw-cli) using trezor connect and we noticed that if the device has passphrase protection enabled, it prompts the user to enter it in the browser which effectively locks them out as they are not in a browser, so there is no option to switch to insertion of the passphrase on the device.

Is there a way to force passphrase insertion on the device upfront? So far, we were only able to tweak connect to bypass the popup promise in the onDevicePassphraseHandler and hard-wire passphraseOnDevice to be true https://github.com/trezor/connect/blob/63ad13f46a8a8ae2cb2fdaa06f478757fccb1102/src/js/core/Core.js#L700 which is not pretty, of course and means we would need to maintain our own version of connect.

Would it be possible to add nodejs detection or some flag into the `init()` call of TrezorConnect? Or should we be using a completely different library/approach to interact with Trezor in nodejs? Is there perhaps already a call/flag to achieve what we want and we are just missing it?

link to our internal workaround PR for reference: https://github.com/vacuumlabs/connect/pull/5

Possibly, a more robust approach, that would work with Trezor One as well (which does not support passphrase insertion on the device) would be allowing to pass the passphrase when connect initializes/wrap connect calls in a function that awaits on a promise that fullfills right away if no passphrase is enabled, or awaits passphrase insertion (in whatever way - would be up to the integrating party) and passes it down to Trezor Connect, alternatively passing the flag that the passphrase should be inserted on the device

**Comment by szymonlesisz** [comment]
hi @refi93 
yes, there is a way how to force it.

you can detect if device has "passphrase on device" support.
after receive UI.PASSPHRASE_REQUEST event do:
```
const passphraseOnDevice = !!(
        device.features &&
        device.features.capabilities &&
        device.features.capabilities.includes('Capability_PassphraseEntry')
);
```

and respond with:

```
TrezorConnect.uiResponse({
        type: UI.RECEIVE_PASSPHRASE,
        payload: {
            value: '',
            save: true,
            passphraseOnDevice,
        },
    });
```

**Comment by szymonlesisz** [comment]
mentioned `getPopupPromise()` is not related to the `window` object. name of the function may be confusing, but it works in  in `nodejs` as well. connect is just waiting for `TrezorConnect.uiResponse` to be called

all you have to do is implement all `UI.EVENTS` like:
```
UI.REQUEST_PIN // T1
UI.REQUEST_PASSPHRASE
UI.REQUEST_PERMISSION
```
and respond with TrezorConnect.uiResponse:

```
UI.RECEIVE_PIN // T1
UI.RECEIVE_PASSPHRASE
UI.RECEIVE_PERMISSION
```

**Comment by refi93** [comment]
Thanks @szymonlesisz Based on an example I found (https://github.com/trezor/connect/blob/63ad13f46a8a8ae2cb2fdaa06f478757fccb1102/examples/electron/main-process/src/trezor-connect-ipc.js#L46) I tried implementing a simplistic UI event handler like this:

```
TrezorConnect.on(UI_EVENT, (event) => {
    if (event.type === UI.REQUEST_PASSPHRASE) {
      if (event.payload.device.features.capabilities.includes('Capability_PassphraseEntry')) {
        TrezorConnect.uiResponse({ type: UI.RECEIVE_PASSPHRASE, payload: { passphraseOnDevice: true, save: true, value: '' }      })
      }
    }
  })
```

And the passphrase insertion prompt is not triggered on the device and it still shows on Trezor the prompt to insert it in the browser, even though the `UI.REQUEST_PASSPHRASE` event seems to be triggered after I make a call to Trezor to e.g. `cardanoGetPublicKey`. Interestingly, if I wrap the `TrezorConnect.uiResponse()` in `setTimeout()` with 0ms delay, it works as expected and the passphrase prompt is triggered on the device. Do you know why would I observe such weird behavior?

**Comment by szymonlesisz** [comment]
looks like some race condition in promises.

try to change those lines in your local connect:
https://github.com/trezor/connect/blob/develop/src/js/core/Core.js#L703-L707

to:
```
    // create ui promise
    const uiPromise = createUiPromise(UI.RECEIVE_PASSPHRASE, device);
    // request passphrase view
    postMessage(UiMessage(UI.REQUEST_PASSPHRASE, { device: device.toMessageObject() }));
    // wait for passphrase

    const uiResp: UiPromiseResponse = await uiPromise.promise;

```

if it helps i will fix that globally in connect

**Comment by refi93** [comment]
@szymonlesisz I pulled the latest commit in develop with the fix you proposed above and it works, thank you!
