### ISSUE TITLE
What happens if https://connect.trezor.io is compromized?

### ISSUE THREAD

**Issue by onemanstartup** [trezor/connect#72]
I have a client and I implementing authentication through trezor and he want fully autonomous authentication. He fears if we connecting to other servers they can be compromised. 

Will it be more safe if I take connect.js and popup.html and serve them on my server? And will people trust us if we serve this files on our side?

**Comment by jcalfee** [comment]
Agreed .. I would also add: I can't in good conscienceless build an app using this lib knowing that if trezor.io is not available it will not work.  I realize that I can install a trezord but that makes the barrier to entry that means my tool will not be used.

A browser only implementation that works purely between the browser and the device is a requirement for any long standing app that will be assured to work in the future even after trezor decides to end support for something.

**Comment by prusnak** [comment]
We are working on a rewrite of Connect which would allow you to embed Connect into your application code. Stay tuned.

**Comment by prusnak** [comment]
Also there is no need to use TREZOR via anything hosted on trezor.io. There are [python](https://github.com/trezor/python-trezor) and [Javascript](https://github.com/trezor/trezor-link) libraries available and one can use these to interact with the device via low-level means.

**Comment by jcalfee** [comment]
Thank you ;) .. FYI:  The node version gives me a hard time in Node 8 and I really couldn't get it it work on a RAM only bootable USB (in several distros).  I'm giving up on that.  Python would probably be much better but still requires special setup.  I'm putting my money on the browser.  It would be good to have a full implementation running in the browser ..

**Comment by onemanstartup** [comment]
@prusnak It's actually doesn't address the issue. If I host connect.js on my site and popup asks for the pin code, I have ability to know this pin code. 
What is ETA for rewrite of connect.js?

**Comment by prusnak** [comment]
No, you will not know the PIN, because what is transferred to TREZOR is just positions, not the actual PIN. I suggest you to try it and watch the messages.
