### ISSUE TITLE
Running integration tests with custom firmware

### ISSUE THREAD

**Issue by refi93** [trezor/connect#723]
I noticed that the current [tests/run.sh](https://github.com/trezor/connect/blob/95f9ee7bc2739db4812d33aaf974cd3e7eccda0f/tests/run.sh) script does not include the `-b` option to use a custom-built trezor firmware even though the [README](https://github.com/trezor/connect/blob/95f9ee7bc2739db4812d33aaf974cd3e7eccda0f/tests/README.md) still mentions it. Will the `-b` option appear again or is there already an alternative to it?

**Comment by szymonlesisz** [comment]
yeah, since we've switched to a different setup it's not possible right now.
I've created an issue for that
https://github.com/trezor/trezor-user-env/issues/49

the only workaround for now is to manually replace firmware binary in `trezor-user-env` docker image

**Comment by tsusanka** [comment]
https://github.com/trezor/trezor-user-env/issues/49 is done, closing here 🎉 .
