### ISSUE TITLE
case signethmsg missing on popup.js

### ISSUE THREAD

**Issue by Zwilla** [trezor/connect#73]
please update popup.html => popup.js (LiVE)

thx

p.s. will test the signmsg if it also works for eth

missing on Version2 and Version3 !

**Comment by szymonlesisz** [comment]
Hi,
it wasn't meant to be in version2, but it's available in version3. 
You can find it documentation but we've forgot to put it into examples list. 
You can test it here:

https://connect.trezor.io/3/examples/signmsg-ethereum.html

**Comment by Zwilla** [comment]
I know about version 3, but I opened this issue because I get this error:
{
  "success": false,
  “error": "Unknown message"
}

also with your example, all other examples are working.
And thx for that fast respond!

**Comment by prusnak** [comment]
You need to have current firmware (1.5.1 and newer) loaded in your device. Older versions did not have this functionality.

Maybe it Connect should throw an error if an older version (before 1.5.1) in device is detected?

**Comment by szymonlesisz** [comment]
I will add this exception to example

**Comment by Zwilla** [comment]
Hope that’s it. I saw that on my trezor (delivered before a few day’s) is only version 1.5.0 installed.

And no there come no ‘Upgrade Message’.

Also it will be cool if there comes also the message if trezor is connected to an other session :)

**Comment by szymonlesisz** [comment]
New firmware 1.5.2 was released yesterday.
To get an upgrade just go to https://wallet.trezor.io/ and follow the instructions.
More info here:
https://blog.trezor.io/trezor-firmware-security-update-1-5-2-5ef1b6f13fed

**Comment by Zwilla** [comment]
Great, now I have an other thing:
I think will be a good idea to not allow shared sessions. 
At moment it is possible. I think it is better after closing a website to close also the session from trezor.

clearSession

**Comment by szymonlesisz** [comment]
I'm not sure what you mean by that.
There are no shared sessions in connect.
App flow works like (in short):
open popup > get session > do something > return result > release session > close popup

**Comment by runn1ng** [comment]
@szymonlesisz: @Zwilla probably means Trezor sessions, not Trezor Daemon sessions.

I was under the impression that we call clearSession at the end of every action though.

**Comment by Zwilla** [comment]
clearSession calls this.trezorJsDevice.clearSessionRest()

**Comment by Zwilla** [comment]
cool, now the process has changed, so that I have to enter a second time my 4digit! 👍

**Comment by szymonlesisz** [comment]
There were no changes so far :) 
Pin is cached in your device for 15 minutes after that time it clear itself, that's why device ask for it again.
We agreed on that we don't want to have automatic clearSession after popup close.
The best example is working with myetherwallet where you need to pair your device and account (eth address) every time you want do something (send, sign message, view account etc.)
It will be annoying if we will force you to enter pin and password every time you change page.

**Comment by Zwilla** [comment]
Ok, I think I will make a video and then you will see which security concerns I (and every other also) have.
WARNING! Do this only with a testing Trezor! Need HwVersion 1.5.2
Step by step:
* open https://myetherwallet.comsignmsg.html (Tab1)
* open https://mytokenwallet.com/signmsg.html (Tab2)
* connect your Trezor on (Tab1) and than on (Tab2)
* sign a message (just for testing) on (Tab1) and on (Tab2)
* open https://wallet.trezor.io/

Ok: now you see that I can open the other sites without entering into a new trezor session!

p.s. I’working on osx safari

**Comment by Zwilla** [comment]
‘It will be annoying if we''ll force you to enter pin and password every time you change a section'

SURE!

But if I change the WebSite it have to. Or not? Just watch this video and you see live what I mean.

http://www.youtube.com/watch?v=LLtqKgwIWDU

**Comment by runn1ng** [comment]
As @szymonlesisz said. It's not a security issue. You still need to confirm the message, the transactions, etc. on your device.

If we made clearSession after every action, the user would need to enter PIN repeatedly all the time.

Right now, Trezor itself clears session after about 15 minutes of inactivity. So even if you do enter PIN in one window, it will want PIN again after 15 minutes.

In the end, you are still the same user who entered the PIN the first time, so we already authenticated it's you. You still need to confirm all the actions.

**Comment by runn1ng** [comment]
The point is, you should not trust the website or the computer - you should check what is on the TREZOR screen and confirm *that*.

On Trezor Wallet, you can explicitly call clearSession, by clicking on the "small lock" near the name of the device. We might add a function to Connect that exports this, that's not a bad idea actually, but we won't do it by default.
