### ISSUE TITLE
Waiting for XinFin-XDC Network support in Trezor

### ISSUE THREAD

**Issue by AaditiGirkar** [trezor/connect#735]
Hello Team,

Please have a look at the XinFin-network use cases, The XinFin blockchain utilizes the XinFin Delegated Proof-of-Stake consensus(XDPoS) mechanism for smoother digitization of industrial processes and almost-instant trade settlement.

We are waiting for XinFin-XDC Network support Trezor.

Github:- https://github.com/XinFinOrg/XDPoSChain
CMC :- https://coinmarketcap.com/currencies/xinfin-network/
Circulating Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=getcirculatingsupply
Total Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=totalXDC
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Integration Code example: https://xinfin.org/exchange-listing-resource

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/

Happy to talk commercials as well as ready to support with large XinFin Community members support to grow adoption with your team.

**Comment by prusnak** [comment]
We already told you we are adding coins only in TOP30 on Coinmarketcap: https://github.com/trezor/trezor-suite/issues/3201

**Comment by AaditiGirkar** [comment]
Thanks for response. The request isn't coming from project team but over 15,000 strong #XDC community. We will share with them this link if they keep asking.
