### ISSUE TITLE
Passphrase-activated Trezor connectivity without UI/browser access

### ISSUE THREAD

**Issue by apalepu23** [trezor/connect#739]
Hey all!

We were interested in using trezor-connect (trezor-connect-extended to be specific) programmatically to allow users to run node scripts for signing/submitting transactions to Ethereum after connecting their Trezor. 

These scripts should be able to run without the need for any browser embeds or UI popups. Things are working perfectly for the standard Trezor set up using a fairly standard `TrezorConnect.init` initialization. However, when setting up a hidden wallet on the Trezor, things seem to not be working as expected. My understanding is that setting up a passphrase allowing for the creation of additional hidden wallets explicitly creates a "blank" passphrase for the initial account as well of "". 

It wasn't immediately obvious to me how to pass in this empty passphrase for the first account, or an arbitrary passphrase for any other hidden wallets, in the `TrezorConnect.init`. Is there a configurable parameter to achieve this there or in some other location? If this doesn't exist, would we be able to support this type of interaction since it's important to have this kind of interaction supported without needing any browser/UI popups?

Thanks!

**Comment by szymonlesisz** [comment]
Hi @apalepu23 ,
It is described in the [common params docs](https://github.com/trezor/connect/blob/develop/docs/methods/commonParams.md)
If you don't want to use hidden wallet (passphrase) then you should set `useEmptyPassphrase: true` for your call, like:

```
TrezorConnect.ethereumSignTransaction({
 ...your params,
 useEmptyPassphrase: true,
 });
 ```
