### ISSUE TITLE
Forbidden key path when signing an Ethereum transaction with a valid BIP44 path

### ISSUE THREAD

**Issue by elias-garcia** [trezor/connect#744]
Hi, I'm trying to sign an Ethereum transaction using a Trezor Model T but I'm getting this result from the library:

```js
{
  id: 10
  payload: {
    error: "Forbidden key path",
    code: "Failure_DataError"
  }
  success: false
}
```

After constantly getting this error I just tried to build a minimal example and I come up with this code (copied from the example of the `ethereumSignTransaction` docs), but it's also failing with the same error:

```js
TrezorConnect.ethereumSignTransaction({
  path: "m/44'/60'/0'/0/0",
  transaction: {
    to: "0x7314e0f1c0e28474bdb6be3e2c3e0453255188f8",
    value: "0xf4240",
    data: "0x01",
    chainId: 3,
    nonce: "0x0",
    gasLimit: "0x5208",
    gasPrice: "0xbebc200",
  },
}).then(console.log);
```

However, when I call `ethereumGetAddress` or `ethereumSignMessage` with the same derivation path, the function call succeeds. As far as I know I'm using a valid BIP44 derivation path and this is only happening with this specific method. Any idea about what's going on?

PS: I have the Trezor Bridge `2.0.27` installed on my Mac and my Trezor Model T device is updated to the `2.34` firmware version.

**Comment by prusnak** [comment]
Correct path for Ropsten (chainId=3) is  `"m/44'/60'/1'/0/0"` (Ropsten is a testnet, so SLIP44 mandates coin type = 1 in BIP44 path).

**Comment by elias-garcia** [comment]
I didn't know that, thanks a lot for the explanation! 

EDIT: The correct path is: `"m/44'/1'/0'/0/0"` not `"m/44'/60'/1'/0/0"`, it's working perfectly now.

**Comment by aloisklink** [comment]
For prosperity's sake, if you do need to use an invalid SLIP44 path for testnets (for example, you're trying to make a testnet transaction in MetaMask), `trezorctl` can be used to raise a prompt on the Trezor Model T, allowing you to override this safety check.

See https://github.com/trezor/trezor-firmware/issues/1474#issuecomment-792048438
