### ISSUE TITLE
Print version at HTML index

### ISSUE THREAD

**Issue by tsusanka** [trezor/connect#749]
Could we print the current version at https://connect.trezor.io/8/? In another words at the HTML homepage. It would be useful to quickly check what version is deployed. Or is there any other simple way to find out?

**Comment by prusnak** [comment]
We can add it there as well, but there's already an easy way how to check the version:

```
curl -s https://connect.trezor.io/8/trezor-connect.js | grep VERSION
```

**Comment by tsusanka** [comment]
Oh that's nice, I think that is more than enough. Added to readme in eeebf7f4.
