### ISSUE TITLE
New error using v8.1.20

### ISSUE THREAD

**Issue by Scotty0448** [trezor/connect#750]
My web wallet that supports Trezor in no longer working to sign transactions. Calling TrezorConnect.signTransaction is resulting in an error of "Parameter "amount" is missing."

I even get the same error when using your own test page at https://trezor.github.io/connect-explorer/#/method/signTransaction-paytoaddress when selecting Bitcoin.

**Comment by prusnak** [comment]
Right, thanks for the notice! I've reverted connect on connect.trezor.io to 8.1.19 for now.

**Comment by Scotty0448** [comment]
Yep, it works now.  Thank you for always providing such incredible support!

**Comment by prusnak** [comment]
Next release will deal with the missing amount field
