### ISSUE TITLE
Preventing forward compatibility issues

### ISSUE THREAD

**Issue by refi93** [trezor/connect#751]
In Cardano we recently added multiasset support/minValidity field (https://github.com/trezor/connect/pull/745) which extends the existing protobuf messages with new fields. This works nice with old trezor-firmware (2.3.4) until a user attempts to sign a transaction containing those new fields. The expected behavior would be that Trezor rejects such transaction as it contains unknown fields that it cannot serialize into the tx, but instead (due to the way protobuf is designed) it proceeds to gracefully sign a transaction without those fields which is invalid at best and lacking some crucial information at worst (e.g. the min validity start field, effectively disabling the time lock on the signed tx).

Is there any better way to prevent such forward compatibility-related issues than explicitly checking the trezor firmware version client-side? Am I perhaps missing some pattern/helper function inside trezor-connect where we could specify since which version of Trezor firmware does given field work and throw if a message with that field is passed?

I guess it's loosely related to https://github.com/trezor/trezor-firmware/issues/1438

**Comment by szymonlesisz** [comment]
Hi @refi93, actually there are two ways: 
- we can [globally exclude](https://github.com/trezor/connect/blob/develop/src/data/config.json#L125) `cardanoSignTransaction` method for FW lower than 2.3.5, then user will be forced to install the newest version of firmware (> 2.3.4) 
- we can add a [runtime validation](https://github.com/trezor/connect/blob/develop/src/js/core/methods/CardanoSignTransaction.js#L45):  throw an error if FW < 2.3.5 and params are not supported (params object contains new messages)

**Comment by refi93** [comment]
@szymonlesisz I see, runtime validation seems like the way to go so wallet clients can already safely update to the newest version of connect without breaking support with the currently launched Trezor fw - do you have a live example of such runtime validation we can replicate or should we just create an ad-hoc helper function using `this.device.atLeast()` to return whether given feature is supported on the device being interacted with? Also, is there some standard exception to throw in that case? The closest I found was a check inside the `LoadDevice` method: https://github.com/trezor/connect/blob/eeebf7f407e402fb0d1759bbfa6d9cc17d182c71/src/js/core/methods/LoadDevice.js#L72-L80

So not sure if I'm missing something more straightforward used for coin-related calls.

Of course, if you can add it yourself as hinted in your response, and it doesn't take you too much time, that would be great, feel free to include me as a reviewer in that case

**Comment by refi93** [comment]
Created PR with proposed solution and a minor bug fix in params validation: https://github.com/trezor/connect/pull/753/files
