### ISSUE TITLE
Trezor connect login issue

### ISSUE THREAD

**Issue by hoangan** [trezor/connect#76]
I tried out the login example. The popup stuck at Loading... forever. 

![screen shot 2017-09-20 at 11 50 26 am](https://user-images.githubusercontent.com/1736330/30627405-38523d8e-9dfa-11e7-85a0-c7fffa016f2d.png)

The error in the JS console is: 

```javascript
popup.js:151 Uncaught TypeError: Cannot read property 'substring' of undefined
    at parseIdentity (popup.js:151)
    at onMessage (popup.js:75)
```

Any idea how to fix it?

Thanks

**Comment by runn1ng** [comment]
Weird

Have you tried v3?

https://connect.trezor.io/3/examples/login.html

**Comment by runn1ng** [comment]
The error seems to be from here

https://github.com/trezor/connect/blob/v2/popup/popup.js#L145

It's strange that it's not working. What is your browser? Are you running it from the web, or from local disk?

**Comment by hoangan** [comment]
Hi,

I run from local disk. Does it need a server with a cert to run? I'm guessing. 
Thanks
An

**Comment by runn1ng** [comment]
Yeah, it does, for login, so it knows the website you are logging into

**Comment by hoangan** [comment]
Would it work for local server with self-signed cert?

**Comment by runn1ng** [comment]
It should. Please try and report, how it works for you

**Comment by hoangan** [comment]
Ok, thanks. I will try it out 👍

**Comment by hoangan** [comment]
It works with local server and self signed cert.
