### ISSUE TITLE
paramsValidator and optional types

### ISSUE THREAD

**Issue by refi93** [trezor/connect#770]
Currently the paramsValidator helper used mostly to validate the message payloads doesn't seem to support optional types in the sense that the value itself would be null - either the key is completely missing or it is present and has the given type.

https://github.com/trezor/connect/blob/d38be2d259a2be87dbadfd2a24e476ed2cabe247/src/js/core/methods/helpers/paramsValidator.js#L22

Is that intended? Because it makes the integrations dealing with optional values kind of awkward, requiring them to delete null keys from the object before passing it to connect.

Moreover, the meaning of "obligatory: false" can be seen as kind of misleading as somebody may (imho legitimately) expect that is equivalent to the value being "optional", hence wrongly supposing a key having a null value passes just fine through the validation.

Would it make sense to add to paramsValidator an "allowNull" flag alongside "allowEmpty" to allow for a null value to be passed without breaking the existing validation rules? Or is there already some cleaner way to achieve the desired handling of null/undefined values that I'm just missing?

**Comment by szymonlesisz** [comment]
Hi @refi93,
you are totally right in both cases
i'm currently looking for some better way to do params validation, like some json schema or something...
i already tried multiple approaches with multiple trending libs but unfortunately none of them is 100% satisfying. just too much overhead.

i guess i'll just fix current validation utility then by allowing `null/undefined` and renaming `obligatory` to `required`

**Comment by gabrielKerekes** [comment]
@szymonlesisz are there any updates on this please?

**Comment by szymonlesisz** [comment]
hi @gabrielKerekes 
i've refactored `paramsValidator` ef1978cb85ccdea961c3adffb1d4fea6df81928d
renamed `obligatory` to `required` 92f618a49e545c9b84397ed1ada7dd4ce64735b4
and renamed `paramsValidatior` type `amount` to `uint` 95ace8c2596b670be7315a75dce6781f136aaf59

**Comment by davidmisiak** [comment]
> hi @gabrielKerekes
> i've refactored `paramsValidator` [ef1978c](https://github.com/trezor/connect/commit/ef1978cb85ccdea961c3adffb1d4fea6df81928d)
> renamed `obligatory` to `required` [92f618a](https://github.com/trezor/connect/commit/92f618a49e545c9b84397ed1ada7dd4ce64735b4)
> and renamed `paramsValidatior` type `amount` to `uint` [95ace8c](https://github.com/trezor/connect/commit/95ace8c2596b670be7315a75dce6781f136aaf59)

Thank you very much, we tested the new `paramsValidator` behavior in `cardano-hw-cli` and it seems to work perfectly.
