### ISSUE TITLE
Passphrase request on the device is not working sometimes

### ISSUE THREAD

**Issue by tomislavhoracek** [trezor/connect#783]
**Issue:** We are forcing passphrase on the device (on passphrase request event) and we are not using trezor-connect popup for that.

So, we are using this:

```
TrezorConnect.uiResponse({
    type: UI.RECEIVE_PASSPHRASE,
    payload: { value: '', passphraseOnDevice: true },
});
```

It works In most cases but sometimes a passphrase is not requested on the device and the message _"Please type your passphrase on the connected host"_ is shown. There is also a console error.

<img width="1135" alt="Screen Shot 2021-03-19 at 11 22 24" src="https://user-images.githubusercontent.com/18653950/111777212-48fd1080-88b3-11eb-9f44-1bb617ab1b0b.png">

Probably this is related to:
trezor/trezor-suite#4874

Device: Trezor Model T
Firmware: 2.3.6
JS lib: trezor-connect: "8.1.22-extended" (for Electron)

Thanks in advance!

**Comment by szymonlesisz** [comment]
hi @tomislavhoracek, try with connect 8.1.25-extended 
i beleive this was fixed by this PR:
https://github.com/trezor/connect/pull/763

**Comment by tomislavhoracek** [comment]
@szymonlesisz Thanks. We will try.

**Comment by szymonlesisz** [comment]
is this still an issue? can i close it?

**Comment by szymonlesisz** [comment]
closing since referenced issue is also closed
