### ISSUE TITLE
integration docs not using newest version of trezor connect

### ISSUE THREAD

**Issue by nnmfnwl7** [trezor/connect#787]
As main page https://github.com/trezor/connect so file README.md pointing integrator to Integration docs https://github.com/trezor/connect/blob/develop/docs/index.md , instructions says <script src="https://connect.trezor.io/7/trezor-connect.js"></script> which is v7 no the newest version. thanks for insta fix.

**Comment by prusnak** [comment]
Fixed in 824ad58895cd2d54ecae5d77de131d749ffada00

Thanks!
