### ISSUE TITLE
How to connect to a bitcoin testnet node? 

### ISSUE THREAD

**Issue by hoangan** [trezor/connect#79]
Hi guys,

Is there a way to connect a bitcoin testnet node (e.g.: https://test-insight.bitpay.com/) ? I saw 2 trezor bitcore node urls hardcoded inside ('https://btc-bitcore3.trezor.io', 'https://btc-bitcore1.trezor.io'). Then I switch to localhost to run the code in development mode, so that I can change the file popup.js and load it locally, instead of loading from https://connect.trezor.io/3/popup/popup.html . However, I then run into another error which is 

```javascript
signtx-paytoaddress.html:31 Error: Input not found
(anonymous) @ signtx-paytoaddress.html:31
(anonymous) @ connect.js:1006
onresponse @ connect.js:1014
respond @ connect.js:867
receive @ connect.js:873
```
Currently, I'm using npm http-server to run this locally. 
A little help for running this in development mode or connecting to a testnet node is appreciated.

Thanks
An

**Comment by hoangan** [comment]
I've tried to run the project hd-wallet separately, which trezor-connect is using, and connect it to https://insight.bitpay.com. However, it seems to fails. Error is: All backends are offline.

It's a bit strange that bitcore1.trezor.io is also an bitpay insight node. I'm wondering why it can connect to bitcore1.trezor.io, but not bitpay? This also may be the reason when I configure trezor-connect to connect to insight.bitpay, it doesn't work. Any idea?

Thanks

**Comment by prusnak** [comment]
https://testnet-bitcore1.trezor.io or https://testnet-bitcore3.trezor.io

**Comment by hoangan** [comment]
Thank you. Any idea why it doesn't work with insight.bitpay.com, since trezor node is also an insight node?

**Comment by prusnak** [comment]
Not really sure :-/

**Comment by runn1ng** [comment]
Bitpay servers don't have the websocket API accessible out to the internet.

**Comment by WilliamXie9** [comment]
@prusnak 
The links seems that it can't be used.
