### ISSUE TITLE
ethereum posláno do Trezor na adresu Ethereum Classic.

### ISSUE THREAD

**Issue by cartoonis** [trezor/connect#797]

**Comment by cartoonis** [comment]
Poslal jsem ethereum z anycoin.cz na můj trezor ale omylem cestou na Ethereum Classic.Z trezoru mi poslali návod jak to zachránit,ale nefunguje.Bylo to přes myetherallet.com,ale po připojení jsem našel 10.000 000 adres jako:0xbC8DafE3399c9c5000b2f0F3963eBe013******,ale žádná ta moje.Jak ta špatná či ta správná pro Ethereum.M

**Comment by mmahut** [comment]
f

**Comment by mmahut** [comment]
F

**Comment by prusnak** [comment]
Kontaktujte prosim nas support, Github neni support kanal -> https://trezor.io/support

**Comment by cartoonis** [comment]
to by museli napřed nějak reagovat!Myslíte,že jim,nebo vám nepíši....
