### ISSUE TITLE
signMessage error: Forbidden key path

### ISSUE THREAD

**Issue by johnbailon** [trezor/connect#799]
Trying to sign a message using Ethereum address:
```javascript
const signMessage = await TrezorConnect.signMessage({
  path: "m/44'/60'/0'/0/0",
  message: 'test mesage',
});
```

this returns:

```json
{ 
  "id": 1,
  "success": false,
  "payload": {
    "error": "Forbidden key path",
    "code": "Failure_DataError" 
    }
}
```
Take note that the `path` is taken directly from ```TrezorConnect.getAccountInfo()```.
This works for bitcoin (passing along the proper derived address path) but fails with Ethereum. What am I missing?

**Comment by prusnak** [comment]
Aren't you using Testnet network (Ropsten, Kovan, etc.) by any chance?

**Comment by johnbailon** [comment]
> Aren't you using Testnet network (Ropsten, Kovan, etc.) by any chance?

No, using mainnet. Well at least,  I don't specify any network on my `TrezorConnect.getAccountInfo()` params. (Is that even possible?)

**Comment by prusnak** [comment]
Ah, now I understand the issue - you need to be using `ethereumSignMessage`. 

`signMessage` is meant to be used for Bitcoin.

**Comment by johnbailon** [comment]
🤦  Thank you!
