### ISSUE TITLE
Trezor detection

### ISSUE THREAD

**Issue by ondra-novak** [trezor/connect#8]
Hi. I am just playing with trezor connect and there are few features I am missing. One of them is trezor detection. I want to show UI to user only if he/she can use the trezor. The feature can detect whether the bridge/extension is presented - this should be enough to achieve this requirement (user without the bridge probably hasn't the trezor at all).

Other missing features may appear in separate issues :)

Thank you!

**Comment by prusnak** [comment]
Closed as duplicate of https://github.com/trezor/connect/issues/124
