### ISSUE TITLE
Shared Secrets

### ISSUE THREAD

**Issue by johnbailon** [trezor/connect#804]
Would it be possible to expose ECDH scalar multiplication method? I'd like the ability to be able to generate the same shared symmetric key between two parties.

Consider:
Alice and Bob want to communicate securely through an insecure channel. Both of them have Trezors.
Alice and Bob know each other's public key.

Alice generates shared key via scalar multiplication on Bob's public key and her private key. (Happens on Trezor device)
Bob generates shared key via scalar multiplication on Alice's public key and his private key. (Happens on Trezor device)

This should generate the same key which can then be used to encrypt and decrypt data using something like AES.

```javascript
// Alice's side
const sharedKey = await TrezorConnect.scalarMult({
 path: "m/44'/0'/0'",
 pubKey: bobPubKey,
});
const encryptedMessage = aes_encrypt('Hi Bob, i like you.', sharedKey);
// Alice sends encryptedMessage via insecure channel
```

```javascript
// Bob's side
const sharedKey = await TrezorConnect.scalarMult({
 path: "m/44'/0'/0'",
 pubKey: alicePubKey,
});
const decryptedMessage = aes_decrypt(encryptedMessage, sharedKey);
// Bob proceeds to blush
```

I see [this](https://github.com/trezor/trezor-firmware/blob/master/crypto/ed25519-donna/curve25519-donna-scalarmult-base.c) in the firmware monorepo, but not sure if its exactly what I need for this operation, my C is a little rusty. Can this operation be exposed via connect?

**Comment by tsusanka** [comment]
Hi, thank you for your report. This is not currently on our roadmap, we would have to expose these crypto calls via firmware and we do not have product usage for this at the moment.

Also I belive if Alice and Bob know each other's public key, they can simple transact the symmetric key using asymmetric encryption. I am closing this as there is not much we can do about this but feel free to continue the discussion here.
