### ISSUE TITLE
Trezor Connect stays loading in Firefox

### ISSUE THREAD

**Issue by FBrinkkemper** [trezor/connect#814]
I'm using an application with Trezor Connect. The Trezor connect page stays loading infinitely on the latest Firefox, and doesn't allow me to continue. Using the same application on the latest Chrome allows me to continue in Trezor connect. 

The firmware is up to date of the Trezor.

**Comment by keraf** [comment]
Could you provide some additional information please? A link to the application, your OS, Firefox version, etc... And maybe even the output from the devtools (F12). As is, it will be hard to figure out the issue, any extra information helps.
