### ISSUE TITLE
Encountered invalid prev_hash signing error

### ISSUE THREAD

**Issue by pbca26** [trezor/connect#823]
I'm having an issue signing a Komodo compatible transaction. I double checked everything but still fail to find what am I missing. Can you have a look please? I assume it got something to do with nExpiry field? I read zip-0203 (https://zips.z.cash/zip-0203#specification) and it mentioned there that when both fields Locktime and nExpiry are set they must be equal to a height value not timestamp. Could this be an issue?

This is my Trezor object:
```
{
  "versionGroupId":2301567109,
  "branchId":1991772603,
  "overwintered":true,
  "version":4,
  "push":false,
  "coin":"kmd",
  "locktime":0,
  "outputs":[
    {
      "address":"RDbGxL8QYdEp8sMULaVZS2E6XThcTKT9Jd",
      "amount":"100000000",
      "script_type":"PAYTOADDRESS"
    },
    {
      "address_n":[
        2147483692,
        2147483789,
        2147483648,
        "1",
        "0"
      ],
      "amount":"316920493200",
      "script_type":"PAYTOADDRESS"
    }
  ],
  "inputs":[
    {
      "address_n":[
        2147483692,
        2147483789,
        2147483648,
        "0",
        "9"
      ],
      "prev_index":1,
      "prev_hash":"a066734b1bd3bf37f4d13e58caadf3d40baff23987ca51cd7cbb24b22a7b6c9a",
      "amount":"317020503200"
    }
  ],
  "refTxs":[
    {
      "hash":"a066734b1bd3bf37f4d13e58caadf3d40baff23987ca51cd7cbb24b22a7b6c9a",
      "inputs":[
        {
          "prev_hash":"a037325dfb9630e24bffb10af6943609a62532cf510398b1a047d6506572b813",
          "prev_index":1,
          "script_sig":"47304402202b2f85a5cf752ebefb09643ef68ea1f1dee3bfc6b8119f5001b92a5bda301ab4022054d53fec36f3bf570d4e198f583f89e8a5be2bfc190da1857a06c26bf853718c012102bf8d4f63c16211de9a00123eadde26e74756cbd9c6dff24d551ed26cf1ad33ce",
          "sequence":4294967294
        }
      ],
      "bin_outputs":[
        {
          "amount":487280618121128060,
          "script_pubkey":"76a914fd38339028671bdf86b722ab6b842282b875a35b88ac"
        },
        {
          "amount":317020503200,
          "script_pubkey":"76a914b680d79bd4e070c8455e87dc6bdceb79c142301888ac"
        }
      ],
      "version":4,
      "lock_time":1612044751,
      "version_group_id":2301567109,
      "branch_id":1991772603,
      "extra_data":"0000000000000000000000",
      "expiry":2718
    }
  ]
}
```

**Inputs:**
Decoded https://wsb.explorer.dexstats.info/insight-api-komodo/tx/a066734b1bd3bf37f4d13e58caadf3d40baff23987ca51cd7cbb24b22a7b6c9a
Raw https://wsb.explorer.dexstats.info/insight-api-komodo/rawtx/a066734b1bd3bf37f4d13e58caadf3d40baff23987ca51cd7cbb24b22a7b6c9a
Decoded https://wsb.explorer.dexstats.info/insight-api-komodo/tx/a037325dfb9630e24bffb10af6943609a62532cf510398b1a047d6506572b813
Raw https://wsb.explorer.dexstats.info/insight-api-komodo/rawtx/a037325dfb9630e24bffb10af6943609a62532cf510398b1a047d6506572b813

**Comment by szymonlesisz** [comment]
looks like the explorer you are using doesn't return correct values

`bin_outputs[0].amount` should be `487280618121128100` 
you need to use string instead of number because this value is greater than [Number. MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

so your `bin_outputs` should be:

```
"bin_outputs": [
      {
            "amount": "487280618121128100",
            "script_pubkey": "76a914fd38339028671bdf86b722ab6b842282b875a35b88ac"
       },
       {
            "amount": "317020503200",
            "script_pubkey": "76a914b680d79bd4e070c8455e87dc6bdceb79c142301888ac"
        }
 ],
```

**Comment by szymonlesisz** [comment]
i'm using [this script](https://github.com/trezor/connect/blob/develop/tests/__txcache__/gen-reftx.js) to generate referenced transactions

in your case: hex == raw tx and change `BitcoinJs.Transaction.USE_STRING_VALUES = true;`

**Comment by pbca26** [comment]
You are correct, explorer is altering data for some reason. We're using an old version of Insight Explorer modified for Komodo. I guess we will need to patch it.

Thanks a lot for identifying the issue!

**Comment by pbca26** [comment]
When I'm trying to use @trezor/utxo-lib lib to decode raw transaction hex I ran into the following issue.

index.js:1098 Uncaught (in promise) RangeError: Trying to access beyond buffer length
    at checkOffset (index.js:1098)
    at Uint8Array.readUInt32LE (index.js:1148)
    at readUInt32 (transaction.js:113)
    at Function../node_modules/@trezor/utxo-lib/src/transaction.js.Transaction.fromBuffer (transaction.js:317)
    at Function../node_modules/@trezor/utxo-lib/src/transaction.js.Transaction.fromHex (transaction.js:389)

It does seem to work on nodejs side fine and I get a decoded transaction using the same lib. Is it a browser limitation?
