### ISSUE TITLE
Ethereum EIP-712 structured signatures isn't supported

### ISSUE THREAD

**Issue by artall64** [trezor/connect#825]
Reference: https://eips.ethereum.org/EIPS/eip-712
This EIP become widely use over the Ethereum Network, but looks like it's isn't available via SDK

Any plans to support this ?

**Comment by szymonlesisz** [comment]
depends on https://github.com/trezor/trezor-firmware/pull/1568

**Comment by ghost** [comment]
> Reference: https://eips.ethereum.org/EIPS/eip-712
> This EIP become widely use over the Ethereum Network, but looks like it's isn't available via SDK
> 
> Any plans to support this ?

You can ask them on this thread over here https://github.com/trezor/trezor-firmware/pull/1568

**Comment by aydnep** [comment]
Hi guys. any updates on EIP-712 support?

**Comment by ghost** [comment]
> Hi guys. any updates on EIP-712 support?

It looks like it's being tracked over here https://github.com/trezor/trezor-firmware/pull/1835

**Comment by yura-pakhuchiy** [comment]
Any updates on this? trezor/trezor-firmware#1835 is merged, but not really usable without connect counterpart

**Comment by yura-pakhuchiy** [comment]
@xlab maybe you have some code for connect ready?

**Comment by mroz22** [comment]
Hello there. We don't have it in our plans in near future but we are happy to review and merge any contribution from comunity.

**Comment by artall64** [comment]
Does't mean that EIP-712 support wouldn't be released on Trezor in 2021 ?
It's a key requirement for limit orders and much more DeFi stuff on Ethereum-like networks.

**Comment by prusnak** [comment]
> Does't mean that EIP-712 support wouldn't be released on Trezor in 2021 ?

Will be released in early 2022. Please be patient.

**Comment by tsusanka** [comment]
We have released EIP-712 support [in January](https://blog.trezor.io/trezor-suite-and-trezor-model-one-firmware-updates-january-2022-4a77e4a07a5a) release.
