### ISSUE TITLE
Protect develop branch

### ISSUE THREAD

**Issue by goodhoko** [trezor/connect#826]
Today I accidentally pushed [two](https://github.com/trezor/connect/commit/37eb8b9e1ea775225548482dd81e66de889c083e) [commits](https://github.com/trezor/connect/commit/a4de06923b9ad08d1bd9be85be9af389f0507fa2) directly to the `develop` branch. (I was working in a terminal and thought I'm on a feature-branch while in fact I wasn't.)

To prevent this in future we should make the branch protected and require changes to go through a code review before merging to `develop`.

**Comment by szymonlesisz** [comment]
we talked about this in person, it's not required.

closing
