### ISSUE TITLE
Is Bitcoin Cash supported?

### ISSUE THREAD

**Issue by matiu** [trezor/connect#83]
Hello, Copay Dev here.

We have been asked by many users to support BitcoinCash on Copay/Trezor for multisig wallets. Some users mentioned BitcoinCash was already supported on Trezor, but I can't find any documentation on that, an I see also:

https://github.com/trezor/connect/commit/3d64e070066fc1d18f6329f98a3ebc9ae28adabf

Was bitcoinCash support was removed? Any advice how to allow our users to sign a multisig transaction with trezor? thanks.

**Comment by prusnak** [comment]
Connect supports BCash, the code that was removed was moved to a separate repo for claiming BCH coins. Multisig have not changed and should work the same way as it does for Bitcoin.

**Comment by matiu** [comment]
Thanks, as soon as  https://github.com/trezor/connect/issues/84 gets solve we will add Cash support then.
