### ISSUE TITLE
Enter PIN ui is not shown when used with node.js

### ISSUE THREAD

**Issue by evgenynacu** [trezor/connect#843]
I try to use 8.1.27-extended version of trezor-connect in nodejs (with Trezor One)
When I try to do something like this:

```
TrezorConnect.ethereumGetAddress({ path: "m/44'/60'/0'/0/0" })
    .then(console.log)
    .catch(console.log)
```

PIN dialog is shown on the device, but not on the PC display.

How this flow should work? (when some ui should be shown)
Do I have to show some UI manually?

**Comment by szymonlesisz** [comment]
Hi @evgenynacu,

connect does not have any UI dedicated for nodejs.
you will need to create own based on `UI_EVENT`

example:
https://github.com/trezor/connect/blob/develop/examples/electron/main-process/src/trezor-connect-ipc.js#L45-L91

**Comment by evgenynacu** [comment]
Thanks, then let's close
