### ISSUE TITLE
BCash support

### ISSUE THREAD

**Issue by gabrielbazan7** [trezor/connect#85]
Hi ! Copay dev here. I'm trying to sign a Bitcoin Cash transaction using connect. I couldn't find any documentation about it. I'm doing it this way but I get an error:

``` 
$log.debug('Signing with TREZOR/CASH', inputs, outputs);
TrezorConnect.signTx(inputs, outputs, callback, '1.5.2', 'Bcash');
``` 
this is the log output: 
```
Signing with TREZOR/CASH [{"address_n":[-2147483604,-2147483648,-2147483648,0,1],"prev_index":0,"prev_hash":"290c8701f14f801429e8e7b66626f12322b20d78101f68b39225ba7a56d762ba"},{"address_n":[-2147483604,-2147483648,-2147483648,0,0],"prev_index":1,"prev_hash":"ea36acbe59a58186f2b9c27413d6aa245e476c8c25a60358ddf73cb50a80df65"}] [{"address":"CcGKgjnmPwWYguus1aUxGdPFQ8Av7NhK66","amount":104505,"script_type":"PAYTOADDRESS"}]
```
error: 
```
"RPCError: No such mempool or blockchain transaction. Use gettransaction for wallet transactions."
```

Could you share some documentation with me ?

**Comment by szymonlesisz** [comment]
Hi @gabrielbazan7,
Recently we have released a new version (v4) which support segwit, BitcoinCash and altcoins.
Are you using a newest version?

you can try it here:

https://connect.trezor.io/4/examples/composetx.html
or
https://connect.trezor.io/4/examples/signtx-paytoaddress.html

**Comment by johnvamo** [comment]
Hi, I am writing here a note in order to get a notification when the integration is ready. Thanks for your support.
