### ISSUE TITLE
Docs: Wrong Function Name

### ISSUE THREAD

**Issue by 360disrupt** [trezor/connect#87]
In the library there is a function named `signEthereumTx` but in the docs there is a function which is not existent in the library: `ethereumSignTx`

https://github.com/trezor/connect#sign-ethereum-transaction

**Comment by szymonlesisz** [comment]
Hi @360disrupt,
Both cases are valid and both are present in connect, signEthereumTx is a backward compatible name.

https://connect.trezor.io/4/connect.js
look at lines 269 and 274
