### ISSUE TITLE
Is it possible to get the matching BIP44 address for a given wallet address? (Ethereum)

### ISSUE THREAD

**Issue by jasperdardx** [trezor/connect#870]
I'm trying to get the BIP44 address (which I need to sign a transaction) for a given wallet address. I know the opposite is possible using the 'ethereumGetAddress' method.

**Comment by szymonlesisz** [comment]
Hi @jasperdardx,

No it's not possible, first of all it will hard to determine when to stop looking for given address. at account 10 or account 1000?
Also this kind of "scanning" through your device could be treated as a vulnerability.
