### ISSUE TITLE
WebUSB pairing is broken with MetaMask 10.0.0

### ISSUE THREAD

**Issue by aloceros** [trezor/connect#873]
During pairing of a Trezor the extension attempts to load

chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/trezor-usb-permissions.html

This results in

Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

Also posted to MetaMask at https://github.com/MetaMask/metamask-extension/issues/11809

**Comment by Roninkhan** [comment]
I am experiencing the same issue any help would be appreciated.

**Comment by matejkriz** [comment]
fixed in MetaMask
