### ISSUE TITLE
Passphrase is incorrect in Cardano functions

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/connect#877]
This problem is occurring only in Suite when passing the device object.

**Affected functions:**

- cardanoSignTransaction
- cardanoGetAddress

**Code example:**
```
await TrezorConnect.cardanoGetAddress({
    device: <HERE>,
    useEmptyPassphrase: device.useEmptyPassphrase,
    addressParameters: {
        stakingPath: getStakingPath(account.accountType, account.index),
        addressType: getAddressType(account.accountType),
        path,
    },
    protocolMagic: getProtocolMagic(account.symbol),
    networkId: getNetworkId(account.symbol),
});
```

While calling one of these two functions you will get the error message *Passphrase is incorrect*.
Tested on firmware versions `2.3.6`, `2.4.0` and `2.4.1`.

The weird thing is that with firmware `2.4.1` it's successful for the first time and unsuccessful (*passphrase is incorrect*) for the second time.

Maybe it could be something about the passphrase caching?

**Screenshot:**

![image](https://user-images.githubusercontent.com/3112191/129807800-79f171d7-ddad-4b3a-ae80-940f3ada29a2.png)

**Comment by szymonlesisz** [comment]
Hi @vladimirvolek,
yes we are aware about passphrase problems with cardano which is kinda blocker for integration in suite:
https://github.com/trezor/trezor-firmware/issues/1231

Do you have any other coins enabled? maybe this is the reason why it previously works

**Comment by matejkriz** [comment]
should be fixed in https://github.com/trezor/connect/pull/933

**Comment by vladimirvolek** [comment]
It is :))
