### ISSUE TITLE
Signing ETH Transaction {success: false, error: "e.slice is not a function"}

### ISSUE THREAD

**Issue by 360disrupt** [trezor/connect#88]
CoffeeScript
```
    @.signTransaction = ()->
      console.log TrezorConnect 
      @.address_n = "m/44'/60'/0'/0"
      @.nonce = 0
      @.gas_price = (21000).toString(16)
      @.gas_limit = (200000).toString(16)
      @.to = "0x6B17E1fD175E39115EfE19ee4ee31BF02e22baD6"
      @.value = 100 #wei
      @.data = 0
      @.chain_id = null

      callback = (err)->
        console.log "Transaction processed", err

      TrezorConnect.signEthereumTx(
        @.address_n,
        @.nonce,
        @.gas_price,
        @.gas_limit,
        @.to,
        @.value,
        @.data,
        @.chain_id,
        callback
      )
```

 console.log TrezorConnect:
` {ERR_TIMED_OUT: "Loading timed out", ERR_WINDOW_CLOSED: "Window closed", ERR_WINDOW_BLOCKED: "Window blocked", ERR_ALREADY_WAITING: "Already waiting for a response", ERR_CHROME_NOT_CONNECTED: "Internal Chrome popup is not responding.", …}
`
When calling the function the Trezor popup appears but disappears while `loading`.

**Comment by szymonlesisz** [comment]
Hi 360disrupt,

It looks like you are sending wrong type of inputs.
According to example: 
https://connect.trezor.io/4/examples/signtx-ethereum.html 
(look at source code)

**nonce** should be a hex
**data** should be a hex or null - not a number
**value** should be a hex not a number
**chain_id** should be a 1 or 61 (etc/eth)
