### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by pointtoken** [trezor/connect#89]
In this repo, the version of connect.js is 2. However, the version in MEW is version 3 and there also seems to be a version 4 as this url works: https://connect.trezor.io/4/examples/

Is this repo out of date with the latest version?

**Comment by prusnak** [comment]
Yes, https://github.com/trezor/connect/tree/v4 is the latest.

**Comment by runn1ng** [comment]
We updated master documentation, thx for reporting this

**Comment by pointtoken** [comment]
Awesome, thanks for clarifying!
