### ISSUE TITLE
Cardano Catalyst registration documentation

### ISSUE THREAD

**Issue by Scitz0** [trezor/connect#899]
I'm in the process of implementing Cardano Catalyst voting registration support into our wallet but noticed that the documentation example most likely needs an update.

https://github.com/trezor/connect/blob/develop/docs/methods/cardanoSignTransaction.md
```
auxiliaryData: {
    catalystRegistrationParameters: {
        votingPublicKey:
            "1af8fa0b754ff99253d983894e63a2b09cbb56c833ba18c3384210163f63dcfc",
        stakingPath: "m/1852'/1815'/0'/2/0",
        rewardAddressParameters: {
            addressType: CardanoAddressType.BASE,
            path: "m/1852'/1815'/0'/0/0",
            stakingPath: "m/1852'/1815'/0'/2/0",
        },
        nonce: "22634813",
    },
},
```
rewardAddressParameters here I think should be of type CardanoAddressType.REWARD
E.g.
```
rewardAddressParameters: {
    addressType: CardanoAddressType.REWARD,
    path: "m/1852'/1815'/0'/2/0",
},
```
This matches with [Adalite implementation](https://github.com/vacuumlabs/adalite/blob/d09b4db5ecfcea5a5165f23ef76514695cd7fec0/app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts#L377-L380) that is confirmed to be working on mainnet. Using address like in the current example also failed in my implementation while Adalite way worked.

**Comment by matejkriz** [comment]
@refi93 @gabrielKerekes could you please check? Is it ok with you?

**Comment by gabrielKerekes** [comment]
Changing the example makes sense, yes. Although Trezor firmware doesn't limit the address to only `CardanoAddressType.REWARD` i.e. any address is allowed at the moment.
