### ISSUE TITLE
DER format

### ISSUE THREAD

**Issue by AMS777** [trezor/connect#909]
Hello,

Is there any way to get a Trezor device to sign a message with DER (ASN.1) format? 

If that option is not available, do you know how to convert the output of `ethereumSignMessage()` to DER format?

Thanks!

**Comment by matejkriz** [comment]
cc @matejcik @prusnak any idea, please?

**Comment by matejcik** [comment]
Trezor does not allow signing arbitrary message bytes. If you're using `EthereumSignMessage`, you are getting a signature for `"\x19Ethereum Signed Message:\n" ‖ str(len(b)) ‖ b`, where `b` is your message bytes. You can of course stuff DER-encoded data in there, but the signature is not over DER.

The returned signature from `ethereumSignMessage` is 65 bytes:
1. first 32 bytes are the value of `r` in big endian order
2. following 32 bytes are the value of `s` in big endian order
3. last byte is value of `v`

You can use any publicly available DER encoding library to encode the `(r, s)` pair and get back what is usually considered a "DER signature".

It would be helpful to know what your actual usecase is. Wouldn't it be better to just use one of the existing standards, such as EIP-712, which will be included in Trezor soon?

**Comment by AMS777** [comment]
Thank you for the clarification.

We finally went for a more general purpose device that that better suits signining arbitrary bytes (YubiKey).
