### ISSUE TITLE
Accessing transaction history for active addresses

### ISSUE THREAD

**Issue by FlorianML** [trezor/connect#910]
I haven't seen the ability to do this so I apologize if this is already a feature and can close the issue.

Is there any way to directly retrieve the transaction history of addresses that were generated from the device?  For example, if the address (0x12345) was involved in receiving 1 ETH and sending 0.5 ETH, is there a way to pull that transaction history from the device without having to go through a block explorer.

**Comment by szymonlesisz** [comment]
Hi @FlorianML ,

sure. use `getAccountInfo` method where `descriptor` param is your `0x12345` address:

https://trezor.github.io/connect-explorer/#/method/ethereumGetAccountInfo-advanced

(use "details: transactions")
