### ISSUE TITLE
Access account that was generated using derivation path

### ISSUE THREAD

**Issue by lukasmatta** [trezor/connect#911]
Hello,

the following situation happened to me: In Trezor, I have only 1 BTC account with 0 funds on it (there is a rule that I can't create a new account when I have only 1 account with 0 funds on it). However, I was able to generate a new account using the derivation path, then I sent funds to it.

Now I can not access this account using Trezor web interface/Trezor suite. What's the solution?

Thanks.

**Comment by szymonlesisz** [comment]
Hi @lukasmatta,

you can still access this account using trezor-connect (in the same way as you created it)
using for example:
https://trezor.github.io/connect-explorer/#/method/getAccountInfo

if you want your account to be visible by trezor suite/wallet you need to "fill the gaps" by sending some tx into 1st account.

**Comment by lukasmatta** [comment]
Hello @szymonlesisz,

thanks for your response. Is it really necessary to "fill the gaps" by design? Or is it just a feature of Trezor suite/wallet? If it's just a feature, I'd consider refactoring it so the user can make visible any account.

**Comment by szymonlesisz** [comment]
this rule is there for a reason (and its there since the beginning) otherwise how wallet would know when to stop discovering accounts?
after 10th account? after 1000th account? never?

same rule applies to receive addresses, you shoudnt have gaps larger than 20 empty addresses in your account.

**Comment by lukasmatta** [comment]
@szymonlesisz I expected it would check few accounts (let's say the first 5 sounds reasonable). But I definitely see your point now, thanks for explaining it to me.

**Comment by szymonlesisz** [comment]
98% of users have max. 1-2 accounts.
checking 5 for everyone (where 4 of them are empty) would be wasting resources/backend traffic.
