### ISSUE TITLE
Does Trezor support Goerli?

### ISSUE THREAD

**Issue by peculiarity** [trezor/connect#918]
Just to be on the safe side. I've seen in the Trezor App and also on the forum that it supports only Ropsten. I would like to know if that's the case? A person reported that they were able to sign a TX on kovan as well.

**Comment by szymonlesisz** [comment]
looks like it does:
https://github.com/trezor/trezor-firmware/blob/d318a293431f6ff6fbed5d650360ca9fcc364f67/core/src/apps/ethereum/networks.py#L548

use chainId `420`

**Comment by Ncortesa** [comment]
I'm having the same issue. There is already some solution available?

**Comment by sime** [comment]
It's being tracked here: https://github.com/trezor/trezor-suite/issues/6441

Ideally to be released in November.
