### ISSUE TITLE
Inconsistency Between getAccountInfo and ethereumGetAddress

### ISSUE THREAD

**Issue by pointtoken** [trezor/connect#92]
Hey - I noticed that if I call ethereumGetAddress, the Trezor requires confirmation from the user, but getAccountInfo doesn't. Seems like it should be the same -- either read queries require confirmation or they don't, otherwise could be confusing for the user.

**Comment by pointtoken** [comment]
BTW, I get why you do this since you are calling out to the blockchain in the case of everything but eth, but in the case of eth, you are just providing address. Still it is confusing for the user a bit, how eth acts different

**Comment by pointtoken** [comment]
I guess the work around is to ask for the eth public key,  which gives the desired behavior. Regardless, it would be nice if the ethereumGetAddress didn't require the user touching the device itself.

**Comment by prusnak** [comment]
GetAddress is used by wallets to present the address to the user on TREZOR screen. GetPublicNode is used by wallets to load account public keys. Try it in MyEtherWallet for example, and it will start making sense.
