### ISSUE TITLE
Problems connecting to Ronin Wallet

### ISSUE THREAD

**Issue by pauserratgutierrez** [trezor/connect#925]
Hi, I own a Trezor T with the last version. Trezor works fine for me.

When I try to "Connect a new hardware wallet" in Ronin using Trezor I get a chargin screen that never charges.
![image](https://user-images.githubusercontent.com/73240206/139214574-08f645bd-40b6-47a7-b808-3524f977baa4.png)

![image](https://user-images.githubusercontent.com/73240206/139214645-f2f5f012-6198-434f-9218-6c98b3289b86.png)

![image](https://user-images.githubusercontent.com/73240206/139214728-89f48bd5-bd27-4c9b-aedc-540a8c0adb87.png)

But sometimes it works and I can add accounts:
![image](https://user-images.githubusercontent.com/73240206/139215891-869aa765-496e-416a-848d-a8ec47b7f4c9.png)

**Comment by mroz22** [comment]
Hello, try to upgrade your firmware please. You can use trezor suite wallet for this https://suite.trezor.io/web/. 

I just tried this ronin wallet with my device and it worked correctly. 

If problems are still around try to gather more technical info please (firmware version, browser version, whatever logs are available..)
