### ISSUE TITLE
Can not sign transactions, fw 2.4.2

### ISSUE THREAD

**Issue by TrejGun** [trezor/connect#938]
First, there is a warning popup saying  -
"The current version of firmware (2.4.2) may be not compatible with the running version of Trezor Connect"

Second, there is an error when signing transaction: 

index.tsx:114 Error: Invalid parameters: Parameter "chainId" has invalid type. "number" expected.
at TrezorSubprovider.<anonymous> (trezor.js:164)

All with fresh Trezor-T initialized with fw 2.4.2 and auto-downloaded trezor-connect at first connect

**Comment by mroz22** [comment]
looks odd 

1. what wallet did you use?
1. does https://suite.trezor.io/web/ work for you?

**Comment by mroz22** [comment]
Hello, I hope you managed to resolve your problem. If your problem still persist, feel free to reopen this but please provide more info.
