### ISSUE TITLE
Auto Generation of Public Address

### ISSUE THREAD

**Issue by njags** [trezor/connect#94]
Hello,

We are working at the moment on developing a web application to integrate with Trezor. At the moment we are successfully able to integrate it using trezor.js to pull the account information with the address of the selected wallet. We are not able to get the multiple address generated or update the automatic new address generated by trezor once a transaction is done on trezor. At the moment we are working on it manually and would like to get it done automatically without the device being connected to the machine everytime to only generate the address.

We would also like to learn how can we know the used address on trezor to keep a track of it and fetch a new bitcoin address once it is been used.

Also the maximum new address we can create is 20 address for bitcoin we will also need this restriction to be removed as we are currently having more than 5000 registered users and displaying unique address from trezor wallet for each user is mandate for us to on path of security and db record purpose

The application we are developing is in ASP.NET C# and SQL Server 2012.

It would be good if someone could help me on immediate basis to resolve this issue.

**Comment by prusnak** [comment]
Look into the export public key feature: 
https://github.com/trezor/connect/blob/master/README.md#export-public-key
Once exported, xpub allows you to generate addresses without having the
device connected. Also you  can generate as many addresses as you want,
but keep in mind that most of the wallets will not show you the
addresses beyond the unused gap of 20 addresses.

**Comment by njags** [comment]
Hello,

Thank you for your quick reply, basically we are developing a Exchange Platform and at the moment the number of users we have is huge and to have unique / not the same address for every user is mandate. Can we have some way possible to make the unused gap of 20 address increase based on our requirements.

**Comment by prusnak** [comment]
No, this is up to the wallets and they implement the standard.

**Comment by prusnak** [comment]
You can use addresses beyond the gap, of course, just normal wallets
won't be able to see them.

**Comment by njags** [comment]
Ok, Thanks, I will have a look on the documentation and keep you posted with the development sharing my work.

**Comment by njags** [comment]
Hello,
we want  to pull the account information with the address of the selected wallet. We are not able to get the single and  multiple address generated or update the automatic new address generated by trezor once a transaction is done on trezor.
https://github.com/trezor/connect/blob/master/examples/xpubkey-ethereum.html

**Comment by njags** [comment]
we are using the above link

**Comment by njags** [comment]
Hello,
we want to pull the account information with the address of the selected wallet. We are not able to get the single and multiple address generated or update the automatic new address generated by trezor once a transaction is done on trezor.
we are using this code:
https://github.com/trezor/connect/blob/master/examples/xpubkey-ethereum.html

description:
when we are using this code at starting point we are not getting your response
 var path = "m/44'/60'/0'"; 
         TrezorConnect.getXPubKey(path, function (response) {  }

the response is callback function not getting the values of the address path. it not showing error also directly exit the code. so we are not getting any solution of the multiple addresses.

**Comment by prusnak** [comment]
Ah, you should have said from the beginning you want to use Ethereum, not Bitcoin.

You should find a tool that can generate Ethereum addresses from provided "xpub", but this is out of the scope of Connect. For Bitcoin, there are many tools, such as [https://github.com/prusnak/bip32utils](bip32utils), which do that. Ask in the Ethereum community if there is an equivalent of this.

**Comment by njags** [comment]
Hello,

Apologies if I am not able to explain the integration we are trying to do using Trezor. We are using Trezor API to get all their possible crypto available.

Also we would like to get multiple address generated for each of the crypto using the Trezor API.

As of now we did try to use Trezor API for bitcoin but we get no response when we run the javascript to get the result.

**Comment by njags** [comment]
The link you have in the reply directs me to a 404 error page.

**Comment by 93Kamuran** [comment]
> The link you have in the reply directs me to a 404 error page.

Hi, could you find a solution for your problem ? 

Im looking for this on  a few days
