### ISSUE TITLE
Ethereum breaking changes 2.4.1 - 2.4.2 

### ISSUE THREAD

**Issue by mroz22** [trezor/connect#940]
I found that firmware version 2.4.1 and 2.4.2 produce different results for this fixture https://github.com/trezor/trezor-firmware/blob/a01516389a5a98f0d63205fdd40f8907e2054f87/common/tests/fixtures/ethereum/sign_tx_eip155.json#L160

I am using `trezorctl ethereum sign-tx -c 11297108109 -n "m/44'/60'/0'/0/0" --nonce 0 --gas-price 20000000000 --gas-limit 21000 0x8eA7a3fccC211ED48b763b4164884DDbcF3b0A98 10000000000`

2.4.1
```
{
  "nonce": 0,
  "gasPrice": 20000000000,
  "gasLimit": 21000,
  "to": "0x8ea7a3fccc211ed48b763b4164884ddbcf3b0a98",
  "value": 10000000000,
  "data": "",
  "from": "0x548b180e56e41ff8532e1deea87ee7af66a92577",
  "r": "0ecc50afef98c57adbbf633965419de191a31c326510fce4913a312b02457065",
  "v": "0542b8613e",
  "s": "0b8b7267d2e09b5ce330dcd34579f36f01aa91745640d14bbcb017e924650517"
} 
```
2.4.2
```
{
  "nonce": 0,
  "gasPrice": 20000000000,
  "gasLimit": 21000,
  "to": "0x8ea7a3fccc211ed48b763b4164884ddbcf3b0a98",
  "value": 10000000000,
  "data": "",
  "from": "0x73d0385f4d8e00c5e6504c6030f47bf6212736a8",
  "r": "9d05ca7cdcf971f3114c0ef8d636c5aae1353bb227e04ec1198c60d874e676c0",
  "v": "0542b8613e",
  "s": "35414067209e27fb690d9387264c74e334e25a117705f3583fb24434a952c9ca"
}
```
both are using all seed without passphrase. 

2.4.1 results seem to be incorrect, should we bump minimum required firmware version for this type of operation?

**Comment by matejkriz** [comment]
not important
