### ISSUE TITLE
v8.2.3-extended failing with "Transport is missing"

### ISSUE THREAD

**Issue by gabrielKerekes** [trezor/connect#966]
We were trying out the new 8.2.3. extended release with [cardano-hw-cli](https://github.com/vacuumlabs/cardano-hw-cli) and we are not able to make any (e.g. `getVersion`) calls to the Trezor device. We tried with 2.4.3 physical device and emulator, also with older FWs and trezor bridge version 2.0.27. The non-extended release seems to work fine on the same setup - we have tested that via a test app of ours.

It seems to us that https://github.com/trezor/connect/commit/580cc0e177c923eba92286f9bae200a6ac2ee209 broke the extended build as a build from https://github.com/trezor/connect/commit/424e0c0a500f81c7b3daeab37855250762268805 works. Also `8.2.3-beta.3` works and `8.2.3-beta.4` doesn't. By adding logs to `node_modules/trezor-link/lib/bridge/v2.js` we observed, that it seems that the request to `http://127.0.0.1:21325` doesn't seem to go through, but maybe the problem is elsewhere.

Is there perhaps something we might be doing wrong or perhaps something else which needs to be updated, which we haven't done or is this a bug?

**Comment by gabrielKerekes** [comment]
The issue has been confirmed to us also by people working on the Trezor Daedalus integration. Updating to the official 8.2.3 extended release breaks the integration. `8.2.3-beta.3` works.

@mroz22 @szymonlesisz could you please take a look? 🙏  Firmwares are being updated and Daedalus stops working with them -> https://github.com/input-output-hk/daedalus/issues/2777.

**Comment by mroz22** [comment]
Hi, thanks for report. I am looking at this now with priority.

**Comment by mroz22** [comment]
@gabrielKerekes could you please in the meantime try if `8.2.3-beta.8` works for you? This version should be the same as `8.2.3-extended` the only difference is that I removed commit https://github.com/trezor/connect/commit/580cc0e177c923eba92286f9bae200a6ac2ee209

**Comment by davidmisiak** [comment]
> could you please in the meantime try if 8.2.3-beta.8 works for you?

Yes, it works for us (tested with firmware 2.4.3 and hw-cli 1.9.0-rc0).

**Comment by mroz22** [comment]
Ok, I think you can use this release safely for now as it was only an optimization (ironicaly) and had no added or required features. I will ofcourse try to find out where is the problem once this commit is included.

**Comment by mroz22** [comment]
This should now be fixed in `8.2.4-extended` 
please reopen in case you find a problem.
